### ISSUE TITLE
Adjust amount of left padding when line numbers are displayed

### ISSUE THREAD

**Issue by tpapastylianou** [gwsw/less#103]
As mentioned in https://unix.stackexchange.com/questions/624296/remove-left-padding-of-line-numbers-in-less, the amount of padding displayed with line numbers is fixed, as provided by the MIN_LINENUM_WIDTH constant.

It would be useful to be able to adjust this constant as an option to less, (e.g. to preserve screen real-estate, or quickly compare with outputs from other applications)

**Comment by gwsw** [comment]
Fixed by adding the --line-num-width option in 13f1a7d9efe3a017a08bf3666a6da87771734d17
