### ISSUE TITLE
error: implicit declaration of function 'sleep_ms' is invalid in C99

### ISSUE THREAD

**Issue by ryenus** [gwsw/less#104]
```
ch.c:307:5: error: implicit declaration of function 'sleep_ms' is invalid in C99 [-Werror,-Wimplicit-function-declaration]
                        sleep_ms(2); /* Reduce system load */
                        ^
1 error generated.
make: *** [ch.o] Error 1
```

I got the above error when running `make` using gcc.
Here's a link to the related source:

https://github.com/gwsw/less/blob/13f1a7d9efe3a017a08bf3666a6da87771734d17/ch.c#L307

**Comment by gwsw** [comment]
Did you run "make -f Makefile.aut" first, as described in the README?

**Comment by ryenus** [comment]
Ah, my bad, I thought it could be skipped since I had run it before.
Clearly you're right, re-run `make -f Makefile.aut` made it, thank you @gwsw

**Comment by gwsw** [comment]
Yes, it needs to be re-run when a new public function is added, as was the case here.
