### ISSUE TITLE
unexpected wrapping in man pages

### ISSUE THREAD

**Issue by ryenus** [gwsw/less#105]
Using less built from the latest source (13f1a7d9), I see unexpected line wrapping when `-S` is on, 
as in the screenshot below:

![image](https://user-images.githubusercontent.com/610161/102734921-0a22f180-437c-11eb-8fcc-0151fcd7cd2f.png)

**Comment by gwsw** [comment]
Thanks, should be fixed in f580946636b6bbf0245a23ddc1bcece30e3d1388.

**Comment by ryenus** [comment]
Thank you @gwsw for the prompt response, I confirm the issue is now fixed! 👍
