### ISSUE TITLE
Change or allow configuration of search highlight color?

### ISSUE THREAD

**Issue by amreus** [gwsw/less#110]
Hello,

Is it possible to change the search highlight type or color? If not, I would appreciate the ability. 

I have a very difficult time finding the highlighted text in a default Windows terminal. I have attached a screenshot below.  The highlighted word is "tag".  Is it just me? 

Using a color or even just an inverse style would make a huge difference.

Thanks for listening.

![2021-01-02_102510](https://user-images.githubusercontent.com/38442825/103460723-a33ff980-4ce6-11eb-8850-c023ee666a6c.png)

**Comment by gwsw** [comment]
There are several different compilers that can be used to build the Windows version of less; which one did you use? On most of them, the -Ds flag can be used to change the standout (highlight) color.

**Comment by amreus** [comment]
Thanks for the hint on the `-Ds` option - it gave me a clue for the correct syntax.

It's possible I did try using the -D option at some point but never got it to work right.  

My suggestion would be to improve the help file for this option.  For example, specify what the following codes mean: `-D must be followed by n, d, u, k, s or a`, and include a concrete example.

Here is an example of setting the search highlight color to black text on white background:

    $ ls | less -D s0.7

Colors on my machine match the color list for the built-in command `color`:

    0 = Black       8 = Gray
    1 = Blue        9 = Light Blue
    2 = Green       A = Light Green
    3 = Aqua        B = Light Aqua
    4 = Red         C = Light Red
    5 = Purple      D = Light Purple
    6 = Yellow      E = Light Yellow
    7 = White       F = Bright White

Although you need to use decimal numbers and not hex.

My eyes thank you.

I've pasted a section from the Linux man page:


-Dxcolor or --color=xcolor
    [MS-DOS only] Sets the color of the text displayed. x is a single character which selects the type of text whose color is being 
   set: n=normal, s=standout, d=bold, u=underlined, k=blink. color is a pair of numbers separated by a period. The first number
   selects the foreground color and the second selects the background color of the text. A single number N is the same as N.M,
   where M is the normal background color.
