### ISSUE TITLE
less hangs/freezes when scrolling past start or end of file

### ISSUE THREAD

**Issue by bdcarr** [gwsw/less#111]
If I'm at the top of a file and I scroll up (via mouse wheel or `k` key), or the bottom and I scroll down, less freezes for about half a second. The issue is I regularly unlock my scroll wheel and let it fly to get to the top/bottom of a file, which results in dozens of scroll commands being queued and freezing less for several seconds at least. I think it might be triggering my terminal's alert bell? But I have that turned off, and I don't see/hear a bell or any flashing.

I'm using iTerm2 with these notification settings:

![image](https://user-images.githubusercontent.com/1940488/103604196-7c8ef680-4f64-11eb-895b-662d2896ae8e.png)

And my LESS env var is `-RiQ`

Video demonstrating the issue below:

https://user-images.githubusercontent.com/1940488/103603832-9ed44480-4f63-11eb-861d-289030bfc6cb.mp4

**Comment by gwsw** [comment]
Many terminals have a "flash" terminfo entry that changes the color of the terminal, waits 100 milliseconds or so, then changes it back. Sending many of these flash sequences can hang the terminal for a long time, even if you're not displaying the color changes. You could edit your terminfo database to remove the "flash" entry. Or if that is difficult, you can this line to your .lesskey file:
```LESS_TERMCAP_vb=```

That said, I don't think it's reasonable for less to be sending a huge number of flash sequences when the mouse is scrolled at beginning/end of file like it does now. As of 2df9dca3460a678d42aec122bdccb1dccb7384f1 I have changed it to send no more than one per second. This should make the behavior more tolerable even if one doesn't change their terminfo.

**Comment by bdcarr** [comment]
Wow, thanks for updating less based on my feedback! I tried adding that line to ~/.lesskey under each of the #env, #line-edit and #command headers, but it didn't change the behaviour. I'll just wait for the update to come through on homebrew. Thanks mate!

**Comment by gwsw** [comment]
Sorry I wasn't more specific. The ```LESS_TERMCAP_vb=``` line should be in the #env section, and you must run the "lesskey" command after editing the .lesskey file. Let me know if this still doesn't work.

**Comment by bdcarr** [comment]
Oh you beauty, that worked perfectly! Zero hanging when I try to scroll beyond the top/bottom of the file now. Thank you so much!

**Comment by david-fong** [comment]
I just want to chime in with joy about this! I've felt bothered by this for a long time and having this solution feels marvelous.
