### ISSUE TITLE
Mapping ^K in .lesskey

### ISSUE THREAD

**Issue by arp242** [gwsw/less#115]
I'd like to start search (`/`) with `^K` by default, so I added to my `~/.lesskey`:

    #command
    / forw-search ^K

The `^K` inserts some gibberish though:

    Keep-pos /(^F^A

Other combinations, such as `/ forw-search ^R` work fine.

I looked a bit at the source, and it seems [`CONTROL('K')` is handle specially](https://github.com/gwsw/less/blob/master/lesskey.c#L456), and the [`tstr_control_k`](https://github.com/gwsw/less/blob/master/lesskey.c#L364) it inserts does match with what I'm getting: `SK_CONTROL_K` is `40`, and U+0040 is `(`, and `6` and `1` are `^F` and `^A`.

If I comment that out (as a test) it works as expected, I don't know what that does exactly, but I guess that wasn't put in there for the fun of it.

Is there are any way to map `^K`? I couldn't really figure out a way to do this, since `^K` is handle specially everywhere 🤔

**Comment by gwsw** [comment]
Thanks for the report. This should be fixed in 09a76d3fd0bf27547561b8a36eaf5acab188c9cf.

**Comment by arp242** [comment]
Tested and confirmed it works; thank you :-)

**Comment by gwsw** [comment]
BTW, I think you can make this work even without the lesskey fix by putting an actual ctrl-K character in the .lesskey file, rather than the two character sequence "^K".

**Comment by arp242** [comment]
Ah right; that seems to work with the system-provided `lesskey` v563; not sure why I hadn't thought of that. Ah well, still a good fix to have.
