### ISSUE TITLE
Debug Mode for Makefile.wng

### ISSUE THREAD

**Issue by tgrelka** [gwsw/less#119]
The Makefile.wnm has debugging flags which can be optionally enabled.
I feel like Makefile.wng should have something similar. When building less using mingw32-make, I found that I had to add the `-g` flag to CFLAGS / CFLAGS_MINGW to be able to debug successfully.

**Comment by gwsw** [comment]
I am not familiar with mingw, but feel free to submit a pull request for the changes that you want.
