### ISSUE TITLE
If I copy a command that extends multiple lines from a text file, there's a newline added in the middle of the paste

### ISSUE THREAD

**Issue by aki-k** [gwsw/less#123]
This problem only happens if I scroll backwards in the file. If I only scroll forwards or search for the line I want to copy, the problem doesn't happen.

Environment: Fedora 32, Plasma 5 desktop, konsole, GNU Screen

**Comment by gwsw** [comment]
When you scroll back one line, less scrolls the screen down to create a blank line at the top of the screen, then prints the new line in that blank line. On most terminals, this leaves a newline at the end of that line of text. The only way to avoid it would be to repaint the entire screen on every backwards movement, even if it's only one line. You can however avoid the problem by entering the "r" command to manually repaint the screen before you copy text out of it.

**Comment by aki-k** [comment]
How about scrolling backwards a page at a time with b ? Isn't that already painting the entire screen?

**Comment by gwsw** [comment]
Normally if you scroll backwards a full screen, less will scroll and paint one line at a time, so it will still have embedded newlines. However if you use the -c option it will repaint the whole screen forward, and won't have the newlines.

**Comment by aki-k** [comment]
Thanks, this resolved my issue.
