### ISSUE TITLE
undefined reference to tty_device in release v578

### ISSUE THREAD

**Issue by msoyka-of-wharton** [gwsw/less#124]
If I build v578 using mingw I get the following link error:

gcc -L/mingw-w64/i686-8.1.0-posix-dwarf-rt_v6-rev0/mingw32/opt/lib -o less main.o screen.o brac.o ch.o charset.o cmdbuf.o command.o cvt.o decode.o edit.o filename.o forwback.o help.o ifile.o input.o jump.o line.o linenum.o lsystem.o mark.o optfunc.o option.o opttbl.o os.o output.o pattern.o position.o prompt.o search.o signal.o tags.o ttyin.o version.o -lregex
lsystem.o:lsystem.c:(.text+0x79): undefined reference to `tty_device'
collect2.exe: error: ld returned 1 exit status

**Comment by gwsw** [comment]
Thanks, should be fixed in 0c08883a66a5ad4039f9587401872d9e390b09e3.

**Comment by msoyka-of-wharton** [comment]
yes, 0c08883 does fix it.
