### ISSUE TITLE
Unable to display utf-8 unassigned code points in non-standout

### ISSUE THREAD

**Issue by ivbit** [gwsw/less#128]
Hello. I am unable to display utf-8 unassigned code points in non-standout mode.
Putting "*n<U+%04lX>" into LESSUTFBINFMT has no effect. Both "*k" and "*d" work and remove standout, but they make text blink or bold, which is undesirable effect.
I am unable to make text normal and non-standout.

**Comment by gwsw** [comment]
I cannot reproduce this. This displays the character in normal mode for me:
```
perl -e 'printf "%c%c\n", 194, 128' | LESSCHARSET=utf8 LESSUTFBINFMT='*nU+%04lX' less 
```
What version of less are you using?

**Comment by ivbit** [comment]
`perl -e 'printf "%c%c\n", 194, 128' | LESSCHARSET=utf8 LESSUTFBINFMT='*n<U+%04X>' less`
The output on my system (OpenBSD 6.6) is in standout mode.
version is:
`$ less -V`
less (OpenBSD) (POSIX regular expressions)
Copyright (C) 1984-2012 Mark Nudelman
Modified for use with illumos by Garrett D'Amore.
Copyright 2014 Garrett D'Amore

less comes with NO WARRANTY, to the extent permitted by law.
For information about the terms of redistribution,
see the file named README in the less distribution.
Homepage: http://www.greenwoodsoftware.com/less

**Comment by gwsw** [comment]
The -V output indicates that you have a modified version of less, not one of my releases. Can you download less-563 from http://greenwoodsoftware.com/less/download.html and see if it acts the same for you?

**Comment by ivbit** [comment]
I can confirm this problem is **not present** in less-563.
Thank you. I'm closing this issue.
