### ISSUE TITLE
Searching should be able to scroll left or right as well as up and down

### ISSUE THREAD

**Issue by eyalroz** [gwsw/less#129]
If I search for some text or pattern, e.g. using ESC, then `/mypattern`, which is not currently visible in the viewport, less will scroll up or down so that the text will be on the first displayed line (or later if we're near the end).

I believe this should also occur for the columns. That is, when the lines of text are long, and the `mypattern` is not to be seen on the current viewport, `less` should also scroll right or left so that the viewport _does_ contain the pattern - e.g. aligned to its left edge.

This should either be the hard default, or an option.

The matter also relates to using less to render tables. See also issue #43 .

**Comment by gwsw** [comment]
What version of less are you using? This was implemented in d1fe3e1535d69ba47437173ea35b00045d35aea4, and built in v576 and later releases. However no officially announced beta release yet contains this change.

**Comment by eyalroz** [comment]
I'm using less v487, which comes with Devuan GNU/Linux 3 ...
