### ISSUE TITLE
Feature request: add an option to disable "...skipping..."

### ISSUE THREAD

**Issue by elljay23** [gwsw/less#130]
Hi, a suggestion to add an option that disables the "...skipping..." line that appears on screen when filtering a file (using "&" for example) combined with the "F" Scroll Forward command.  Thanks :)

**Comment by gwsw** [comment]
I'm not aware of any circumstance where the skipping message is visible. It's normally only printed between screens and is scrolled off the screen when the screen is finished updating. Can you provide instructions to reproduce this?

**Comment by elljay23** [comment]
Hi, sure - something like this should show it...

```
less /var/log/syslog
&named
<shift-f>
```
gives me this output:

**Mar  4 18:28:21 sam named[13349]: resolver priming query complete
Mar  4 18:29:33 sam named[13349]: resolver priming query complete
Mar  4 18:30:04 sam named[13349]: resolver priming query complete
Mar  4 18:30:13 sam named[13349]: resolver priming query complete
...skipping...
Mar  4 18:31:10 sam named[13349]: resolver priming query complete
...skipping...
Mar  4 18:33:37 sam named[13349]: resolver priming query complete
Waiting for data... (interrupt to abort)**

I guess as long as there are non-matching lines added to the file you're monitoring it outputs "...skipping..." in between each update.

**Comment by gwsw** [comment]
I see. Yes, the skipping message is added when a new line is appended which does not immediately follow the last line currently displayed. This is perhaps not appropriate when & filtering is in effect. I will look into this.

**Comment by gwsw** [comment]
Fixed in 8ef51c5665429a4ce0b7335010669555cf0db487.

**Comment by elljay23** [comment]
Thanks for fixing this! :)
