### ISSUE TITLE
Issues building v578

### ISSUE THREAD

**Issue by eyalroz** [gwsw/less#131]
I've just downloaded v578 (which is currently the latest release).

There are a bunch of issues with building it...

1. The `INSTALL` file says:

   >    The \`configure' shell script attempts to blah blah

  suggesting that you need to run it. But - it doesn't exist. It should be clarified that you need to generate it, before talking about what it's going to do.

2. `INSTALL` then says:

   >    The file \`configure.in' is used to create \`configure' by a program
called `autoconf'

   ... but there is no `configure.in`. There's a `configure.ac`. `autoconf` is right - I guess - but that's another confusing, incorrect distraction.

3. If I `autoconf`, then `./configure --prefix=/opt/less`, on my Devuan GNU/Linux 3 system, I get, at some point:

   ```
   config.status: error: cannot find input file: `defines.h.in'
   ```
   and at that point I'm stuck, because that file doesn't exist. There are four `defines` files - and none of them are for Unix/Linux.

**Comment by gwsw** [comment]
Did you download from greenwoodsoftware.com or from github? If you downloaded from github, you should follow the instructions in README.  INSTALL is a generic set of instructions for autoconf and only applies to complete builds downloaded from greenwoodsoftware.com.

**Comment by eyalroz** [comment]
> Did you download from greenwoodsoftware.com or from github? 

GitHub.

> If you downloaded from github, you should follow the instructions in README.

It is customary for `INSTALL` to contain instructions for (building and) installing. Lacking an `INSTALL`, I would proceed to `README`. ... plus, there's only a `README.VER` file, which I would not imagine holds installation instructions.

>  INSTALL is a generic set of instructions for autoconf and only applies to complete builds downloaded from greenwoodsoftware.com.

Then - either don't include it in the releases on GitHub, or have `INSTALL` say something like:
```
If you have downloaded this from GitHub, please follow the instructions in README.VER
```

---

Having said all this - if I follow the instructions in `README.VER` instead of `INSTALL`, I am told to run: `sh configure`. Unfortunately, a `configure` file does not exist.

**Comment by gwsw** [comment]
Step 3 says to run sh configure. Step 2 says to run "make -f Makefile.aut" first. Did you do that step?

**Comment by gwsw** [comment]
BTW, if you want a ready-to-build version of less-578, you can download it from
https://greenwoodsoftware.com/less/less-578.tar.gz

**Comment by eyalroz** [comment]
> Step 3 says to run sh configure. Step 2 says to run "make -f Makefile.aut" first. Did you do that step?

I did not, because the file says:

> If you are building from a numbered release package ... you should skip this step.

so I skipped it.
