### ISSUE TITLE
Unused variable warnings from mingw

### ISSUE THREAD

**Issue by msoyka-of-wharton** [gwsw/less#133]
As of commit 35f3651c79e4870a3206996537b39c19310c71dc I see the following warnings when building less for Windows:

screen.c:237:12: warning: 'attrcolor' defined but not used [-Wunused-variable]
 static int attrcolor = -1;
            ^~~~~~~~~

optfunc.c:949:7: warning: unused variable 'parg' [-Wunused-variable]
  PARG parg;
       ^~~~

**Comment by gwsw** [comment]
These warnings should be fixed in v580.
