### ISSUE TITLE
Cannot build less with mingw

### ISSUE THREAD

**Issue by msoyka-of-wharton** [gwsw/less#134]
As of commit 35f3651c79e4870a3206996537b39c19310c71dc the mingw linker fails with this message:

gcc -L/mingw-w64/mingw32/opt/lib -o less main.o screen.o brac.o ch.o charset.o c
mdbuf.o command.o cvt.o decode.o edit.o filename.o forwback.o help.o ifile.o inp
ut.o jump.o line.o linenum.o lsystem.o mark.o optfunc.o option.o opttbl.o os.o o
utput.o pattern.o position.o prompt.o search.o signal.o tags.o ttyin.o version.o
 -lregex
optfunc.o:optfunc.c:(.text+0x1187): undefined reference to `ttyin_name'
collect2.exe: error: ld returned 1 exit status
mingw32-make: *** [Makefile.wng:113: less] Error 1

**Comment by gwsw** [comment]
This should be fixed in v580.
