### ISSUE TITLE
SIGTSTP and SIGQUIT should be ignored when LESSSECURE is set

### ISSUE THREAD

**Issue by mjetzer** [gwsw/less#137]
less should ignore SIGTSTP and SIGQUIT when LESSSECURE is set to prevent the user from breaking out of less.

I'm using less from a Perl script which ignores these signals, sets LESSSECURE, and does a fork/exec of less to display a file.  If the user delivers a ctrl-z (SIGTSTP), things hang.  If I modify signal.c to ignore these signals if secure is set, less ignores these signal completely and everything continues to work.

**Comment by gwsw** [comment]
As of e3af3f5f15aee14bffc3afa062d7647ce7f09cc4, SIGTSTP is now ignored when LESSSECURE is set.
SIGQUIT has always been ignored, regardless of the setting of LESSSECURE.
