### ISSUE TITLE
Note of Appreciation

### ISSUE THREAD

**Issue by jftuga** [gwsw/less#138]
Thank you for making `less` a really awesome program.  

I can't imagine how immeasurably more difficult it would be without being able to use your program a hundred times, it not more, each day.  It's indispensable.  In the past few months, I have submitted a few issues and you have always been very attentive, quick to reply and worked to resolve my submissions.  Your program is not overlooked in how critical it is.  Please keep up the phenomenal work.

**Comment by gwsw** [comment]
Thank you very much for the kind words. It's very gratifying to hear this.

**Comment by clin1234** [comment]
Is there any way for someone to donate financially to Greenwoods in order to fund development of less?

**Comment by clin1234** [comment]
Hopefully the owner gets a response: Is there any way for someone to donate financially to Greenwoods in order to fund development of less?

**Comment by gwsw** [comment]
Hi @clin1234, I very much appreciate the thought, but financial donations are not necessary. However you are very welcome to suggest fixes and enhancements here.

**Comment by ches** [comment]
I came to express the same sentiment and also ask the question of donation.

less is probably the single most-used software application in my 15-year IT career (beside maybe the shell I run it in? ☺️). Thank you Mark, for the tool and nearly 30 years of commitment.
