### ISSUE TITLE
Latest less from the repo fails to install

### ISSUE THREAD

**Issue by grgoffe** [gwsw/less#139]
I just downloaded the latest from the repo and did a build.

The build went just fine but when I entered make install I got error messages about less.nrof missing:

make: *** No rule to make target 'less.nro', needed by 'install'.  Stop.

I ran these commands and make install now succeeds:

 cp -irpv less.nro.VER less.nro
 cp -irpv lessecho.nro.VER lessecho.nro
 cp -irpv lesskey.nro.VER lesskey.nro

**Comment by polluks** [comment]
No, this rule is of `Makefile.aut`, see https://github.com/gwsw/less/pull/117/files

**Comment by gwsw** [comment]
Installing a github clone is not recommended; you should use a packaged build from greenwoodsoftware.com. However, if you do want to do this, you should run "make -f Makefile.aut distfiles" first.
