### ISSUE TITLE
less 563 can't pattern match specific line

### ISSUE THREAD

**Issue by CervEdin** [gwsw/less#148]
I've encountered a bug where less is unable to search for patterns in a specific line.

It can be reproduced with the following text

```
x é
y ör 
z
```
when it's HEX encoded in the following way
```
7820 e90d 0a79 20f6 7220 0d0a 7a0d 0a
```
[less-cant-match-y-line.txt](https://github.com/gwsw/less/files/6284589/less-cant-match-y-line.txt)

Using `/y` in less you get `Pattern not found`, and as far as I could tell, it was the same for any pattern on that line in the original output.

The other lines appear to match fine.

I'm not 100% sure of the encoding, the source is output from [tf history](https://docs.microsoft.com/en-us/azure/devops/repos/tfvc/history-command?view=azure-devops) and the underlying database is running `Finnish_Swedish_CI_AS` collation.

Using `chardet` it guesses the encoding as `ISO-8859-1` with `0.73` confidence.

Piping through `iconv` resolves the issue

```
cat less-cant-match-y-line.txt | iconv -f Windows-1252 -t UTF-8 | less
cat less-cant-match-y-line.txt | iconv -f ISO-8859-1 -t UTF-8 | less
```

**Comment by CervEdin** [comment]
I should add that this was running on Git bash for windows

**Comment by polluks** [comment]
v563 and v487 fail in macOS too
v458 works in NetBSD
finding "x" works always...

**Comment by CervEdin** [comment]
yes, `x` and `z` are no problem and afaik any other pattern on those lines, just the `y` line

also I don't believe it's `ISO-8859-1` encoded, possibly `CP-1252`

**Comment by gwsw** [comment]
I cannot reproduce this unless I set my charset to UTF-8 (via LESSCHARSET, LANG, LC_CTYPE or LC_ALL). Since the file is not UTF-8-encoded, telling less to use UTF-8 will result in less misinterpreting the non-ASCII characters.  If I set the charset to windows-1252 or in fact anything except utf-8, it finds the "y" correctly.

**Comment by gwsw** [comment]
Actually, in my testing it seems pcre is the culprit. What regex library are you using? This program demonstrates that pcre rejects the invalid UTF-8 sequence in the second line of your file. If run without arguments it prints -10 (PCRE_ERROR_BADUTF8). If run with an argument of "x", it replaces the \xf6 character with an 'x' and then it prints 1 (pcre match successful).
```
#include <stdio.h>
#include <pcre.h>

int main(int argc, char **argv)
{
	const char *errstring;
	int erroffset;
	int ovector[3];
	int n;
	char line[] = "y \xf6rp";
	pcre *comp = pcre_compile("y", PCRE_UTF8 | PCRE_NO_UTF8_CHECK, &errstring, &erroffset, NULL);
	if (comp == NULL) abort();
	if (argc > 1) line[2] = argv[1][0];
	n = pcre_exec(comp, NULL, line, 5, 0, 0, ovector, 3);
	printf("%d\n", n);
	return 0;
}
```

**Comment by CervEdin** [comment]
> Actually, in my testing it seems pcre is the culprit. What regex library are you using? This program demonstrates that pcre rejects the invalid UTF-8 sequence in the second line of your file. If run without arguments it prints -10 (PCRE_ERROR_BADUTF8). If run with an argument of "x", it replaces the \xf6 character with an 'x' and then it prints 1 (pcre match successful).
> 
> ```
> #include <stdio.h>
> #include <pcre.h>
> 
> int main(int argc, char **argv)
> {
> 	const char *errstring;
> 	int erroffset;
> 	int ovector[3];
> 	int n;
> 	char line[] = "y \xf6rp";
> 	pcre *comp = pcre_compile("y", PCRE_UTF8 | PCRE_NO_UTF8_CHECK, &errstring, &erroffset, NULL);
> 	if (comp == NULL) abort();
> 	if (argc > 1) line[2] = argv[1][0];
> 	n = pcre_exec(comp, NULL, line, 5, 0, 0, ovector, 3);
> 	printf("%d\n", n);
> 	return 0;
> }
> ```

Honestly, I don't know not with which regex library is being used.

I encountered this using Git bash for windows, in a minTTY terminal which is configured to run with UTF-8.

On the same machine running Ubuntu 18.04 with less 487 I don't appear to be able to reproduce the problem.

Happy to provide more information about the environment but I might need some direction, for example, how can I find out which regex library is used?

**Comment by gwsw** [comment]
Just run ```less --version``` and it should tell you the version number and the regex library on the first line of the output.

**Comment by CervEdin** [comment]
> Just run `less --version` and it should tell you the version number and the regex library on the first line of the output.

`less 563 (PCRE regular expressions)`

which I believe was distributed with `Git-2.30.1-64-bit`

the test on Ubuntu was running GNU regex

**Comment by gwsw** [comment]
Ok, so the version that fails for you is also using pcre and the one that works is using gnu regex. This is consistent with my finding that pcre rejects invalid UTF-8 sequences when you have UTF-8 mode enabled. But it's not really a problem with either less or pcre. The bottom line is, if your data is not UTF-8 encoded, you should not be using UTF-8 mode.

**Comment by CervEdin** [comment]
Guessing the utf-8 mode is set by the terminal in this case?

I was mainly surprised this line in particular failed, and that the whole
line failed.

Anyways, I figured out how to circumvent it in this case.

Thanks for the awesome software

**Comment by gwsw** [comment]
>Guessing the utf-8 mode is set by the terminal in this case?

It's coming from an environment variable, one of the 4 I mentioned in my first response. I don't know what is setting that variable in your case though. You can explicitly override it by doing something like (in bash)
```LESSCHARSET=ascii less myfile```
