### ISSUE TITLE
Non-compiled configuration file

### ISSUE THREAD

**Issue by openjck** [gwsw/less#149]
I'd like to request that less support a non-compiled configuration file. There are a couple of configuration options I'd like to set, for example, [configuring search to wrap](https://unix.stackexchange.com/a/621514/410447), but I know I'm eventually going to make a change, forget to run `lesskey`, and become confused.

If you do this, I'd recommend supporting XDG configuration file locations, e.g. *$HOME/.config/lessrc*.

**Comment by gwsw** [comment]
Thanks for this suggestion. Lesskey was originally made a separate program to minimize the code size in less, back when memory was a much scarcer resource than it is today. The size of the parsing code is fairly trivial by today's standards, so this is probably a good idea.

**Comment by gwsw** [comment]
Addressed in 5bc78d59ce9050938af6492f5a3bc8178c67f425.
For compatibility, the configuration file remains $HOME/.lesskey etc.
