### ISSUE TITLE
Results of the static analysis tool FB Infer on source files

### ISSUE THREAD

**Issue by TomasBeranek** [gwsw/less#151]
As a part of my Bachelor's thesis, I have been analyzing packages on Fedora with a static analysis tool called Facebook Infer. When analyzing package less-551-4.fc33 Infer produced some interesting errors. I have checked them against this repository and it seems, that they are still present. I will summarize them into a single issue:

lesskey.c:126: error: Null Dereference
  pointer `pathname` last assigned on line 125 could be null and is
  dereferenced by call to `strcpy()` at line 126.

lesskey.c:289: error: Null Dereference
  pointer `env` last assigned on line 287 could be null and is
  dereferenced by call to `strcpy()` at line 289.

ch.c:857: error: Null Dereference
  pointer `thisfile` last assigned on line 855 could be null and is
  dereferenced at line 857.

filename.c:285: error: Null Dereference
  pointer `pathname` last assigned on line 273 could be null and is
  dereferenced at line 285.

**Comment by gwsw** [comment]
Fixed in df6e714f3f92c757cdc9e69383cc56d4ba52c5bd.
