### ISSUE TITLE
less v581 with pcre2, --pattern='\$' does not work?

### ISSUE THREAD

**Issue by mario-grgic** [gwsw/less#154]
I have less v581 compiled `--with-regex=pcre2`. When I search a file interactively by typing `/\$` to find all instances of literal `$` in the file, it works just fine.

However, if I try to invoke less from BASH v5.1.4 either like:

```
less --pattern='\$' my_file
```

or

```
less +'/\$' my_file
```

it complains with message:

```
\ at the end of pattern (press RETURN)
```

If I inspect the actual pattern by typing `/ up arrow` to see the previous pattern, it only displays `\` as actual pattern. Somehow `$` has been eaten along the way.

Not sure what is causing this. I tried passing `\\$`,` \\\$`, `\$$$$$` and in any case all `$` get eaten.

**Comment by mario-grgic** [comment]
Note however that:

```
pcre2grep '\$' my_file
```

works correctly.

**Comment by mario-grgic** [comment]
Even when using `--use-backslash` option, this still does not work correctly. I have a shell script with a line:

```sh
if [[ $var -eq 1 ]]
then
     echo "$var
fi
```

Specifying pattern like this:

```
less +x'/if \[\[ \$var' my_file
```
complains about \ at the end of pattern.

If I use:

```
less --use-backslash +x'/if \[\[ \$var' my_file
```
I get: `missing terminating ] for character class` instead. No other tool compiled against PCRE2 behaves like this (pcre2grep, git, etc).

**Comment by gwsw** [comment]
You need to specify the --use-backslash option so that you can escape the $ to include it in the string. But with --use-backslash, you also need to escape any backslashes in your string. You have three backslashes to escape, plus the $ to escape, so your command should look like this
```
less --use-backslash +x'/if \\[\\[ \\\$var' my_file
```
Also the "x" at the beginning of the + command seems unnecessary.

**Comment by mario-grgic** [comment]
@gwsw Thank you for the clarification. I figured out eventually that is the form I am supposed to type by adding some debug print statements in the source code and printing the actual pattern being passed to PCRE2 library. 

However, this is very much unlike majority of tools out there. If you single quote pattern on the command line, single backspace is enough for tools like grep, pcre2grep etc. The form with triple backspaces is something you encounter in programming language source code regexes.
