### ISSUE TITLE
cannot build less v583 using mingw (Windows)

### ISSUE THREAD

**Issue by msoyka-of-wharton** [gwsw/less#156]
When building less.exe using mingw I get the following linker error:

    decode.o:decode.c:(.text+0x790): undefined reference to `parse_lesskey'

The function parse_lesskey is defined in lesskey_parse.c but that file is not listed as a dependency in the makefile.

**Comment by gwsw** [comment]
Should be fixed in 0ead0254d622ed744ee6fbf69f87fabcf2b44a0f.
