### ISSUE TITLE
regerror()

### ISSUE THREAD

**Issue by polluks** [gwsw/less#158]
What about this function for "no regular expressions"? At least it's not defined in search.c.

**Comment by gwsw** [comment]
Sorry, I'm not understanding the question. regerror is used only by the Spencer regex code included with less (in regexp.c) This is only compiled in if configured with --with-regex=regcomp-local. regerror() is not used if any other regex library is used, or if no regex library is used (--with-regex=none).

**Comment by polluks** [comment]
I see, I mixed them up.
