### ISSUE TITLE
Is ‘--mouse’ working properly?

### ISSUE THREAD

**Issue by larrypl** [gwsw/less#159]
With less 583, with either LESS including ‘--mouse’ or typing ‘--mouse’ in less, the scrolling works, but typing in ‘--mouse’ (again, if typed in less previously), less still scrolls, and copy/pasting doesn't work (is ignored), but ‘__mouse’ says “ignore mouse input”. Also quitting less leaves xterm (e.g.) in a state where mouse movements (e.g., to scroll back in xterm history) produces unrecognized escape sequences (e.g., “64;41;21M” with scroll up). The ‘reset’ command repairs the xterm terminal.

In other terminal emulators similar, although not exactly identical, results occur. (Some terminal emulators seem to have mouse scrolling built-in, but the copy/pasting is still ignored on second and subsequent ‘--mouse’ toggles.)

**Comment by gwsw** [comment]
Thanks, this was indeed malfunctioning. Should be fixed in 21e0892eb4a0d0a7cffdfc1eee15972dc5691fdd.

**Comment by gwsw** [comment]
Note issue has existed since v572.

**Comment by larrypl** [comment]
Thanks!

**Comment by gwsw** [comment]
Note fix has been applied to v581 in the v581rel branch and released in less-581.2.
