### ISSUE TITLE
Highlight current line

### ISSUE THREAD

**Issue by ravenpi** [gwsw/less#160]
I'm an admin, and often have to go through SOP checklists of instructions on how to do a given task.  It would be really handy if I could highlight line-at-a-time as I scroll through the file so that I don't lose my place.  Maybe I'm missing a way to do this, but I've read through the manpage twice, as well as done some googling, and if it's in there, I'm missing it.  Finally wrote my own version in Ruby, but boy, I'd love to have it in less.

**Comment by gwsw** [comment]
If I'm understanding your request, one option would be to enable the status column (-J) and the mouse (--mouse). You can then click on a line with the mouse to add a mark in the status column.

**Comment by ryenus** [comment]
I too, would like to see this feature. 

Using `-J` and `--mouse` works, but the status column takes extra screen space, especially when line numbers are also displayed.

**Comment by gwsw** [comment]
Line numbers are going to take screen space if enabled, regardless of whether the status column is displayed. The status column does use one column (if you use --status-col-width=1). Is that really a serious impediment? It seems to me that you can make your window one column wider if you really need to.

**Comment by ryenus** [comment]
What about something like cursorline in vim? It's much easier to see the current line if underlined. Another way might be highlight the current line using a different background color.

**Comment by gwsw** [comment]
Added the --status-line option in 465a0b3549a7ccf59f4cb3255d021ad59d52ffe1 to address this.

**Comment by gwsw** [comment]
Fix is available in less-593.
