### ISSUE TITLE
quit-if-one-screen aka F works bad with +Gg

### ISSUE THREAD

**Issue by vatosarmat** [gwsw/less#161]
It is pretty common practice to have `+Gg` in `LESS` to have browsed file size and scroll percentage in the verbose prompt. Unfortunately it works bad with one-screen input and `F` flag: screen getting flooed with tildas
![less_tildas](https://user-images.githubusercontent.com/35213999/116560316-9a81cc00-a944-11eb-81f5-05c9a022e1a7.png)

**Comment by gwsw** [comment]
The new option --file-size added in a4caa7843e0f34166131931c5ccb0c2e82b76aff can be used instead of +Gg.

**Comment by gwsw** [comment]
Fix available in v586.
