### ISSUE TITLE
Can't set multiple --color options in LESS variable

### ISSUE THREAD

**Issue by tardypad** [gwsw/less#162]
Using version 581.2 on Arch Linux.

Here's how to reproduce the issue.

I don't have any LESS variable defined in my shell, and I removed my `~/.less` file as well.

Single --color option, everything is fine
```shell
> echo '\xc' | less --use-color -DCr -FN
      1 ^L # Only ^L is red
> echo '\xc' | LESS='--use-color -DCr' less -FN
      1 ^L # Only ^L is red same as before
```

Two --color options, only the first command works as expected
```shell
> echo '\xc' | less --use-color -DCr -DNr -FN
      1 ^L # everything is red
> echo '\xc' | LESS='--use-color -DCr -DNr' less -FN
Invalid color string "r -DNr"
Press RETURN to continue
      1 ^L # same colors as default --use-color
```

There's the same issue whether using `-D` or `--color`

And I'm also seeing some weirder things with some combo, no error is returned but the result is not correct
```shell
> echo '\xc' | less --use-color -DCrw -DNrw -FN
      1 ^L # everything is red
> echo '\xc' | LESS='--use-color -DCrw -DNrw' less -FN
      1 ^L # The ^L is red but not the line number
```

**Comment by gwsw** [comment]
You need to use a dollar sign to terminate the string following the -D option. The man page states:

> Some options like -k or -D require a string to follow the option  let-
>        ter.   The  string  for that option is considered to end when a dollar
>        sign ($) is found.  For example, you can set two -D options on  MS-DOS
>        like this:
> 
>        LESS="Dn9.1$Ds4.1"

You can also use ```LESS="-DCr$ -DNr"```, closer to what you were trying.

**Comment by tardypad** [comment]
Damn I missed that indeed. I was grepping for "color" only.
Everything looks good then now :)
Thanks a lot for that speedy reply.
