### ISSUE TITLE
Can't set W color

### ISSUE THREAD

**Issue by tardypad** [gwsw/less#163]
Using less version 581.2 on Arch Linux.

I don't have any LESS variable defined in my shell, and I removed my ~/.less file as well.

Per man page:
```
W      The highlight enabled via the -w option.
```

However in usage:
```
> echo hello | less --use-color -DWr$ -F
Invalid color specifier 'W'
Press RETURN to continue
hello
```

Hope I didn't miss anything this time :)

**Comment by gwsw** [comment]
Thanks, this is indeed a disconnect between the code and the man page. The code is currently using A rather than W as the descriptor for the -w highlight. In 058448f7970e29bb9635bf0b667289eadab2717f I have changed the code to accept W as well as A, to match the man page.

**Comment by gwsw** [comment]
Fix available in v586.
