### ISSUE TITLE
Incorrect behavior when resizing terminal window

### ISSUE THREAD

**Issue by mbenford** [gwsw/less#165]
After upgrading less to version 581.2 I noticed that it has stopped rendering text correctly after a window resize. The following GIFs illustrate what I mean:

Before window resize
![less-1](https://user-images.githubusercontent.com/446867/118009031-0f310f00-b324-11eb-91de-e0d17950e635.gif)

After window resize
![less-2](https://user-images.githubusercontent.com/446867/118009089-2243df00-b324-11eb-8f2d-4e77cd421641.gif)

It looks like less only sees with the original window height. I have downgraded it to version [563](https://archive.archlinux.org/packages/l/less/less-1%3A563-1-x86_64.pkg.tar.zst) and the issue no longer happens.

**Comment by gwsw** [comment]
This is fixed in less-586 (first fixed in 0e822fc9f2796fe27269edcf19f534afee9d4a06). I will soon release this version as a beta.

**Comment by mbenford** [comment]
Thanks for replying.

Should I keep this issue open until the next release is out? I didn't find another one related to the same problem.

**Comment by gwsw** [comment]
You can leave this issue open for now.
