### ISSUE TITLE
latest stable release is missing from gnu server

### ISSUE THREAD

**Issue by xosevp** [gwsw/less#167]
https://ftp.gnu.org/gnu/less/

Thanks.

**Comment by gwsw** [comment]
Uploaded 15 May 2021.

**Comment by xosevp** [comment]
590 is also missing.

**Comment by gwsw** [comment]
590 is uploaded now.

**Comment by xosevp** [comment]
608 is missing.
Thanks.

**Comment by gwsw** [comment]
less-608 is now uploaded to gnu.

**Comment by xosevp** [comment]
632 and 633 are is missing.
Thank you.

**Comment by gwsw** [comment]
Well I tried to upload less-633 but something seems to have gone wrong. It's not showing up on https://directory.fsf.org/wiki/Less, and if I try to upload it again I get
```
ftp> put less-633.tar.gz
200 EPRT command successful. Consider using EPSV.
553 Could not create file.
```
I'll try again in a couple of days.

**Comment by gwsw** [comment]
less-633 has been uploaded to the gnu server.
