### ISSUE TITLE
less --file-size (Windows)

### ISSUE THREAD

**Issue by adoxa** [gwsw/less#168]
`less --file-size FILE` leaves behind the length message.

```
C:\Projects\less>less --file-size less.man
Determining length of file... (interrupt to abort)
C:\Projects\less>
```

I tried adding `ierror("", NULL_PARG)`, but that still leaves the abort part. Could just use `clear_bot()`, but that leaves `need_clr` set (not that it matters too much, I guess).

**Comment by gwsw** [comment]
I'm confused -- on Linux at least, ierror sets need_clr which causes putchr to call clear_bot. The clear_bot erases the Determining message. I would expect this all to work the same on Windows, so I don't understand why you are seeing the message. If I run with termcap debug on I see
```
$ echo hello | LESS_TERMCAP_DEBUG=1 less --file-size 
<cr><cd><so>Determining length of file... (interrupt to abort)<se><cr><cd><ti><ks><cr>hello
<so>(END)<se><ce>
```
The "<cr><cd>" after the message represents a call to clear_bot.

**Comment by adoxa** [comment]
Don't compare Windows & Linux. ;)  It would seem this message (and the "binary" one) are displayed before the console switches screens. I don't think that can be done earlier because of `-F` (but even so it probably wouldn't be right for the "binary" one).

**Comment by gwsw** [comment]
Yes, the Determining message is displayed before switching screens, but the clear_bot should also happen before switching screens. Ah, perhaps the difference is Linux uses putchr to send the init ("ti") sequence, which invokes clear_bot, but Windows doesn't call putchr anywhere in init(). Maybe the need_clr/clear_bot check that's in putchr should be done explicitly at the start of init().

**Comment by gwsw** [comment]
Let me know if 81c1184064d90a10b7757db4d8bc0198d6f4b9ba fixes this in Windows.

**Comment by adoxa** [comment]
Yep, that got it, thanks.
