### ISSUE TITLE
Latest pull from repo produces error with "--with-secure" parameter in configure script

### ISSUE THREAD

**Issue by grgoffe** [gwsw/less#171]
Hody,

Less builds successfully without "--with-secure" present. With "--with-secure" present the following messages are displayed:

gcc -I. -c -DBINDIR=\"/usr/lsd/Linux/bin\" -DSYSDIR=\"/usr/lsd/Linux/etc\"  -g -O2 version.c
gcc  -o less main.o screen.o brac.o ch.o charset.o cmdbuf.o command.o cvt.o decode.o edit.o filename.o forwback.o help.o ifile.o input.o jump.o lesskey_parse.o line.o linenum.o lsystem.o mark.o optfunc.o option.o opttbl.o os.o output.o pattern.o position.o prompt.o search.o signal.o tags.o ttyin.o version.o   -ltinfo
/export/home/lsd/Linux/bin/../lib/gcc/x86_64-pc-linux-gnu/12.0.0/../../../../x86_64-pc-linux-gnu/bin/ld: /export/home/lsd/Linux/bin/../lib/gcc/x86_64-pc-linux-gnu/12.0.0/../../../../x86_64-pc-linux-gnu/bin/ld: DWARF error: can't find .debug_ranges section.
lesskey_parse.o: in function `parse_error':
lesskey_parse.c:(.text+0xac): undefined reference to `lesskey_parse_error'
/export/home/lsd/Linux/bin/../lib/gcc/x86_64-pc-linux-gnu/12.0.0/../../../../x86_64-pc-linux-gnu/bin/ld: lesskey_parse.o: in function `parse_lesskey':
lesskey_parse.c:(.text+0x83a): undefined reference to `lesskey_parse_error'
collect2: error: ld returned 1 exit status
make: *** [Makefile:58: less] Error 1

**Comment by gwsw** [comment]
Fixed in 95f209262ca4e767465e2587ee41e53ae67f010f
