### ISSUE TITLE
Less builds successfully but does not find --with-editor=vi 

### ISSUE THREAD

**Issue by grgoffe** [gwsw/less#174]
From the latest repo pull. building with --editor=vi or --editor=/usr/bin/vi, less produces an error message: "Command unavailable".

This system is Fedora Core 35 (rawhide).

**Comment by grgoffe** [comment]
This happens even leaving the "--with-editor=" excluded from the "configure" args.

**Comment by gwsw** [comment]
I cannot reproduce this. Did you configure with --with-secure? The editor command is not available in secure mode.

**Comment by grgoffe** [comment]
gwsw,

Ah... Yes I used --with-secure.

Sorry to bother you.

Best regards and STAY SAFE!

George...
