### ISSUE TITLE
Color is incorrectly cleared with --use-color

### ISSUE THREAD

**Issue by felipec** [gwsw/less#175]
When viewing text with color (e.g. `git diff`) and doing a search, the search is colored in green and the rest of the line will not be colored any more.

You can try this:

```sh
echo "\e[33mSearch here, and the rest will be cleared\e[m" | less -R --use-color
```

The fg color should not be cleared by the search.

**Comment by gwsw** [comment]
Fixed in 3b0a03c6d115793523b43257cc93dab726deb1d3
Available in less-588.
