### ISSUE TITLE
less with -F flag exits if terminal window is resized to a size that fits the contents of the file

### ISSUE THREAD

**Issue by agsimmons** [gwsw/less#176]
This was originally reported to sharkdp/bat#1575 but this behavior was determined to be caused by less itself.

less version: 581.2

When viewing a file that does not fit entirely on screen with less using the -F flag, less remains open and allows you to page through the file. Upon resizing the terminal to a size that can fit the entire file, less exits and the contents of the file disappears. This behavior is the same across terminal applications (Konsole and Alacritty were tested).

It makes sense why this happens as the -F flag "Causes less to automatically exit if the entire file can be displayed on the first screen.", but this behavior does not seem to be correct as this causes the file's contents to disappear, which is unlike when the flag is used on a file that can be displayed entirely on the first screen.

The behavior I would expect is that the check to determine if a file fits entirely on the first screen occurs once upon opening the file rather than every time the dimensions of the terminal change. If in windowed mode and opening a file that does not fit on the first screen, the user were to resize their terminal window to a size that does fit the entire file on the first screen, then less should remain open as the "does file fit on page" check should only have occurred once upon opening the file.

Thank you!

https://user-images.githubusercontent.com/4230365/119568779-df4e2680-bd7b-11eb-9898-60b9a9f7362d.mp4

**Comment by gwsw** [comment]
Fixed in 129b5a1866a5a81492ac86238029fe6037695728.
Available in less-588.
