### ISSUE TITLE
[feature-request] start counting line numbers from n-th line

### ISSUE THREAD

**Issue by ryenus** [gwsw/less#178]
When less is used to navigate tabular data which include one or more lines at the top with column headers, can we have less to skip the header lines? So that the header lines won't have line numbers displayed, the line `1` would be for the line followed.

Maybe a new option `--header-lines` or `-H` can be introduced, which specifies the number of header lines to skip.

**Comment by gwsw** [comment]
#43 is a much more ambitious request, to not scroll the header lines at all. But here you just asking that the line numbers be modified to skip the header line? That would be pretty easy but I kind of feel it should perhaps be bundled with #43. Or do you think these are orthogonal features that should be selectable separately?

**Comment by ryenus** [comment]
Thanks and #43 looks interesting! It definitely makes sense to be able to also pin the header lines when scrolling. 
So my vote goes to having these features converged, with the line numbers only map to the scrollable lines.
