### ISSUE TITLE
RTL text handling?

### ISSUE THREAD

**Issue by clin1234** [gwsw/less#183]
How well is RTL text handled (eg. Hebrew and Arabic)?

Also, can less handle top to down text, such as the traditional Mongolian script?

**Comment by gwsw** [comment]
I have made no attempt to support RTL or vertical text, nor have I tested them. If it works at all, it is completely fortuitous.

**Comment by polluks** [comment]
> Also, can less handle top to down text, such as the traditional Mongolian script?

Which console app supports TTD at all? My suggestion would be use a filter program.
