### ISSUE TITLE
Less does not clear the contents of the original file in memory, and appends the new contents of the file instead after refreshing file of size 0

### ISSUE THREAD

**Issue by 4D617278** [gwsw/less#189]
less sometimes does not clear the contents of the original file in memory, and appends the new contents of the file instead starting from version 581.2. Any ideas on how to debug or what the problem is?

**Comment by gwsw** [comment]
Can you explain in a little more detail what you're seeing? I think you're saying that if you invoke less with two filename arguments (eg. ```less file1 file2```), when you enter the ```:n``` command to view the second file, you sometimes see the second file concatenated onto the end of the first file. Is that correct? And it is not repeatable in the sense that if you repeat with the same two files and the exact same keystrokes it may not happen again? Does this happen only when you have moved all the way to the end of the first file, or does it happen if you enter ```:n``` before reaching the end of the first file?

**Comment by 4D617278** [comment]
The bug occurs when less is invoked with multiple filename arguments file1 file2 and a command is executed like !echo 'garbage' > file2 when file2 already has been viewed and while less is on file1 when you use the ```:n``` command to view the second file, the string garbage is appended to the original contents of the second file as opposed to just having the string garbage without the original contents of the file.

**Comment by 4D617278** [comment]
I figured it out, the bug is caused when you refresh a file of size 0 which results in the CH_CANSEEK flag being turned off because of commit 512feb19. This results in any further file reads to be appended to the current content of the file

**Comment by polluks** [comment]
Maybe you can check if it's a procfs access?

**Comment by gwsw** [comment]
Hm, I'm not sure of a good way to determine if a file is a procfs. Maybe ```major(st_rdev) == 0```? I don't know how portable that is.

**Comment by polluks** [comment]
How about this? https://unix.stackexchange.com/a/16170/277889

**Comment by 4D617278** [comment]
Non procfs files return 0 when running major(st_rdev) for me on Gentoo

**Comment by 4D617278** [comment]
Never mind, I think you mean st_dev rather than st_rdev

**Comment by 4D617278** [comment]
What about statfs, then checking if f_type is PROC_SUPER_MAGIC? Is that portable? major(st_dev) is 0 for a tmpfs, which is where I'm using less

**Comment by gwsw** [comment]
Could you give a step by step method to reproduce this? I've tried various combinations of viewing two files, adding content to one, refreshing, having one or both of the files be empty, etc. but I haven't reproduced any problem. 

I've attempted to implement this in the statfs branch, but I don't know how to test it.

**Comment by 4D617278** [comment]
$ rm -rf /tmp/test
$ touch /tmp/test
$ less /tmp/test
Press r
Type `!echo a > %` in less
Press enter
Type `!echo b > %` in less
If the bug is present is should display 
a
b
otherwise, it should display
b

**Comment by gwsw** [comment]
This should be fixed in less-593.
