### ISSUE TITLE
Missing left few characters in prompts containing ANSI escape sequences or Unicode code points

### ISSUE THREAD

**Issue by 0xTadash1** [gwsw/less#190]
I love less and I want to make the prompt eyecandy, so I did the following.

```shell
$ ph='\033[;96;40m \uf7d5 HELP \033[;30;45m\ue0b8 \uf42a  q to quit \033[;35;106m\ue0b8 \033[;30;106m\uf0dc j/k to scroll \033[;96m\ue0b8 \033[m '
```

![image](https://user-images.githubusercontent.com/56265995/127996869-ee7f9c2c-ddd3-47ab-8700-26e489251938.png)

This sometimes works.
**But, when the terminal window is somewhat narrower, the first few characters of the prompt are missing.**

```shell
$ LESS= less --help -Ph"$(echo $ph)"
```

![image](https://user-images.githubusercontent.com/56265995/127997026-92cc02fb-920c-4a77-9cdf-7953e7874348.png)

### No Unicode code points (Nerd Fonts)

```shell
$ ph_nonf='\033[;96;40m  HELP \033[;30;45m  q to quit \033[;35;106m \033[;30;106m j/k to scroll \033[;96m \033[m '
```

![image](https://user-images.githubusercontent.com/56265995/127999363-b19798d9-572a-488a-a89e-2b57b50dba59.png)

```shell
$ LESS= less --help -Ph"$(echo $ph_nonf)"
```

![image](https://user-images.githubusercontent.com/56265995/127999495-7eba1706-2d42-423f-92e2-2884c8c939a4.png)

### No ANSI escape sequences

```shell
$ ph_noansi=' \uf7d5 HELP \ue0b8 \uf42a  q to quit \ue0b8 \uf0dc j/k to scroll \ue0b8 '
```

![image](https://user-images.githubusercontent.com/56265995/128003070-8eeaa735-f8c7-45f5-8f26-6c3366321ab6.png)

```shell
$ LESS= less --help -Ph"$(echo $ph_noansi)"
```

![image](https://user-images.githubusercontent.com/56265995/128003269-cd1f6afe-0dd5-48d5-a467-906ae65f1305.png)

So far, I don't know how to make it display correctly except to give enough window width. 

---

CPU: Intel i7-1185G7
OS: Manjaro Linux
Terminal: (at least) Konsole, Kitty, and VSCode's integrated terminal
Shell: zsh 5.8
less: less 590 (PCRE2 regular expressions)

**Comment by gwsw** [comment]
This should be fixed in 2cdb98461a4e7ccc0732c85cacbe84e2da1eb4d7, available in v591.
