### ISSUE TITLE
How to configure `less` so that search hits are in the middle line of the screen

### ISSUE THREAD

**Issue by zachriggle** [gwsw/less#192]
Hello!  Sorry for what seems to be a newbie question, but I currently searching with `less` puts the first match on the top line.

Is there any way to configure `less` such that the matches are centered in the window (i.e. the middle line will contain the match)?

This is useful so that you can more easily see the lines around the match and not have to page back up.

**Comment by gwsw** [comment]
See the description of the -j option in the man page. To put the target line in the middle of the screen you could use ```-j.5```.

**Comment by zachriggle** [comment]
‼️

I think I tried this before, but must've done something wrong or specified `0.5` instead of `.5` (or something similarly close-but-not-quite-correct).

Thanks!
