### ISSUE TITLE
Better support for multiple search terms

### ISSUE THREAD

**Issue by didib** [gwsw/less#196]
Hi Mark,

First, I'd like to say thanks. I've been using less since 1993 or so, and it's definitely one of the most important tools for me, used tens or hundreds of times a day. I actually find it quite amazing that you didn't loose interest after all these years. So, Thanks!

I've been thinking about this for quite some time now, but still do not have my thoughts clear. But now had another case where I wanted this feature, so decided it's a good time to create this "issue", as github calls it.

`less` already supports multiple search terms indirectly, by supporting "extended regexp" and the terms split with '|'. But AFAICT based on the manpage, the support is "implicit" - if the regexp library has it, you get it. That's fine, but I want more. specifically, at least two features, but perhaps others might make sense if/when work on this is started:

1. Highlight different terms with different colors. Not much to say about this, I think it's obvious why it might be useful, and is probably not that hard to implement, if you agree to have slightly more reg-exp-library-specific code.

2. Have a quick and simple way to jump to the next occurrence of a specific term. I still did not manage to come up with a good UI for this, as `less` already uses many/most keys/shortcuts and having to type long commands won't be "quick and simple", IMO. It might even make sense to introduce a new mode for searching, in which keys change their meaning - then, it can be useful to be able to type e.g. a single number or letter - e.g. pressing '3' or 'c' will jump to the next occurrence of the third term. Using a letter will also allow naturally to press 'C' for jumping to the previous occurrence. Alternatively, perhaps some new command (instead of a mode) can tell `less` what term number should 'n'/'N' jump to. That's less comfortable in some cases, probably, but requires a simpler and more natural change in the code/behavior, I guess. Why would this be useful? More and more, I find myself looking at some complex log file, having information about lots of different actions/tasks/items going on, and needing to search for both item-specific data (such as its ID/Name), often more than one (think a host name, a file name, etc.), and for more general terms (such as action names/IDs). I often want to see (highlight) all of them, but jump (n/N) to occurrences of a specific item (or items) - e.g. to the next occurrence of a host or file name but not the next one of a task name.

Best regards and thanks again!

**Comment by gwsw** [comment]
Although this doesn't address the second issue, as of b033a6fd92acf54ddaf1ae5e4df44adde5fc449e (less-620), you can get multiple color highlighting by using parenthesized subpatterns in your search pattern (only with posix and pcre regex libraries). Having multiple search terms active at the same time as you suggest would be substantially more difficult.

**Comment by piotr-dobrogost** [comment]
> I find myself looking at some complex log file (…)

Have you tried [lnav](https://github.com/tstack/lnav) for this?

**Comment by didib** [comment]
> Although this doesn't address the second issue, as of [b033a6f](https://github.com/gwsw/less/commit/b033a6fd92acf54ddaf1ae5e4df44adde5fc449e) (less-620), you can get multiple color highlighting by using parenthesized subpatterns in your search pattern (only with posix and pcre regex libraries).

Thanks, sounds useful!

> Having multiple search terms active at the same time as you suggest would be substantially more difficult.

OK. How about having a new variable/param - not sure how to call it, e.g. --search-subpattern-target=PATTNUM - defaulting to 0 (search for the entire pattern), where if it's set to some other number, pressing n/N will jump to the next occurrence of the respective subpattern?

**Comment by didib** [comment]
> > I find myself looking at some complex log file (…)
> 
> Have you tried [lnav](https://github.com/tstack/lnav) for this?

Not yet. I might do soon - thanks. I realize there are specialized tools for such tasks, but IMO it's also useful to know that in a few years, once the changes done here propagate to the common distros, you'll have this available on more-or-less every server you happen to have to diagnose, right there - as `less` is everywhere :-).

**Comment by gwsw** [comment]
@didib, by definition every subpattern is part of every string that matches the search pattern. So pressing "n" will already jump to the next occurrence of every subpattern. Perhaps I'm not understanding correctly what you mean?

**Comment by ferdnyc** [comment]
> @didib, by definition every subpattern is part of every string that matches the search pattern.

That's not _quite_ accurate, technically.

If I have a pattern like `/((Red)|(Blue))/`, then for every occurrence of `Red`, groups 1 and 2 will have matched 'Red', whereas group 3 will not have participated in the match. For every occurrence of `Blue`, groups 1 and 3 will have matched 'Blue', whereas group 2 will not have participated in the match.

I'm not saying that it's possible to build a good/comfortable UI for _interacting_ with that kind of sub-submatch. (In fact, I'll go in the opposite direction entirely: I think it's _highly unlikely_ that simultaneous navigation of multiple sets of search matches can be represented in a sufficiently-comprehensible UI, where I define 'sufficiently-comprehensible' as "makes more sense than using `vim`". But I'd welcome being proved wrong.) But, technically not all (sub-)subgroups are included in all matches.

**Comment by didib** [comment]
> @didib, by definition every subpattern is part of every string that matches the search pattern. So pressing "n" will already jump to the next occurrence of every subpattern. Perhaps I'm not understanding correctly what you mean?

I admit I didn't think this out clearly. How about: Jump to the next line matching the pattern where the matching for group PATTNUM is not empty.

I think this is also a natural extension of less's behavior to say 'Pattern not found' when searching for the empty string (and not matching all lines, like e.g. grep does).

**Comment by gwsw** [comment]
In ac3ec3acc0ad312c8db224ab6a6b791d4596d760 there is a new ctrl-S search modifier, which lets you specify one or more subpatterns which must be nonempty in a valid match.

**Comment by buzain** [comment]
> In [ac3ec3a](https://github.com/gwsw/less/commit/ac3ec3acc0ad312c8db224ab6a6b791d4596d760) there is a new ctrl-S search modifier, which lets you specify one or more subpatterns which must be nonempty in a valid match.

Is there an example/tutorial on how to use ctrl-S?

**Comment by gwsw** [comment]
An example was added to the man page in 69a7a49b5d99ef2b6c6264096beb9c8e4bf5c709.
