### ISSUE TITLE
When compiled with PCRE2, `less -i` ignores `(?-i)` in regex

### ISSUE THREAD

**Issue by danielyli** [gwsw/less#197]
### Reproduction steps:

0. Prerequisite: `less --version` must show `less 590 (PCRE2 regular expressions)`.
1. Run `less -i <<< Xx`
2. Search: `(?-i)x`

### Expected result:

Only the lowercase `x` should be matched.

### Actual result:

Both `X` and `x` are matched.

**Comment by gwsw** [comment]
Fixed in bc4525fab7b12db0a10a943e7ac959f966e3219e, but only when using -I.

**Comment by gwsw** [comment]
Fixed in c9f2a293fa61c88ee676aa8f521eab198d7c4faf.
