### ISSUE TITLE
Code in function "create_flash" is never instantiated

### ISSUE THREAD

**Issue by msoyka-of-wharton** [gwsw/less#2]
In file screen.c, lines 1928-1989, the function "create_flash" is enclosed in the if-block:
  #if MSDOS_COMPILER==MSOFTC || MSDOS_COMPILER==BORLANDC
  #endif
This makes sense because the function is referenced only by code instantiated by those two conditions.  

However, within the function definition, lines 1974-1984, there is this if-block:
  #if MSDOS_COMPILER==WIN32C
  #endif
which will never be instantiated.

It would appear that the second if-block and its code can be deleted.

**Comment by gwsw** [comment]
Fixed in v536.
