### ISSUE TITLE
`noaction 1key` disrupts normal `key` behavior

### ISSUE THREAD

**Issue by bew** [gwsw/less#205]
Hello,

I'm not sure how to summarize this simply for the issue title..

In my lesskey file I have:
```
#command

# Use HJKL to move around by half-a-page
# [...]
H left-scroll
L right-scroll

# Use hjkl to move around 1-by-1 (char/line)
# [...]
h noaction 1H
l noaction 1L
```
I'm using the `LESSKEYIN` env var pointing to the file (but it shouldn't make any difference).

#### Repro steps

1. Open less
2. Try H and L => moves by half a page left and right :heavy_check_mark: 
3. Try h and l => moves one column at a time left and right :heavy_check_mark: 
4. Try again H and L => moves by one column **instead of half a page** :x: :cry: 

#### System info

OS: Arch
Installed with: pacman and Nix
`less` version info: `less 590 (POSIX regular expressions)`

**Comment by gwsw** [comment]
If I'm understanding correctly, this is behaving as designed. Prefixing a scroll command with a number (as in your 'h' command) makes that number be the default for any future scroll command which are not prefixed with a number (as in your 'H' command).

You could do something like this
```
L noaction 40\e)
H noaction 40\e(
l noaction 1\e)
h noaction 1\e(
```
but that would only be exactly a half page if your terminal width is 80. Unfortunately there's no easy way to specify "half a page" as a parameter to the command.

**Comment by bew** [comment]
Oh that would explain it!

Though, using `\e(` or `\e)` in the mapping (or `\kl` / `\kr` which are bound to the same actions) always gives me a message like `No bracket in top/bottom line`.
Interestingly, the following mapping seems to go recursively, doing the l/h mapping again and again:
```
l noaction 1\kl
h noaction 1\kr
```
Maybe an issue with the `key` in the parsing of `noaction 1key` ? or something?

Anyway your solution does work when I use a third mapping bound to `{left,right}-scroll` actions, so that's good :+1:

**Comment by gwsw** [comment]
Ah right, you can't use \e or \k in the action string. You can use backslash followed by an octal number, so this should work
```
h noaction 1\033(
l noaction 1\033)
H noaction 40\033(
L noaction 40\033)
```

**Comment by bew** [comment]
> h noaction 1\033(
> l noaction 1\033)
> H noaction 40\033(
> L noaction 40\033)

This gives the same error message as with `\e(` or `kl` unfortunately.

**Comment by gwsw** [comment]
I'm not seeing that problem with less-590. Are you sure you've put these lines into your .lesskey file correctly, that you don't have any additional definitions for these keys in the file, and that you've either run lesskey or removed any .less file?

**Comment by bew** [comment]
Indeed that works when I remove everything else, sorry about that.
It also works with `noaction 1\e(` (no need for `\033`)

The offending config I had that broke it for some reason was:
```
#line-edit

# Escape to abort line editing
\e abort
```
(which it turns out, doesn't work at all, any idea how to make that behavior work?)

**Comment by bew** [comment]
The initial issue is solved, I'll close it now.
