### ISSUE TITLE
The options of less are not working when used in pipe

### ISSUE THREAD

**Issue by c02y** [gwsw/less#21]
For example

~~~
$ tree -a . | less
~~~
is the same as 
~~~
$ tree -a . | less -iXFR -x4 -M
~~~
On the bottom-left, it only shows something like `lines 1-43`

But when I use it without pipe
~~~
$ less -iXFR -x4 -M filename
~~~
it shows `filename lines 1-43/369 12%` , this is what I need.

How to make the options work in pipe just like using it without pipe?

FYI: less 530

**Comment by gwsw** [comment]
The four parts of the prompt that you see when you use it without a pipe are (1) the filename, (2) the line numbers currently displayed (3) the total number of lines and (4) the percentage into the file. When used in a pipe, less does not know how long the input is until it reaches EOF, so it cannot display (3) or (4). And there is no filename, so (1) is not displayed either. If the pipe is of reasonable length, you can press Gg to go to the end and then return to the beginning, which will cause (3) and (4) to be displayed.

**Comment by c02y** [comment]
Oh, that is reasonable.

Thanks.
