### ISSUE TITLE
Cyclic search

### ISSUE THREAD

**Issue by Nudin** [gwsw/less#213]
When you search in less and hit the end of the document, you have to hit `gg` to jump to the beginning and then continue the search. Many other programs implement a cyclic search instead, or offer it as an optional feature. In this case, when a search hits the bottom, it automatically jumps back to the beginning.
It would be nice if less also had a flag to enable this behavior.

**Comment by gwsw** [comment]
Implemented in e8edfb80b4adfc7db95e162291ac79954288de6e, available in less-595.
