### ISSUE TITLE
Windows Terminal Unicode output

### ISSUE THREAD

**Issue by segevfiner** [gwsw/less#221]
With:
```powershell
$env:LESSCHARSET='utf-8'
```

In Powershell 7.2.0 (Windows 10.0.19042.1348) in Windows Terminal. Trying to run:
```powershell 
'❯' | less
```

Prints it escaped, despite the fact that Windows Terminal can display full Unicode correctly (But not the plain cmd window, which can only display BMP Unicode):

![image](https://user-images.githubusercontent.com/24731903/141217370-ea8e084c-c89e-478d-a1a3-06100a6f5309.png)

The code here https://github.com/gwsw/less/blob/294976950f5dc2a6b3436b1d2df97034936552b9/charset.c#L809-L818 in particular looks suspect as in `utf_mode = 2` you are going to use `WriteConsoleW` and as such should be able to print any Unicode character regardless of the console output code page (The console output code page is only used for ANSI functions and standard streams). Just changing it to `utf_mode == 1` made it print the character correctly (Might also require a new enough Windows 10 and Windows Terminal):

![image](https://user-images.githubusercontent.com/24731903/141217554-3d29e31d-dfd7-43c3-af88-0a023ee2bb5c.png)

But there is the caveat that you might still want to escape non-BMP Unicode characters on the plain cmd Window which only supports UCS-2 AFAIK, but not on Windows Terminal, VS Code terminal, etc. Not sure how to detect this.

**Comment by gwsw** [comment]
From your description I deduce that GetConsoleOutputCP() is returning CP_UTF8, but WideCharToMultiByte() on that character is failing (setting used_default) even though the terminal can display that character. That would seem to be an inconsistency in the terminal's behavior. But perhaps I'm not fully understanding the situation. @adoxa do you have any comment?

**Comment by adoxa** [comment]
It's the opposite: `utf_mode == 2` means less is using UTF-8, but the console is not. Does using `chcp 65001` help? Might simply add "or Windows Terminal" to the test.

**Comment by segevfiner** [comment]
But in `utf_mode = 2` you are then using `WriteConsoleW` which bypasses the console output CP... I'm not realy sure what ghat bit of code is meant to achieve...  
There are other terminals that support full Unicode than Windows Terminal nowadays, e.g. the embedded one in VS Code.

**Comment by adoxa** [comment]
The terminal might be UTF-8, but the console itself is not (probably CP850). The code shown above is detecting if the wide character can be converted to whatever code page the console is using - it can't, so it's treated as binary (instead of displaying the missing glyph box). If you place the console in UTF-8 mode (`chcp 65001`, which also enforces the UTF-8 charset) then that code is skipped, as `utf_mode` stays as 1. Since WT is not the console, should probably change the test in `charset.c` to:

```
#if MSDOS_COMPILER==WIN32C
				*(p->p_flag) = 1 + (GetConsoleOutputCP() != CP_UTF8 && !getenv("WT_SESSION"));
```

**Comment by segevfiner** [comment]
> The terminal might be UTF-8, but the console itself is not (probably CP850). The code shown above is detecting if the wide character can be converted to whatever code page the console is using - it can't, so it's treated as binary (instead of displaying the missing glyph box). If you place the console in UTF-8 mode (`chcp 65001`, which also enforces the UTF-8 charset) then that code is skipped, as `utf_mode` stays as 1. Since WT is not the console, should probably change the test in `charset.c` to:
> 
> ```
> #if MSDOS_COMPILER==WIN32C
> 				*(p->p_flag) = 1 + (GetConsoleOutputCP() != CP_UTF8 && !getenv("WT_SESSION"));
> ```

Ha, but therein lies the surprise! `WriteConsoleW`, which is used when `utf_mode = 2`, **doesn't** use the console code page and is able to print Unicode just fine regardless of it, depending on the font and console host/terminal program. Check that screenshot I posted, the code page was left at its default OEM code page and the only change I did was disabling that piece of code in less.

Check https://github.com/python/cpython/blob/main/Modules/_io/winconsoleio.c which uses the very same trick. There is even code in the .NET framework to use this trick if you set `Console.OutputEncoding = Encoding Unicode`: https://github.com/dotnet/runtime/blob/5fa6dd364982be4ffd83358adbf130d88049c72a/src/libraries/System.Console/src/System/ConsolePal.Windows.cs#L109-L113, https://github.com/dotnet/runtime/blob/5fa6dd364982be4ffd83358adbf130d88049c72a/src/libraries/System.Console/src/System/ConsolePal.Windows.cs#L1205-L1212

**Comment by adoxa** [comment]
ConHost doesn't do font fallback, so when the glyph isn't supported you get the box; I chose to prefer the binary representation, instead. WT does do font fallback, so converting to binary is not necessary, and that's what the additional test will prevent (although a test for PTY itself might be better, but I'm not sure if there is one).

**Comment by segevfiner** [comment]
It doesn't do font fallback and I'm not sure it even handles non BMP Unicode characters in any Windows version. The thing is that there are more programs than Windows Terminal that can do proper font rendering, such as the embedded terminal in VS Code, and I'm really not sure how to detect them...

**Comment by adoxa** [comment]
There's two potential approaches to detect ConPTY: the current font width is 0; or `GetLargestConsoleWindowSize` returns a pixel-sized width (16 smaller than desktop, in my case). At least, that's what happens under WT, presumably it's true for ConPTY in general.

**Comment by segevfiner** [comment]
### cmd
```python
In [1]: import win32api

In [2]: import win32console

In [3]: a=win32api.GetStdHandle(win32api.STD_OUTPUT_HANDLE)

In [4]: b=win32console.PyConsoleScreenBufferType(a)

In [5]: b.GetCurrentConsoleFont()
Out[5]: (0, PyCOORDType(X=7,Y=16))

In [6]: b.GetLargestConsoleWindowSize()
Out[6]: PyCOORDType(X=232,Y=56)
```

### Windows Terminal
```python
In [1]: import win32api

In [2]: import win32console

In [3]: a=win32api.GetStdHandle(win32api.STD_OUTPUT_HANDLE)

In [4]: b=win32console.PyConsoleScreenBufferType(a)

In [5]: b.GetCurrentConsoleFont()
Out[5]: (0, PyCOORDType(X=0,Y=16))

In [6]: b.GetLargestConsoleWindowSize()
Out[6]: PyCOORDType(X=2544,Y=83)
```

I have no idea how reliable this is...

**Comment by segevfiner** [comment]
Perhaps someone should contact someone from https://github.com/microsoft/terminal#communicating-with-the-team to ask about this or just open an issue on that repo?
