### ISSUE TITLE
less 596 - odd behaviors with --header 10,5 and similar

### ISSUE THREAD

**Issue by larrypl** [gwsw/less#222]
Great new feature with the headers! But it doesn't look like both numbers work correctly.

Using the less NEWS file as an example, this
`paste - - - - - < NEWS | env -u LESS less --header 10,5`
produces odd results (loss of : line, control-c places cursor in random location, commands (like q) don't work).

Another example of the same:
`paste NEWS INSTALL | env -u LESS less --header 10,5`
when the screen is 80 columns wide, produces similar, but slightly different, results.

Both the above require suspending and killing with a TERM signal to exit.

Running a mysql command and piping to less with `--header 3,15` (where 15 happens to be the width of the first column) shows the column name but not the other column names, and scrolling down continues to show the first column name but not the others, but with the underlined line to show the first 3 lines.

But the real attempt is to have mysql output piped to less with `--header 3,15 -S` to show the column headers, and the primary key field (the first 15 columns) and be able to scroll up/down/left/right. When I attempt that, the second three lines of output show in the first three lines instead of the MySQL column header, and repeat in the second three lines. Scrolling right continues to show the second set of 3 lines rather than the first. Example output with `--header 3,8`:
```
| one  |------+-------+
| four | c2   | c3    |
+------+------+-------+
| one  | two  | three |
| four | five | six   |
+------+------+-------+
~
```
After scrolling right:
```
| one  |
| four |
+------+
| one  |
| four |
+------+
~
```

**Comment by gwsw** [comment]
Yeah, this was pretty messed up. Should be fixed in v597.

**Comment by larrypl** [comment]
Great - thanks!

**Comment by larrypl** [comment]
Works great - thanks again!
