### ISSUE TITLE
How about an option to make q quit just like ^C + --quit-on-intr

### ISSUE THREAD

**Issue by jidanni** [gwsw/less#224]
```
# journalctl
q
^C
^C^C^C
^Z
[1]+  Stopped                 journalctl
# kill %
[1]+  Terminated              journalctl
```
OK, `less --quit-on-intr` fixes this mostly,
but how about an option to make "q" quit even without needing to then hit ^C if q doesn't work right away?
less 551

**Comment by gwsw** [comment]
Is this the same as #62, or is it referring to a different case?

**Comment by jidanni** [comment]
I'm not too qualified to say.

**Comment by gwsw** [comment]
The --intr option was added in 7a930a4b872e67b537fdde5af2245506f47d67df, which lets you specify the read interrupt character (default ctrl-X). You could change it to "q" if you wanted. You'd still need to press "q" twice to exit less if "Waiting for data" is displayed (once to abort the read and again to exit less).
