### ISSUE TITLE
different about MacOS `less` and `more`

### ISSUE THREAD

**Issue by gMan1990** [gwsw/less#23]
* `uname -a`
Darwin *deMBP 17.2.0 Darwin Kernel Version 17.2.0: Fri Sep 29 18:27:05 PDT 2017; root:xnu-4570.20.62~3/RELEASE_X86_64 x86_64

* `gsha1sum /usr/bin/more /usr/bin/less`
6f6ec068da5870eb28b04d0cc50abc5ec5e4b85e /usr/bin/more
6f6ec068da5870eb28b04d0cc50abc5ec5e4b85e /usr/bin/less

* `more --version`
less 487 (POSIX regular expressions)
Copyright (C) 1984-2016 Mark Nudelman

    less comes with NO WARRANTY, to the extent permitted by law.
For information about the terms of redistribution,
see the file named README in the less distribution.
Homepage: http://www.greenwoodsoftware.com/less

* Q: `/usr/bin/more` `/usr/bin/less` same file looks? but have different output:
    * `more -n 3 long.txt`
        look like `linux more` or `linux pg`
    * `less -n 3 long.txt`
        less file `3` and `long.txt`

**Comment by gwsw** [comment]
Less attempts to behave in a manner compatible with the POSIX "more" spec when it is invoked with the name "more". See the man page section "COMPATIBILITY WITH MORE" for details.
