### ISSUE TITLE
use line numbers unless file is larger than <arg>KB

### ISSUE THREAD

**Issue by gregrwm** [gwsw/less#230]
Allow -n to be given an argument.  Null or zero would be the same as no argument.  For other values, if a file is that size or smaller, use line numbers, otherwise don't (until told otherwise).  Maybe also interpret multipliers like k/m/g and/or kb/mb/gb etc.

**Comment by gregrwm** [comment]
Or, instead, whether by default or by option, count line numbers within the range of the file which has already been read, and not further.  in the case where there are uncounted lines preceding the current position the line numbers could be like
50%-3
50%-2
50%-1
50%
50%+1
50%+2
50%+3

**Comment by gwsw** [comment]
The size of the file isn't necessarily known when the first page of the file is displayed (for example, it might be a pipe). Therefore the decision on whether or not display line numbers could change while scrolling through the file. Having line numbers suddenly disappear doesn't seem like it would be a good user experience. 

The suggestion to use symbolic numbering like "50%+1" doesn't seem very useful either, besides being quite ugly and transient. A particular line number might appear as "50%+1" at one point in time, and then "60%-100" at some later time after a different seek. I really can't see that being useful to the user, nor implementable in any reasonable way.
