### ISSUE TITLE
Suggestions for --redraw-on-quit (bugs?)

### ISSUE THREAD

**Issue by bew** [gwsw/less#231]
_Extracted from #36_

Hello, while testing the beta release 598 and the `--redraw-on-quit` feature (from #36), I noticed a few things that stops me from using that option:

![image](https://user-images.githubusercontent.com/9730330/145644949-b23a6d7d-ba68-4180-adb0-ac70805d75e3.png)
(note: I've scrolled up a bit to show what I did)

### 1. Paging small content adds many `~` on quit

When using the pager with small content (less than terminal height), quitting will print the content followed by many `~` lines to fill the terminal.
Is that intentional? Can I remove these?

:point_right: If the content is smaller that terminal hight, I'd like to show the pager, and then have _only_ the content printed on quit, as if I didn't use the pager.

### 2. Line `...skipping...` that shouldn't be there?

There's a line `...skipping...` at the beginning of the printed text on quit.
I'm guessing it's meant to indicate that the first printed line is _not_ the first line of the piped content. But in this case it is, so that line shouldn't appear? :eyes: 

:point_right: I think that line should _only_ be visible when there's actually 1 or more lines skipped / not displayed at the beginning AND/OR at the end of the file

Also maybe change that line to `...skipped lines...` ?

---
Do you see what I mean?
What do you think?

**Comment by gwsw** [comment]
Fixed in f90a807301526b12af5d09073584d51a3226aec1.

**Comment by bew** [comment]
Thanks a lot!
I'd like to use it, I tried to build it from master but I can't get the ./configure script to work (and the initial autoconf gave me a bunch of errors as well, maybe it's too recent? (v2.71)).

Since you mention in a few places that we should instead use releases from your website, could you make a release including the commit https://github.com/gwsw/less/commit/f90a807301526b12af5d09073584d51a3226aec1 ?

**Comment by gwsw** [comment]
I will make a new release including these changes soon.

Regarding your build failure, did you follow the instructions in the README, specifically step 2 in which you run "make -f Makefile.aut distfiles"? If so, can you send me the output from your failed make?

**Comment by bew** [comment]
I missed this step `make -f Makefile.aut distfiles`, now I can compile without issue :+1: 

I noticed that I don't see any `~` anymore, BUT it still inserts many newlines (instead of the `~`s), to make the prompt end on the last line of the terminal:

https://user-images.githubusercontent.com/9730330/147286643-7bfa7146-9e36-4765-9375-b1014560ba1c.mp4

**Comment by gwsw** [comment]
It's not really inserting newlines; it's using an escape sequence to jump to the lower left corner of the screen. If your screen is full of text so that you are already at lower left when you run less, you won't see any extra blank lines. You'll only see them if your shell prompt is above the lower left, as your example showed. I'm not sure how easy it would be to suppress the move to lower left, but I'll take a look at it.

**Comment by gwsw** [comment]
This should be addressed in 4a8dc1f41a2f02e09f0ad804d778977fbd7d887a, available in version 599.
