### ISSUE TITLE
[TRIVIAL] man page "N lines"

### ISSUE THREAD

**Issue by Yujah** [gwsw/less#240]
The man page in the description of the first command "SPACE or ^V or f or ^F" says

"Scroll forward N lines, default one window (see option -z below). If N is more than the screen size, only the final screenful is displayed."

but what is "N"? Seems to be from the "^N" description a bit below? Same in most descriptions in that section in fact (z, d, b, w, y, ...).

Just noticed while referring a new Linux user to "man pages", and to navigate them, then also to "man less", and for any such new user it's a bit confusing at least. Have version 551 but have just now verified this to be the same still in the 590 "less.man" source file.

**Comment by gwsw** [comment]
A few lines above that, it says

       Commands  are based on both more and vi.  Commands may be preceded by a
       decimal number, called N in the descriptions below.

**Comment by Yujah** [comment]
Terribly sorry. I even very specifically read "commands are based on both more and vi" but then, somehow, managed to not notice the rest. No idea how; sorry for the noise.
