### ISSUE TITLE
Option --lesskey-file not working properly in 551

### ISSUE THREAD

**Issue by estebanflamini** [gwsw/less#246]
Bindings for non-printable keys (e.g. \kd) are not interpreted correctly when a lesskey file is specified in the command line with `--lesskey-file'.

After compiling the following input file with lesskey:

> #command
> b       back-line
> n       forw-line
> \ku    back-line
> \kd    forw-line
> q       quit
> a       quit
> #stop

if the compiled file is specified in the command line  with --lesskey-file, the non-printable keys do not work properly. If the compiled file is placed in a standard location (~/.less) and **not specified** in the command line, the compiled file is interpreted normally. If the compiled file is placed in the same standard location **and** specified in the command line with --lesskey-file, non-printable keys stop working again.

This bug happens with less 551 after an inplace upgrade from Debian 10 to Debian 11 (running within a virtual machine). less 487 in Debian 10 worked fine.

**Comment by gwsw** [comment]
There were some later fixes in this area. Can you try version 600 and see if it works for you?

**Comment by estebanflamini** [comment]
Thanks for your prompt reply, and I apologize for omitting to try the latest version. I'm rather new to the world of open source :)

Yes, less 600 works fine.

Note: I had to install libncurses5-dev and libncursesw5-dev in order to compile the program.

Thanks again for your time and work!
