### ISSUE TITLE
How to search Chinese character ?

### ISSUE THREAD

**Issue by sisrfeng** [gwsw/less#247]
`LESSCHARSET=utf-8 less myfile`  does not work

Thx !

**Comment by gwsw** [comment]
Can you describe in what way it is not working, and also describe what operating system and terminal you are using? Searching for hanzi text on a Terminator terminal on Linux seems to work fine for me.

**Comment by Konstantin-Glukhov** [comment]
Here are the screenshots of less working on Linux:

less [Japanese.txt](https://github.com/gwsw/less/files/8367858/Japanese.txt)

<img width="135" alt="Linux-1" src="https://user-images.githubusercontent.com/24302271/160528930-dffedf25-abff-4ac6-8517-813a65b609dc.png">

Enter a search text in Japanese and hit Enter:

<img width="119" alt="Linux-2" src="https://user-images.githubusercontent.com/24302271/160529233-e8c770fb-bae2-47c8-90c1-3fe2bd0d8a80.png">

Search results are highlighted:

<img width="101" alt="Linux-3" src="https://user-images.githubusercontent.com/24302271/160529235-31f1f33c-15b4-4660-b4a9-288a5d32705c.png">

Here are the screenshots of less hanging on Windows (results are the same in both cmd.exe and PowerShell.exe):

Open a file with less:

<img width="335" alt="Windows-Cmd-1" src="https://user-images.githubusercontent.com/24302271/160530461-140e5496-32ad-41c2-be52-360e214b384e.png">
<img width="136" alt="Windows-Cmd-2" src="https://user-images.githubusercontent.com/24302271/160530463-075c9ef9-c8a4-4f07-aa6e-392ff22c3914.png">

Enter a search text in English and hit Enter:

<img width="113" alt="Windows-Cmd-3" src="https://user-images.githubusercontent.com/24302271/160530464-d6b5c63f-b5bf-429f-ab0b-e7f26434620e.png">

Search results are highlighted:

<img width="106" alt="Windows-Cmd-4" src="https://user-images.githubusercontent.com/24302271/160530465-acd3eab9-2cd2-48f9-90a3-453bd60ade31.png">

Attempt to search a text in Japanese:

<img width="118" alt="Windows-Cmd-5" src="https://user-images.githubusercontent.com/24302271/160530466-0fd934b0-d538-4d39-9e67-efe70c30ad4e.png">

After hitting "/" and entering the first Japanese character, less becomes unresponsive. After that ESC, Backspace, Ctrl-C or "q" do not work, and **less** needs to be killed from "Task Manger".

**Comment by gwsw** [comment]
Ah, I didn't understand from the original report that the problem only happens in the Windows build. @adoxa Jason, do you have any thoughts about this?

**Comment by adoxa** [comment]
Seems something's going awry with console input. I'm afraid it'll be a while before I can take a closer look.

**Comment by gwsw** [comment]
Ok, thanks.

**Comment by Konstantin-Glukhov** [comment]
I tried to run it in VSCode debug mode and it appears that program crashes on **screen.c:2850** when calling **PeekConsoleInput(tty, &ip, 1, &read)**, which maps to:
```
WINBASEAPI
BOOL
WINAPI
PeekConsoleInputW(
    _In_ HANDLE hConsoleInput,
    _Out_writes_(nLength) PINPUT_RECORD lpBuffer,
    _In_ DWORD nLength,
    _Out_ LPDWORD lpNumberOfEventsRead
    );

```
Unfortunately I cannot step into that function to trace it further.

**Comment by Konstantin-Glukhov** [comment]
I am not sure if it is a big deal here but there is datatype discrepancy in screen.c:

Currently the structure elements defined as:

```
struct keyRecord
{
	int ascii;
	int scan;
} currentKey;

```
but they should be:
```

struct keyRecord
{
	CHAR ascii;
	WORD scan;
} currentKey;
```

**Comment by adoxa** [comment]
Here's a potential [fix](https://github.com/adoxa/less/commit/eedc436cb56fca1ccfbacaac41ca3b59136907ed).

**Comment by Konstantin-Glukhov** [comment]
I tried the fix, but PeekConsoleInput() still fails with **error 233: No process is on the other end of the pipe**.

**Comment by adoxa** [comment]
What pipe? Worked fine for me in Win10 console & Windows Terminal.

**Comment by Konstantin-Glukhov** [comment]
I have no idea why this error is reported. I am just checking the status returned by PeekConsoleInput() and report GetLastError() if status is 0.

My test is the following:

- uznip less-603.zip
- vcvars32.bat (I have VS17)
- modify screen.c with suggested fix and error reporting
- nmake /f Makefile.wnm
- .\less.exe N:\Tmp\Japanese.txt
- Hit "/"
- Switch to Japanese Input by pressing Alt-Esc
- Hit Backspace twice to get rid off garbage
- Press "=" and select 平和 from popup choice
- Hit Enter

Console freezes with the message "error 233: No process is on the other end of the pipe"

**Comment by adoxa** [comment]
>     * Switch to Japanese Input by pressing Alt-Esc

How did you install "Japanese Input"? Does it override Alt-Esc moving the window to the back? I tested by right-clicking to paste in a character (which then also shows up in history).

> Console freezes with the message "error 233: No process is on the other end of the pipe"

That's weird, since it's not a pipe, but a console; I added error testing, but none was detected (built from git, with VS2010). What Windows (Terminal) version are you using? I have 10.0.19044.1526 & 1.11.2421.0.

**Comment by polluks** [comment]
You may try Windows Terminal Preview v1.13.1073
https://github.com/microsoft/terminal/releases

**Comment by Konstantin-Glukhov** [comment]
Japanese Input is installed by adding a language in windows setup.
I did test copy and paste method too.
My terminal is 10.0.19044.1586
I also tested Windows Terminal preview.
I also tried 64bit build.
Nothing works :)

**Comment by adoxa** [comment]
I added Japanese, but it doesn't really want to install with a metered connection; the IME Pad works, though.

**Comment by Konstantin-Glukhov** [comment]
I think I found a solution for Unicode text. Take a look at the patch for less-603 base below.

[screen.patch](https://github.com/gwsw/less/files/8503338/screen.txt)

In short, **PeekConsoleInputA()** hangs when reading Unicode characters and needs to be replaced with **PeekConsoleInputW()**.
On top of that, **ReadConsoleInputW()** returns Unicode character in one pass, while Linux **read()** gets Unicode character one byte at a time, so the windows Unicode character needs to be converted to multibyte to match the Linux read.

One more improvement is required to suppress Alt-~ sequence to switch to IME Japanese mode. But... one thing at a time.

**Comment by Konstantin-Glukhov** [comment]
Actually a fix to suppress Alt-~ is very obvious: just add VK_KANJI to the exception list of virtual key codes. I just added this fix and it works fine. Below is the updated patch file.

[screen.patch](https://github.com/gwsw/less/files/8503576/screen.txt)
