### ISSUE TITLE
OSC-8 search

### ISSUE THREAD

**Issue by sdaoden** [gwsw/less#248]
Hello!
In 2014 i sent an enhancement via mail that added support for a "mdocmx" groff extension with which less could become an interactive browser.

After less gained OSC-8 support in v566 i rewrote all that and based it upon OSC-8 instead of extending (aka misusing) the traditional backspace Unix manual formatting approach for this.  Thanks for this support!
I also opened a groff extension request, and it was actually implemented (https://savannah.gnu.org/bugs/?60666), and will thus be in the next release of groff, whenever it will happen.
I sent an according patch last year, but got no response.

Please find at [1] a patch against less v600 (11610 bytes) at your disposal.
It adds searching for OSC-8 sequences;  it performs a local search with scrolling for id='s, and with HAVE_SYSTEM it adds the possibility to start man(1) for special man:// URLs.
It assumes OSC-8 sequences (the sequence itself) stay on a line, and i think i recall that less(1) does not handle them across line boundaries either.

  [1]  https://ftp.sdaoden.eu/less-osc8-search.patch

Thanks for consideration.

**Comment by sdaoden** [comment]
P.S.: the manual of the MUA i maintain uses mdocmx sequences, this still requires groff extensions which are not present to extend the mdoc macros to generate anchors and links.  But you can interactively browse a manual on a Unix console with it.  For the interested i pre-create them at release time of this MUA, at [1] you could find the latest, for example.

 [1] https://ftp.sdaoden.eu/s-nail-14.9.23.xcat1.xz

**Comment by sdaoden** [comment]
P.P.S: like in, #id == search local, otherwise pass to LESSURLOPEN if set in environment and secure mode is not on.
(And sorry i am new to github .. and came only (back) to report issues to lessen people's burden with me, you know, they block some countries for reasons that i find odd, especially in context. I am reading about regular pull requests..)

**Comment by sdaoden** [comment]
Hello!
So i looked into this, i was maybe a bit in overreaction since the two mails in 2014 and last year i think did not get any response ..., but i think this can be done much better, without the focus on mdocmx i wrote in 2014.

What i mean is, in the meantime i have learned about pull requests, and i think making this a generic mechanism where ^A can search _any_ OSC 8 id=, and where ^A+ and ^A- can be used to simply search forward/backward to find _any_ OSC 8 link (and highlight its contents even?), and where ^A^A would, in case it is some URL://, ask and try to lsystem() lgetenv("LESSURLOPEN") with the URL as an argument -- this could then be used to read external manuals, open a browser on HTTP, etc etc.

I have to look and test this completely new approach, however, next week.
I will open a pull request when that code is ready for you to consider.
Sorry for the noise.

**Comment by g-branden-robinson** [comment]
Thanks for driving this issue, Steffen.  I just got my first experience playing with _less_'s OSC 8 support today and am pleased with it.  It means I won't have to go launch _gnome-terminal_ to investigate _grotty_'s production of these escape sequences.  (I have a strong preference for _xterm_, but unfortunately for me Thomas Dickey is pretty skeptical of adding OSC 8 support to it.)
