### ISSUE TITLE
--MOUSE conceptionally broken (reversed)

### ISSUE THREAD

**Issue by egmontkob** [gwsw/less#25]
`less` recently introduced two options: `--mouse` for mouse wheel/touchpad scrolling in the "traditional" way, and `--MOUSE` for scrolling in reverse direction, usually referred to as "natural scrolling".

This option doesn't simply reverse the two directions all the time. It just reverses them for content scrolling. E.g. when at the search prompt, for both options the "up" direction searches backwards in the history, the direction isn't swapped. This is conceptually great.

`--MOUSE`, however, has a conceptual problem. It seems to me that this option assumes that `less` is the only application where the user wants to have "natural scrolling".

I think this is extremely unlikely. Even though I don't use this mode personally, I'm pretty sure that those who prefer "natural scrolling" prefer to have it through their entire desktop, for all the graphical and text applications. And for that reason they have enabled "natural scrolling" in their desktop's settings.

What this setting does is that it swaps the two scrolling directions at such a low level that even terminal emulators themselves receive swapped directions from the graphical system (e.g. X11), and thus forward such swapped events to applications such as `less`. Thus, `less --mouse` also automatically gets the "natural scrolling" behavior.

That is, for users who want "natural scrolling" everywhere and thus have it enabled in their graphical environment, `--mouse` is what they need and `--MOUSE` breaks the scrolling direction (reverses it back to the "traditional" way). However, at the search prompt and presumably other similar places where `--MOUSE` doesn't reverse the direction, it's here where it IMO makes sense reverse them back (although would be lovely to hear feedback from those actually using it).

`less` shouldn't implement "natural scrolling" on top a "traditional scrolling" desktop, I don't think it's a valid use case. What is a valid use case is to implement "natural scrolling" on top a "natural scrolling" desktop. For this, the directions shouldn't be swapped for content scrolling, but perhaps should be swapped back at the search prompt to revert to the "moving the fingers upwards goes back in the history" behavior.

**Comment by gwsw** [comment]
If the concern is simply that --MOUSE is unnecessary and will never be used, I don't think any action needs to be taken here. If that's true, doesn't hurt anything to leave it in. (However, it was originally implemented in response to a user request.) Remember that less is used in many different environments (Linux, Unix, Windows, Cygwin, Amiga, OS/9, MS/DOS ... ) and I certainly wouldn't assume that they all provide the same type of low-level support for natural scrolling.
