### ISSUE TITLE
--header breaks layout/scrolling (v600, works in v597)

### ISSUE THREAD

**Issue by Yarn** [gwsw/less#255]
with version 600 `less --header 1`

places the `:` line on the second line instead of the bottom of the terminal.

scrolling down does not update the screen, scrolling up does update the screen.

scrolling down does update the position in the file so scrolling down multiple lines then up one line shows later parts of the file

---

version 600 is working fine without --header, version 597 seems to work as expected with --header

---

i'm on arch linux building less with a modified version of https://man.archlinux.org/man/less.1.en https://github.com/archlinux/svntogit-packages/blob/4e42823f59b302a01469b8813ecb89ddf9833cca/trunk/PKGBUILD
i changed pkgver and sha256sums

**Comment by gwsw** [comment]
Thanks, fixed in 6b785cd283e40bc616c3a770bbad502ed6b38190.
