### ISSUE TITLE
Weirdness when loading large file

### ISSUE THREAD

**Issue by gtg944q** [gwsw/less#262]
I have a large file that I'm trying to open with less:
`-rw-rw-r-- 1 justin justin 495375353 May  2 08:24 prices.log.snap`
When I open it from the same directory, like so:
`justin@scapa:~/curveball_replay/replay_20220414_dirty/var/log/prices$ less prices.log.snap`
This is displayed:
```
*** Contents:
prices.log.snap (END)
```
When I open from another directory, like so:
`justin@scapa:~/curveball_replay$ less replay_20220414_dirty/var/log/prices/prices.log.snap`
less appears to stall out, but if I hit Ctrl+C, it will display the file.

`cat prices.log.snap | less` works fine from any directory.

Setup:
less 551 (GNU regular expressions)
GNU bash, version 5.0.17(1)-release (x86_64-pc-linux-gnu)
Ubuntu 20.04.2 LTS

Please let me know what additional info I can provide.

**Comment by gtg944q** [comment]
After further review, it looks like this is maybe caused by the file having a .snap extension.  Is this intended behavior?

**Comment by gwsw** [comment]
Does it behave differently if you use the -L option? If so, it would indicate that the issue is with your system's LESSOPEN script.

**Comment by gtg944q** [comment]
Yes, it behaves as expected with -L.  Thanks.
