### ISSUE TITLE
No "discoverable" way to switch off colors that hamper readability

### ISSUE THREAD

**Issue by AlainKnaff** [gwsw/less#264]
By default less colors the text that is displayed.
Unfortunately, the choice of colors is less than well thought out :-(
For instance, the status bar at the bottom, as well as highlighted text that matches a search are colored in yellow, making them really hard to read.
I'd like to change that yellow color to something else, or, if not possible, completely switch off usage of colors.

However, the man page doesn't mention a way to do so, and tricks that work with other programs such as setting TERM to xterm-mono don't work with less.

**Comment by gwsw** [comment]
Less does not display colors by default. You must set the --use-color option for colors to show. I suspect your system has been configured to set that option automatically. You can check this by running less and then type ```__use-color``` (note the double underscore at the beginning). You can toggle colors off by typing ```--use-color```. If this works, you will need to find where the option is being set (probably in your LESS environment variable or lesskey file) and change it.

Also, less's default colors when --use-color is set are not as you describe -- the command line at the bottom is blue, and search matches are green. This makes me suspect that you also have some --color options set as well, but those will be ignored after --use-color is turned off so you don't need to worry about them.

**Comment by AlainKnaff** [comment]
Thanks.
Indeed, it turned out that I had indeed LESS_TERMCAP_xx environment variables set in my .bashrc. Not sure where I got these from, but they became apparent when I recently switched back from zsh to bash.
After unsetting these variables, less now behaves correctly.
I'm using less-551(the version supplied with Debian 11)

**Comment by gwsw** [comment]
I see, that's a little different than what I thought was happening. less-551 does not support color, but someone apparently used the LESS_TERMCAP_xx trick to change less's standout (reverse video) formatting to the color you were seeing. Removing the LESS_TERMCAP_ settings from your environment is the right fix.
