### ISSUE TITLE
When I use ignore case in search, if my search contains any uppercase letters it will act as if case is significant.

### ISSUE THREAD

**Issue by Ma-XX-oN** [gwsw/less#269]
1. Type command `echo Hello there | less` `[enter]`.
2. Type `/hello` `[enter]`.  Won't find it since case is significant by default.
3. Type `-i`.  Will now find `Hello`. Acting as if case is not significant.
4. Type `/HeLlo` `[enter]`.  Won't find it when it should. Acting as if case is significant.
5. Type `/Hello` `[enter]`.  Will find it.  Acting as if case is significant.

Tried in version 590 and 603.

**Comment by gwsw** [comment]
This is intentional behavior. See the description of the -i and -I flags in the man page.
