### ISSUE TITLE
How to use alt key

### ISSUE THREAD

**Issue by concatime** [gwsw/less#27]
What do i need to add in lesskey file to map Alt-k ?

**Comment by keithbowes** [comment]
I've wondered the same thing.  According to the documentation, it seems that the only modifier keys allowed are Ctrl and Esc.  That's most unfortunate, as Alt is in a much more convenient location than Esc (I swap my caps, so Ctrl isn't inconvenient either).

**Comment by gwsw** [comment]
I don't know if there's a way to detect the Alt key. Pressing ALT-x in a mintty window running on Windows 10 just produces two characters ESC x. I believe rxvt does the same thing. I don't know what other terminal emulators do, or what the native cmd interpreter does. I've heard that some terminals set the high bit, but I haven't seen that in any emulator I've used. 

In any case, it should be possible to determine what key sequence is sent by ALT-x in the terminal that you are using, and map that sequence using lesskey, using the \ddd octal notation if necessary.
