### ISSUE TITLE
`--incsearch` breaks UTF-8 searching

### ISSUE THREAD

**Issue by kidonng** [gwsw/less#273]
less version: 581.2 (vendored version in macOS 12)

When `--incsearch` is specified, searching for UTF-8 string (such as "你好" and "世界" in the following example) gives no result. This affects both `--pattern` and `/pattern` etc.

https://user-images.githubusercontent.com/44045911/178936613-6b7f8134-b3a3-4f0b-a895-7592d6e80a51.mov

**Comment by gwsw** [comment]
Thanks, this should be fixed in 7e6da25e345b146e2ced95a705dfe865d8c650cc.
