### ISSUE TITLE
Improve match navigation: no way to navigate between matches on long lines

### ISSUE THREAD

**Issue by deliciouslytyped** [gwsw/less#287]
There does not appear to be a way to navigate to the previous/next match on a (long) line, only previous/next matched lines?
Can this be implemented?

Thanks!

**Comment by gwsw** [comment]
Not implemented yet, but note that the recent changes to the status column (02d8b0cbfd1bcbbacc793548531f19c7f4a51de0) make it easier to see when there are search matches that are not visible beyond the left or right screen edge.

**Comment by gwsw** [comment]
In less-643, normal searching with / and ? will navigate to matches within the current line.
