### ISSUE TITLE
Gpg question.

### ISSUE THREAD

**Issue by Achaean** [gwsw/less#288]
**Hi!**

I'm probably missing something, not a bug.

I was trying to verify the downloaded package and I'm getting this:

```
>gpg --verify less-608.sig
gpg: no signed data
gpg: can't hash datafile: No data
>
```
Is the signature detached?
Where can datafile can be found?
I couldn't see anything in the download page.

**TIA!!!**  :-)

**Comment by gwsw** [comment]
Yes, the signature is detached. It applies to the corresponding .tar.gz file:
```
gpg --verify less-608.sig less-608.tar.gz
```

**Comment by Achaean** [comment]
**MANY THANKS!!!**  :-)
