### ISSUE TITLE
Dummy ckeck target

### ISSUE THREAD

**Issue by polluks** [gwsw/less#290]
How about implementing the dummy ckeck target as a runtest target?
https://github.com/gwsw/less/blob/ae57646896bd218b1c5c3087d8937da635fb9ef7/Makefile.in#L99
By the way
https://github.com/gwsw/less/blob/ae57646896bd218b1c5c3087d8937da635fb9ef7/lesstest/runtest#L5 run &rarr; runtest

**Comment by gwsw** [comment]
Thanks for the suggestion. This is done as of 9573d422f602823d78d04151633420e5a6b10aac.
