### ISSUE TITLE
NetBSD & gcc 5.5.0 fail

### ISSUE THREAD

**Issue by polluks** [gwsw/less#295]
NetBSD sdf 9.1 NetBSD 9.1 (GENERIC) #0: Sun Oct 18 19:24:30 UTC 2020  mkrepro@mkrepro.NetBSD.org:/usr/src/sys/arch/amd64/compile/GENERIC amd64
```
main.c: At top level:
main.c:331:1: error: conflicting types for 'ecalloc'
 ecalloc(count, size)
 ^
main.c:321:15: note: previous implicit declaration of 'ecalloc' was here
  p = (char *) ecalloc(strlen(s)+1, sizeof(char));
               ^
```
```
$ grep ecalloc /usr/include/*
/usr/include/util.h:void                *ecalloc(size_t, size_t);

**Comment by Eibz-Chan** [comment]
$ grep -r util.h less-master/
less-master/scrsize.c:#include <X11/Xutil.h>

**Comment by gwsw** [comment]
scrsize.c is an obsolete file that's not being compiled, and should probably be removed. I don't know where /usr/include/util.h is coming from; it's probably included in some system include that less uses. It's unfortunate that NetBSD has created a function named ecalloc. I will probably need to rename less's ecalloc to fix this.

**Comment by polluks** [comment]
The declaration was implicit, no prototype at all. After `gmake -f Makefile.aut funcs.h` it works.
Please take care of #294.
