### ISSUE TITLE
"less /proc/cpuinfo" stopped working after less-590, broken on less-600 and less-608

### ISSUE THREAD

**Issue by douzzer** [gwsw/less#298]
I've just noticed, with less-608 on Linux, `less /proc/cpuinfo` gives the appearance of an empty file.  I did a little regression testing and determined the syndrome is also apparent in less-600, but less-590 doesn't have the problem.  And I tested it on every file in `/proc/self/*` and they all incorrectly appeared empty.

I'm running a 6.x kernel, so to rule out new kernel weirdness I copied the less-608 executable to a host with a 5.15.x kernel.  The behavior was the same, empty `/proc/cpuinfo`.

Strangely, `/sys` is not showing the syndrome.  E.g. this works correctly under less-608:
```sh
less /sys/devices/system/clocksource/clocksource0/available_clocksource
```

**Comment by gwsw** [comment]
I think this is the same as #282. Can you confirm whether you still see the problem in builds after 03f011f219a6d6068c4ccd07dbd8dcd50641ff10? I haven't released a numbered build yet, but you can just build from top of tree in the github repository.

**Comment by douzzer** [comment]
@gwsw yup it works for me at 03f011f219a6d6068c4ccd07dbd8dcd50641ff10 , but interestingly if I just apply that one commit to less-608, it doesn't work.

btw the Makefile generated from git sources didn't create funcs.h or help.c for me -- I had to figure those out myself.

**Comment by gwsw** [comment]
I'm glad to hear that less-608 fixes the problem for you.

Regarding funcs.h and help.c, step 2 of the instructions in the README file says to run ```make -f Makefile.aut distfiles``` if you are building from a git clone. Did you do that?

**Comment by douzzer** [comment]
Nope didn't -- that must be it.
