### ISSUE TITLE
--ignore-case doesn't work when searching in non-regex mode

### ISSUE THREAD

**Issue by ahmadsamir** [gwsw/less#300]
- start less with --ignore-case (or use LESS or export LESSKEYIN ...etc)
- / to start searching, Ctrl+R to search in non-regex mode
- search for a lower-case string, notice that it doesn't find upper-case matches

**Comment by gwsw** [comment]
Fixed in 939b26b25e67420c84bf8481355e007e9f2abd5c.

**Comment by ahmadsamir** [comment]
That was fast; thanks :)
