### ISSUE TITLE
No way to inhibit visual bell

### ISSUE THREAD

**Issue by devkev** [gwsw/less#304]
I use `-Q` in my `$LESS` env var to inhibit the terminal bell.  I recently upgraded OS to a later version that includes 0af04471e9f80b7d25b38b2d309b98316bb33703, and now the visual bell is "working" in all the situations that it previously didn't.  However, over many years I've become accustomed to `-Q` inhibiting all feedback (due to the termcap/terminfo problem which the above commit works around), and I like that behaviour.  Whereas I now find the full-terminal flashing of the current visual bell to be quite jarring.

When I went looking for the flag to add to `$LESS` to inhibit the visual bell, and get back the old behaviour, I was very surprised to find that there isn't any such flag.  Would you be open to adding one?  It could be very simple, eg. a BOOL option adjacent to `quiet` (eg. `--inhibit-vbell`) which is checked at the start of `vbell()` and causes an early return.  I'm happy to send a pull request, if you'd like.

**Comment by gwsw** [comment]
It makes sense to add a flag to do this. In the meantime, you could do it by setting ```LESS_TERMCAP_vb``` to some sequence that does nothing. Unfortunately you can't just set it to an empty string, but "```\x7F```" or "```\x1B[s```" will work on many terminals.

**Comment by gwsw** [comment]
It was intended as a debugging tool rather than a feature for end users. However it is occasionally useful in certain situations, like this one. I guess I should add a description to the man page.

**Comment by gwsw** [comment]
The --no-vbell option is implemented in 0c6c01757e4be854dae65ea56d745e1b9fdbf655.

**Comment by devkev** [comment]
> The --no-vbell option is implemented in [0c6c017](https://github.com/gwsw/less/commit/0c6c01757e4be854dae65ea56d745e1b9fdbf655).

Thanks for this!  The commit was actually cc00a2c.  Your patch matches the intention of what I was suggesting.

> In the meantime, you could do it by setting `LESS_TERMCAP_vb` to some sequence that does nothing. Unfortunately you can't just set it to an empty string, but "`\x7F`" or "`\x1B[s`" will work on many terminals.

I didn't get around to testing this, because I had already installed a hacked-up version of less.  However recently a security update has replaced my hacked version with the original (v590), re-introducing the problem.  I can confirm that setting LESS_TERMCAP_vb to either of those values works nicely, and is a much cleaner workaround than my package-hacking (until I upgrade my distro to something with v615+).

Thanks again!!
