### ISSUE TITLE
less-610 is noticeably slower to start

### ISSUE THREAD

**Issue by JoshyPHP** [gwsw/less#306]
For context, I use `less` as my pager for listing directories, reading man pages, and all the usual. As far as I'm concerned, `less` is a perfect program because I usually don't realize I'm using it. However, since upgrading from  `less-608` I noticed that all those actions suffered from a small stutter at the start, displaying the "Waiting for data..." message even for listing small directories that do not actually require paging. I tracked it down to 8e3ec369acfa1741c2e84a1655914c40c63a3f47 which increases sleep from 2 ms to 250 ms. Evidently, reverting the commit restores `less`'s snappy behaviour and my blissful ignorance of running it while navigating the filesystem.

This is a [paper cut](https://en.wikipedia.org/wiki/Paper_cut_bug) that I solved locally by patching my system. I have no preference as to how to fix it or whether it should be considered an issue in the first place, but I suspect that more users will notice the 250 ms delay if it makes it to a stable version.

**Comment by milosivanovic** [comment]
I'm also seeing this behaviour, in addition to `G` not going to the bottom anymore either. In my example: `dmesg | less` and then hitting G doesn't scroll to the bottom anymore. It does show the pager in the status bar (i.e. 10% in my case for not having moved at all) but does not actually page to the bottom.

**Comment by gwsw** [comment]
This should be fixed in less-614.
