### ISSUE TITLE
less 612 no longer scrolls to the bottom correctly

### ISSUE THREAD

**Issue by milosivanovic** [gwsw/less#307]
I often type `dmesg | less` or `dmesg | less +G` to check the scrollback, but with >less-608 (at least 612) pressing G just shows the pager in the status bar but does not scroll any further than what was already on the screen. I have to press G again to finally get it to scroll to the bottom. G needs to be pressed twice.  It is reproducible each time.

This might be related to https://github.com/gwsw/less/issues/306.

Another possibly related datapoint from #gentoo:

```
[15:55:15] <@floppym> FWIW, less-612 does seem to behave stangely with input piped from git-log.
[15:55:46] <@floppym> It seems to "hiccup" when the pipe isn't saturated.
```

**Comment by gwsw** [comment]
This should be fixed in less-614.
