### ISSUE TITLE
`less +F` is much less efficient than `tail -f`

### ISSUE THREAD

**Issue by milosivanovic** [gwsw/less#308]
`less +F` is polling in a loop and making thousands of system calls unnecessarily. In contrast, `tail -f` is using inotify to be efficiently notified of file changes.

**less +F /var/log/messages:**
```
comet ~ # timeout 10 strace -c -p 8756
strace: Process 8756 attached
strace: Process 8756 detached
% time     seconds  usecs/call     calls    errors syscall
------ ----------- ----------- --------- --------- ----------------
 45.98    0.028906           3      9320           poll
 32.13    0.020199           4      4659           clock_nanosleep
 21.87    0.013750           2      4660           read
  0.01    0.000006           6         1           restart_syscall
------ ----------- ----------- --------- --------- ----------------
100.00    0.062861           3     18640           total
```

**tail -f /var/log/messages:**
```
comet ~ # timeout 10 strace -c -p 8698
strace: Process 8698 attached
strace: Process 8698 detached
```

As per the above results, `tail -f` makes 0 system calls in 10 seconds (since the file was not appended to in that time), vs `less +F` which did thousands and contributed much more CPU time, context switches and interrupts to the task than necessary.

Additionally, this relatively recent commit tightens the polling loop even more: https://github.com/gwsw/less/commit/7b0cce57297ac8aba7a043d27e42b35fad79ed87. Given that it's a loop, I think the original 1 second delay is a lot more appropriate than sleeping for 2ms just to see if there's new content in a file. The latter seems excessive.

Is it possible to implement inotify for `less +F` to make it as efficient as `tail -f`? It looks like this is the commit that introduced inotify to tail: https://github.com/coreutils/coreutils/commit/ae494d4be80df2aff50a2ac46fdc0c23de109ea3

**Comment by gwsw** [comment]
This should be improved in less-614.
