### ISSUE TITLE
[bug]directly press enter after input "less -"

### ISSUE THREAD

**Issue by EibzChan** [gwsw/less#309]
version: less 590
question:
If I directly press enter after input "less -"，the screen will be displayed as follows：
![黑屏界面](https://user-images.githubusercontent.com/111971485/204416431-de0f5b91-202a-4c7f-9398-12ef4976b117.PNG)

When I press enter，less has not prompt any error messages. When the screen enters the above state，it could not exit by pressing q，or input any command.

**Comment by Eibz-Chan** [comment]
[https://github.com/gwsw/less/commit/0194c82dc8de6af9dad28d9ad79dc679d14f67a9](url)

**Comment by Eibz-Chan** [comment]
fixed by [https://github.com/gwsw/less/commit/0194c82dc8de6af9dad28d9ad79dc679d14f67a9](url)
