### ISSUE TITLE
less Version 590 became buggy regarding "-R"

### ISSUE THREAD

**Issue by Anton-Wessel** [gwsw/less#312]
My old script like

    apropos man | grep --color=always -ie "man" | less -R -I +/^K"man"

does not work correctly since I have the less version 590.

The bad effect is that the three characters "man" are removed everywhere in the text.

The workaround is to use as less option not capital letter "-R" but small letter "-r".

Yet I would not like to alter all my scripts for the time period until the bug will be corrected.

And -r makes dispay on svree messy.

Some tests:

a file containing word "echo".

grep color=always "echo" <<file>> | less -R

In the display of less, word "echo" is colored.

When in less I type as search pattern "echo" in the display the word "echo" is not highlighted but stolen.

Please correct this bug urgently.

Regards

Anton_Wessel@t-online.de

**Comment by gwsw** [comment]
This is fixed in the latest version, less-608. You can download it from https://greenwoodsoftware.com/less/download.html.

**Comment by Anton-Wessel** [comment]
thank you for your emaim of 15.12
2022 18:13, for your info and for giving me the link for download less 608.

Regards

Anton Wessel

=====

Am 15. Dezember 2022 18:13:32 schrieb gwsw ***@***.***>:
