### ISSUE TITLE
Mouse mode is always deinitialized when exiting `less`, even when it shouldn't be

### ISSUE THREAD

**Issue by jaminthorns** [gwsw/less#313]
When using `less` with mouse mode enabled (with the `--mouse` flag), `less` initializes mouse mode on open and deinitializes mouse mode on exit. This presents a problem when `less` is invoked from within a program that is already in mouse mode. In my case, I'm executing `less` from within `fzf` (which always uses mouse mode). This means that upon exiting `less`, mouse mode gets deinitialized when returning to the invoking program, and the program doesn't work correctly.

Is there a way for this to be fixed by checking if `less` is already in mouse mode when being initialized?

**Comment by gwsw** [comment]
Interesting issue. I don't believe there is a way to detect whether the terminal is in mouse reporting mode, but I'll look into that some more. One possible workaround would be to set the environment variable LESS_TERMCAP_MOUSE_END (and perhaps LESS_TERMCAP_MOUSE_START) to a string that does nothing. Unfortunately you can't set it to an empty string, but you could set it to a DEL character (0x7f) or some innocuous escape sequence like "ESC[s". Then passing the --mouse option to less will enable interpretation of mouse events but won't send the init/deinit sequences. If you do this, mouse input will work ONLY if the init sequence has been previously sent by another program, so if you use less both with fzf and also in standalone mode, you'll need to conditionally set these variables only when used with fzf.

**Comment by jaminthorns** [comment]
That solution actually works very well, thank you!

It did feel a bit hacky to me, though. After thinking about it some more, a cleaner solution to my specific problem came up. Because it's not possible for a program to detect whether it's currently in mouse reporting mode, and any application that uses mouse reporting mode would have to do what `less` does (enable on enter, disable on exit), that means that whenever you're calling an external program from within a program that uses mouse reporting mode, you should:

- Disable mouse reporting mode (`tput XM 0`)
- Execute the program (which can then enable and disable mouse reporting as it pleases)
- Re-enable mouse reporting mode (`tput XM 1`)

NOTE: The `XM` terminal capability is documented in the [`user_caps` map page](https://man7.org/linux/man-pages/man5/user_caps.5.html).

This feels like a cleaner solution to the issue, since it doesn't just apply to `less` or `fzf`, but for any programs that step on each other's toes when it comes to mouse reporting. Hopefully this issue will come up in a search for anyone who encounters a similar problem.

**Comment by gwsw** [comment]
I agree that your solution is better. This is in fact what less itself does -- if you run with --mouse and then use the ! command to run a program from within less, less will disable mouse reporting, run the program, and then re-enable mouse reporting.
