### ISSUE TITLE
Put less in search mode on startup

### ISSUE THREAD

**Issue by Jackenmen** [gwsw/less#314]
Is there a way to put less in search mode on startup using command-line options?
Or perhaps more generally, to set the initial input passed to less on startup?

Basically, if I pass some command-line option, I would like to be able to start typing search phrase immediately after starting less. My use case is related to the kitty terminal which allows showing its scrollback in a pager. I would want it to start less in such a way that I can start typing search phrase immediately without having to first hit the `/` key.

**Comment by kovidgoyal** [comment]
You dont need support form less for this, you can use the following in kitty.conf

```conf
map f1 combine : show_scrollback : send_text normal,application /
```

Replace f1 with whatever key combination you want.

**Comment by Jackenmen** [comment]
I didn't expect to see you here :eyes: Thanks for the tip, that works!

I guess I'll close this then since I don't have another use case for this feature myself.
