### ISSUE TITLE
'less' should port to C23 by using function prototypes

### ISSUE THREAD

**Issue by eggert** [gwsw/less#316]
One of the changes in the 2023 edition of the C standard is that support for K&R style function definitions has been removed. Since 'less' still uses these, it won't compile on a vanilla C23 compiler. And since nobody cares about pre-C89 compilers any more, the simplest fix is for 'less' to use C89-style function prototypes everywhere. It is 33 years after C89, after all.

GCC optionally warns about these obsolete usages; see attached build transcript.I expect some compilers will start erroring out entirely soon.

[lessbug.txt](https://github.com/gwsw/less/files/10302462/lessbug.txt)

**Comment by gwsw** [comment]
I agree that it's time to do this. 
Fixed in 76a7805e1f0d794946ab7d8c6d60454bd3f244a5 (less-618).
