### ISSUE TITLE
Output to be available for display  in its whole width

### ISSUE THREAD

**Issue by Ricky-Tigg** [gwsw/less#32]
OS: Fedora; Component: less.x86_64 551-2.fc31 @anaconda

_Entrancement request_ – **output** to be available for display. in its **whole** width. 

Command involved` lsblk -O | less`. Tested under a **15.60-inched** display, under **Gnome standard v.3.34.1** on **Wayland**, under gnome-terminal.x86_64 3.34.2  Snapshots took while terminal window was in full screen mode, which is equivalent to
```
$ stty size
45 158
```
Default output displayed, which is according to **vertical axis**.

![command_output_lsblk_-O_1](https://user-images.githubusercontent.com/26058215/68580012-2583b380-047e-11ea-9458-e3fb07dcd0e2.png)

Output displayed according to **horizontal axis** –by invoking <kbd>_right-arrow_</kbd> key–. The beginning of the ouput is not available for displaying; here for instance the content listed in the _NAME_ column.

![command_output_lsblk_-O_2](https://user-images.githubusercontent.com/26058215/68580046-32a0a280-047e-11ea-8514-113b7fb9b6ff.png)

**Comment by gwsw** [comment]
I'm sorry, I don't quite understand this. Obviously if the screen is 158 columns wide and the text is wider than that, then the whole line can't be displayed without wrapping, which your first screenshot shows. This screenshot also shows that the entire text is being displayed. When you press right-arrow you are asking to see something different -- what exactly do you expect to see after you press right-arrow?

**Comment by Ricky-Tigg** [comment]
Hey. _A whole line of the output not be displayed without wrapping_; That presently was as a **requirement** in order to reproduce present issue, **not an issue by itself**. As well **size** values supplied by me, they were there only to show under what circumstance on my system that requirement was met, thus those values neither were not meant to be an issue. At last, even if a test would be conducted by relying on an endless-sized screen, _gnome-terminal_ would display outputs according to its internal restrictions, which  _columns x rows_ respective  values are **511 x 511**.

Relevance of first snapshot presence came from that it contained the beginning of the output; it had to be there for a unique purpose to confirm that the object of issue was pertinent.  Here is what was we knew we could expect a view whose beginning would have matched output resulting from` lsblk -o name` while switching from default view to a view according to horizontal axis..

![output|lsblk_-o_name_2](https://user-images.githubusercontent.com/26058215/68663697-d1450600-0547-11ea-8159-0d4e1a64e34b.png)

Further testing brought a new negative element that grows severity of depicted issue. Along with each click onto <kbd>_left-arrow_</kbd> and <kbd>_right-arrow_</kbd> keys, the tool does not display a new segment of the output part of the whole output. 

Here is an illustration of the next segment, –invoked by <kbd>_right-arrow_</kbd>– while previous segment was  the one illustrated in second snapshot:

![output|lsblk_-o_name_1](https://user-images.githubusercontent.com/26058215/68663765-e7eb5d00-0547-11ea-8dce-b30c6cd8cae6.png)

**Comment by gwsw** [comment]
I'm sorry, I still cannot understand what you are asking for. The --shift option specifies how many characters the output is shifted when you press the right-arrow or left-arrow key. Does that help your issue? If not, perhaps you could construct a screenshot of how you would like the output to appear after you press the arrow key, rather than trying to explain it in words.

**Comment by Ricky-Tigg** [comment]
You should probably have by now understood that those commands should had be run in a terminal emulator and they required few knowledge if not at al,lin order to interpret correctly their outputs.. Undoubtedly you would have had few difficulties whit those outputs; I won't guess where, why, and how you all alone managed to achieve that state.

No doubt you shall keep on acting that way as you would not even know something related to the behaviour of the tool you seem to be maintainer, keeping on pretending not to understand a mysterious unknown, which is to indicate you did not indeed understand that a behaviour supported by evidences is wrong when it does fail in its task –to produce visually all parts of an output, as you had perfectly understood.
