### ISSUE TITLE
less as presentation application

### ISSUE THREAD

**Issue by senyai** [gwsw/less#325]
Hi!

I'm using `less` as a way to represent slides (colorful text files). `less *`. Everything is working fine. Recently I got a bit of laugh from my audience that I used '<shift>;n' to go to next slide. And I agree that is too awkward of a shortcut to hit. I think a one key command should be added to switch between files. Is it possible? Are there any keys available? I like "[" and"]", but they are in use.

**Comment by gwsw** [comment]
You can define any key you like to be an alias for the ```:n``` command by using a lesskey file. See the documentation in the ```lesskey``` man page. If you want to use ```]``` and ```[``` for this purpose, put these two lines in your lesskey file:
```
] next-file
[ prev-file
```

**Comment by senyai** [comment]
Hooray! Thanks you. I'm blind. Nevertheless, KEY BINDINGS section of the manual can be improved. It needs an example to catch the eye of a reader. And the manual should explicitly say that `lesskey` manual page 'describes the format of the lesskey source file', not just 'See the lesskey manual page for more details.'. And ideally at the start of the paragraph, not at the end. I might be wrong. I don't mind you closing this issue.

**Comment by gwsw** [comment]
Made some small adjustments to the man page in d4b7ac0117587a0b276855880616ee2b8d285309.
