### ISSUE TITLE
 Improve diagnostics for input preprocessor failures

### ISSUE THREAD

**Issue by eggert** [gwsw/less#327]
This is a followup to issue #258.

After using less 622 with an improved `gzip` and `zless`, I found a couple of opportunities for improving `less`'s new diagnostic on POSIX-compatible systems:

1. Improve the quality of the diagnostic message, by distinguishing between ordinary exit with nonzero status and termination due to a signal, and by printing the signal name rather than a hex number representing it.
2. Don't report a failure merely because the input preprocessor died due to a `SIGPIPE` signal after `less` closed the pipe without reading EOF. This is normal and expected when the `less` user types 'q'.

I plan to hack on this a bit and propose further improvements with a pull request.

**Comment by gwsw** [comment]
Committed in ccf09b61a3d7d5f1e6e5c6d4ae16a870f1e3fd69.

**Comment by leahneukirchen** [comment]
I don't think this ever worked correctly, because popen spawns a shell around the inner process, and the shell returns the exit status of the last command (since `exec` is not used in the popen command line). Thus a SIGPIPE degrades to a plain command returning status 141, and an error message is reported (as I can reproduce on Linux with zless for less v623 up to v694).

**Comment by leahneukirchen** [comment]
After checking, `bash`, `mksh`, `zsh` will automatically `exec` if there's just a single command, however other shells like `dash` (my `/bin/sh`) wont.

**Comment by richfelker** [comment]
Unless there's some hidden allowance I'm missing, what bash is doing is non-conforming. They probably think it's ok by some as-if rule, but as we can see here, the wrong transformation they're making is altering the exit status the parent which invoked the shell expects to get.

**Comment by richfelker** [comment]
If the exec behavior is what's wanted here, adding an explicit `exec` to the start of the popen command string should achieve that portably.

**Comment by gwsw** [comment]
> (as I can reproduce on Linux with zless for less v623 up to v694).

@leahneukirchen can you provide instructions for how to reproduce this?

**Comment by richfelker** [comment]
> can you provide instructions for how to reproduce this?

AIUI you just need `/bin/sh` to be a shell that conforms to POSIX, not bash or something like that. dash or busybox ash will do.

**Comment by gwsw** [comment]
I made /bin/sh be a link to dash, then ran ```SHELL=dash zless <file.gz``` where file.gz is a gzipped 200,000 line ( 4 MB) text file. After it displayed the first screen, I quit less, and I did not see any error message. So I guess I'm not understanding the error case.

**Comment by leahneukirchen** [comment]
Using my [extrace](https://github.com/leahneukirchen/extrace) I see this when I run:

```
zless .irssi/logs/archive/freenode-\#archlinux.log.gz
```

```
      8898+ /bin/sh /usr/bin/zless '.irssi/logs/archive/freenode-#archlinux.log.gz'
        8899+ less -V
        8899- less exited status=0 time=0.001s
      8898- /bin/sh execed time=0.003s
      8898+ less --show-preproc-error '.irssi/logs/archive/freenode-#archlinux.log.gz'
        8900+ sh -c -- '/bin/zsh -c gzip\ -cdfq\ --\ .irssi/logs/archive/freenode-\\\#archlinux.log.gz'
          8902+ /bin/zsh -c 'gzip -cdfq -- .irssi/logs/archive/freenode-\#archlinux.log.gz'
          8902- /bin/zsh execed time=0.006s
          8902+ gzip -cdfq -- '.irssi/logs/archive/freenode-#archlinux.log.gz'
          8902- gzip exited signal=SIGPIPE time=3.026s
        8900- sh exited status=141 time=3.034s
      8898- less exited status=0 time=4.365s
```

We see that gzip exits on SIGPIPE, but sh exits on status code 141.

(Aha, `zless <bigfile.gz` works because it doesn't pass `--show-preproc-error`, but `zless bigfile.gz` shows the error.)

I think the code should simply check for status == 128 + SIGPIPE as well and ignore that.

**Comment by eggert** [comment]
> Unless there's some hidden allowance I'm missing, what bash is doing is non-conforming.

First, whether `bash`, `mksh`, etc. are "non-conforming" doesn't matter all that much as far as the `less` problem is concerned. `less` should work with the shells that we actually have, not just the shells that we'd like to have.

Second, it's unlikely that POSIX intended to ban last command optimization, or whatever you want to call it (it's like tail call optimization in ordinary programming languages). If this issue were brought up to the POSIX standardizers they should (and surely would) say that LCO is allowed. So let's not stand on POSIX-lawyering here.

So yes, let's have `less` check for both true SIGPIPE exit, status == 128 + SIGPIPE.

**Comment by gwsw** [comment]
Well, I'm still not able to reproduce this. I tried ```SHELL=dash zless file.gz``` and I tried 
```SHELL=dash LESSOPEN="||-dash -c 'gzip -cdfq -- %s'" less --show-preproc-error file.gz ``` 
and I still don't see any error message when I quit.

Can someone able to reproduce the problem check whether this patch fixes the issue?
```
index cb2960a5..6d63c4d4 100644
--- a/edit.c
+++ b/edit.c
@@ -290,7 +290,11 @@ static void close_pipe(FILE *pipefd)
 	if (WIFEXITED(status))
 	{
 		int s = WEXITSTATUS(status);
-		if (s != 0)
+		if (s != 0
+#ifdef SIGPIPE
+		    && s != SIGPIPE + 0x80
+#endif
+		   )
 		{
 			parg.p_int = s;
 			error("Input preprocessor failed (status %d)", &parg);
```

**Comment by richfelker** [comment]
> > Unless there's some hidden allowance I'm missing, what bash is doing is non-conforming.
> 
> First, whether `bash`, `mksh`, etc. are "non-conforming" doesn't matter all that much as far as the `less` problem is concerned. `less` should work with the shells that we actually have, not just the shells that we'd like to have.

I'm not saying that you shouldn't work with bash, but that you shouldn't assume something bash is doing just because it's what most people might be using. Regardless of whether the bash behavior is outright wrong or just not something you can portably assume.

> Second, it's unlikely that POSIX intended to ban last command optimization, or whatever you want to call it (it's like tail call optimization in ordinary programming languages). If this issue were brought up to the POSIX standardizers they should (and surely would) say that LCO is allowed. So let's not stand on POSIX-lawyering here.

It clearly is the intent that the application that invoked a shell script can observe the exit status that the shell script is specified to have according to the rules of the shell command language. Bash is trying to go by an "as-if rule" here and didn't think things through to realize that the behavior is not actually as if it had invoked the process like it was specified to. But this is way off-topic.

> So yes, let's have `less` check for both true SIGPIPE exit, status == 128 + SIGPIPE.

This is not a portable assumption either. The exit status the shell produces when the last command exited with a signal is not specified to be `128+signo`, just something >= 128.

There are two possible right things to do here. Since less actually *wants* the bash behavior of getting the terminated-by-signal status, the best solution would be to actually use the exec command to invoke the program as part of the command passed to `popen`, so that you can be sure there's no shell in between.

If there's some reason you can't do that, a reasonable thing to do would be treating all exit codes >=128 as something that's not supposed to be reported as an error.

**Comment by leahneukirchen** [comment]
@gwsw that fixes it for me.

**Comment by richfelker** [comment]
> that fixes it for me.

It depends on a particular choice of how the shell maps signals to exit status though. One which is fairly traditional but not specified. It really would be better to fix this right.

**Comment by gwsw** [comment]
>Since less actually wants the bash behavior of getting the terminated-by-signal status, the best solution would be to actually use the exec command to invoke the program as part of the command passed to popen, so that you can be sure there's no shell in between.

Less actually deliberately invokes the LESSOPEN command via "```$SHELL -c command```", if the SHELL environment variable is set. I believe this was to ensure that any shell metacharacters and variable invocations will get expanded. So I don't think setting LESSOPEN to an ```exec``` command will help, nor would less be able to use an exec command internally without losing the ability for the command to expand shell metacharacters.

>If there's some reason you can't do that, a reasonable thing to do would be treating all exit codes >=128 as something that's not supposed to be reported as an error.

I'm fine with that if there is agreement that this is a reasonable solution.

**Comment by eggert** [comment]
I created a [pull request](https://github.com/gwsw/less/pull/753) which I hope does the right thing. I am running Fedora, which does not have the problem since popen uses Bash, so I haven't tested this in the environment that illustrates the bug.

A few things, which are reflected in this pull request:

1. As gwsw writes, `exec` is not the way to go here.
2. The `bash`/`mksh`/etc. approach is more reliable for `less`, because `less` can see unambiguously that the subsidiary process failed due to `SIGPIPE`. The problem with the `dash` approach is that exit status 141 (or whatever) does not mean that the subcommand failed due to a signal; it could be that the subcommand merely exited with status 141.
3. Although POSIX does not specify how the shell should turn signals into exit statuses greater than 128, as I understand it, in practice every shell that lacks last command optimization adds 128 to the signal number for shell's own exit status, as this is decades-long historical practice. (Even ksh93, which adds 256 for $? in an attempt to distinguish ordinary exit from signal termination, adds only 128 for its own exit status.) So let's assume this longstanding practice for now. If some shell ever departs from longstanding practice (but why would it?) we can deal with it then.

**Comment by gwsw** [comment]
>I am running Fedora, which does not have the problem since popen uses Bash

Ah, I'm running Fedora too, so I guess that's why I can't reproduce the problem. @leahneukirchen can you confirm that eggert's PR fixes the problem for you?

**Comment by leahneukirchen** [comment]
PR works on Void Linux.

**Comment by gwsw** [comment]
Great, thanks. PR Integrated into master as of e311f0091413a187e6771e6d17e880930770b67d.
