### ISSUE TITLE
less forgets about ansi color codes after newline

### ISSUE THREAD

**Issue by RomanValov** [gwsw/less#333]
Hi there

last year we have discussed similar issue ( #276 ) and I appreciate your time spent to fix that issue

Here is a similar one. However I wasn't able to find any version of `less` handling this one correctly.
I've looked among latest master, less 590 (ubuntu 22.04), less 551 (ubuntu 20.04) and less 487 (ubuntu 18.04)

It seems less forgets about ansi color codes after newline, however shell keep color info until it will be explicitly reset.

![Screenshot from 2023-02-02 00-05-46](https://user-images.githubusercontent.com/5928128/216127361-b23bd2bd-e9c8-4a24-98c3-8ffb0697068b.png)

Example file is attached:

[opts.log](https://github.com/gwsw/less/files/10560077/opts.log)

**Comment by gwsw** [comment]
See #99 for an explanation.
