### ISSUE TITLE
Can you bind toggling line numbers such that you don't have to hit RETURN after?

### ISSUE THREAD

**Issue by Jackenmen** [gwsw/less#334]
I tried various combinations of putting `\r` or `\n` so that I don't have to hit Enter but nothing seems to work.

This is the base `.lesskey` I have that results in me being prompted with "Constantly display line numbers  (press RETURN)":
```
#command
l toggle-option N
```

Appending `\n` without a space between causes less to simply move the line down *after* I accept the prompt, it doesn't cause the prompt to get auto-accepted. If I put a space between, it instead moves a whole page down. I also tried some combinations by doing something like:
```
#command
l noaction -N\n
```
but that seems to work the same as `toggle-option`.

**Comment by gwsw** [comment]
You can add a ctrl-P before the "N" to suppress the confirmation message. This is documented under the "-" command in the man page. It can be either a literal ctrl-P character or the two-character sequence "^P":
```
l toggle-option ^PN
```

**Comment by Jackenmen** [comment]
That works, thanks!
