### ISSUE TITLE
No new official release published in http://greenwoodsoftware.com/less/

### ISSUE THREAD

**Issue by sshedi** [gwsw/less#336]
Hi @gwsw,

Is there any reason for not publishing new releases at http://greenwoodsoftware.com/less/?
Please let me know if we need to consume source from github from now onward.

**Comment by gwsw** [comment]
Production and beta releases are published to greenwoodsoftware.com/less. That is normally where you should be getting releases. Versions on github are development stages and generally should not be used, unless you are working on development of less itself or testing specific bug fixes. Right now less-608 is the production release and there is no current beta release.

**Comment by sshedi** [comment]
Thanks for prompt response.

I think it would be nice if a new release is done when security fixes are done.

For example:
https://www.openwall.com/lists/oss-security/2023/02/07/7

Any ETA or roadmap details on next release? Thanks.

**Comment by gwsw** [comment]
I expect to release a beta within the next week or so, if no unexpected issues arise.

**Comment by sshedi** [comment]
Thanks for the info. Closing this issue.
