### ISSUE TITLE
Command line option +&pattern does not automatically executed at the start of command

### ISSUE THREAD

**Issue by telychko** [gwsw/less#339]
PREREQUISITES
$ less -V
less 608 (PCRE2 regular expressions)
Copyright (C) 1984-2022  Mark Nudelman

STEPS TO REPRODUCE
1. Execute
`$ less '+&sda' /etc/fstab`

ACTUAL RESULT
You will see "&/sda" at the bottom of the screen, and you should hit enter key to see the result.

EXPECTED RESULT
A filtered output just after the command is executed. An expected work is like as `less '+/sda' /etc/fstab` works (search pattern).

**Comment by gwsw** [comment]
I agree that it's better to not require the Enter input. This is implemented in 5115835d8365ec0b8b119d273a0cf4ca3164594c (less-628).
