### ISSUE TITLE
Less --quit-if-one-screen auto quits when terminal size is expanded once less is already running

### ISSUE THREAD

**Issue by unphased** [gwsw/less#340]
### Problem Summary
- If content doesn't fit in the screen initially, `less` will start, for which it naturally uses alternate screen mode.
- User expands the terminal to focus on reading the content being presented.
- Once less determines that the content does now fit in one screen per new terminal dimensions, `less` *immediately* quits at this point. 

Due to use of alternate screen, not even whatever portion was visible at the time of the terminal expansion remains visible. Content being viewed is gone with the same level of disruption as if less had segfaulted, but there is actually even more disruption, because in this case the terminal is left stuck in alternate mode and whatever portion of the buffer that happened to be visible before the event **would still be visible**! In this scenario I describe, alternate screen mode and delayed quit-if-one-screen behavior conspire to evoke great consternation in the user.

After some consideration, I believe this is a design flaw in the `--quit-if-one-screen` feature. In particular if we assume a static terminal size, it's not much of a problem for the "if-one-screen" logic to be running constantly in response to events rather than (as I would really hope...) only once at startup.

It is my opinion that if `less` has opened up some content for me to consume using alternate screen, under no circumstances should it then be allowed to auto-quit without being commanded to do so. 

In this particular case the user intent in expanding the terminal is to focus on the content under review. It is therefore even more problematic than at any previous point in time to have the program automatically exit.  

### Proposed path forward: 
- Review whether it is possible to change the if-one-screen check logic to make sure it only runs one time at program startup

**Comment by gwsw** [comment]
What version of less are you using? I believe that this problem was fixed almost two years ago, in less-587.

**Comment by unphased** [comment]
Great, thank you. 551 is what came with my Ubuntu 20.04. Sounds good!
