### ISSUE TITLE
Example of making notes about a set of files

### ISSUE THREAD

**Issue by jidanni** [gwsw/less#346]
Here is an example of a use for less, that you might want to add to the man page:

The secretary is browsing all the files in the directory,
and is to note down which files need further investigation.
The boss needs a list of the suspect filenames. OK, here we go:
```
$ less -KiRXQe *
```
now page through the files with SPACEBAR,
and then when we are looking at a suspect file, do
```
!echo "%" >> ../suspects : need more nurfflehauser details. norfsburg will like this
```
Above, the colon (:) is just so we know where to start typing any notes we
might want to make. No shell metachars like apostrophe allowed though,
unless escaped with backslash.
OK, on any subsequent files we want to make a note about, do:
```
!^P
```
(not !!,) and then update any words we want to say.

P.S., it seems we will have to get used to !^P,
as e.g., it seems lesskey can only bind single commands to a key,
so won't be of any use in this example.

Hmm, maybe instead of colon, use `\#`, which should produce nice shell comments!

Note I was paging through a set of one page long documents.
That way I didn't need to hit ":n" to get to the next document,
that's why things seemed so easy.

**Comment by gwsw** [comment]
This seems to be a very specific use case. I don't think it would add anything generally useful to the man page.

**Comment by jidanni** [comment]
Well okay, then perhaps have some other example of some usage of that symbol.

**Comment by gwsw** [comment]
Which symbol are you referring to?

**Comment by jidanni** [comment]
%

**Comment by gwsw** [comment]
I don't think anything more needs to be done here. The % character is already documented in the description of the ! command.
