### ISSUE TITLE
Mention all the rest of the man pages in each's SEE ALSO

### ISSUE THREAD

**Issue by jidanni** [gwsw/less#347]
Simply looking at the SEE ALSO parts of the man pages,
one would not learn of the complete set:
```
$ dlocate -man less
1 less
1 lessecho
1 lessfile
1 lesskey
1 lesspipe
```

**Comment by gwsw** [comment]
less, lessecho and lesskey are the only programs included with the official release of less. Lesspipe and lessfile are probably things added by your system distributor.

**Comment by jidanni** [comment]
I see. OK. Pretend I didn't mention the stowaways.
