### ISSUE TITLE
Add at least one example to the lessecho man page

### ISSUE THREAD

**Issue by jidanni** [gwsw/less#348]
Add at least one example to the lessecho man page.
There may be examples, but they aren't on the man page itself.
```
$ lessecho abc
abc
```
OK, but that is the same as
```
$ echo abc
abc
```
so please add a different example.

**Comment by gwsw** [comment]
lessecho isn't intended to be used by people, only by less itself. I'm not sure it even needs a man page, but I don't think the man page needs instructions for use by humans.
