### ISSUE TITLE
Lesstest fail

### ISSUE THREAD

**Issue by hongjinghao** [gwsw/less#349]
My less's version is 608. When I make check, this error came up.

FAIL colorbars on cmd #137 (c 63)
FAIL colorbars (137 steps)
ERR  status 256 from /root/rpmbuild/BUILD/less-608/lesstest/lesstest  -e -s '/root/rpmbuild/BUILD/less-608/lesstest/lt_screen' -t '/root/rpmbuild/BUILD/less-608/lesstest/lt/colorbars.lt' '/root/rpmbuild/BUILD/less-608/less'

**Comment by gwsw** [comment]
lesstest was not part of the less-608 release. I guess you copied it from a later build back into your 608 release?

Which regex library are you using? Some versions of the POSIX regex have a bug where "." matches a byte instead of a character, which can cause lesstest to fail like this. I use PCRE or PCRE2 when running lesstest.

**Comment by hongjinghao** [comment]
The test case does not involve regular expression matching.
It reads the colorbar file and pipelines the content, comparing the original file content to the transferred content. The content before and after is inconsistent. I don't see why it would fail

**Comment by hongjinghao** [comment]
My test cases for this version of Lees seem to have nothing to do with regular matching.
It reads the contents of the colorbar file and then pipes it. The content before and after the transmission is compared. There is a possibility that the content is inconsistent and the transmission fails.

**Comment by gwsw** [comment]
I think the issue here is that there was a bug in less-608 that was fixed later when the colorbars test was created (possibly #276, but I'd need to do more research to determine this for sure). Lesstest is doing its job correctly, in finding and reporting a bug in less.

**Comment by hongjinghao** [comment]
> I think the issue here is that there was a bug in less-608 that was fixed later when the colorbars test was created (possibly #276, but I'd need to do more research to determine this for sure). Lesstest is doing its job correctly, in finding and reporting a bug in less.

Do I need to offer anything?

**Comment by hongjinghao** [comment]
I think this may not be the problem with colorbars. I checked a few more times and github reported an error.
![image](https://user-images.githubusercontent.com/67907797/225534962-94bfdb04-ef06-4274-b415-3d5ae8ba8991.png)

**Comment by gwsw** [comment]
Can you try using the latest beta (less-629)? I don't think it's useful to try to incrementally patch less-608 with the relevant fixes that are already in the latest version.

**Comment by gwsw** [comment]
BTW, the low-probability intermittent failure is probably fixed in 8ce22cf61c9f04a42f80bd174a9e5ef7fab439c5, but again, I don't think it's useful to gradually port fixes one at a time back into less-608.
