### ISSUE TITLE
v command fails

### ISSUE THREAD

**Issue by polluks** [gwsw/less#351]
```
$ less README # press v
zsh:1: command not found: README
$ echo $EDITOR
vi
$ uname -a
Darwin mbp 22.4.0 Darwin Kernel Version 22.4.0: Mon Mar  6 22:31:41 PST 2023; root:xnu-8796.101.5~5/RELEASE_ARM64_T8103 arm64

**Comment by gwsw** [comment]
I can't reproduce this. I've tried on a MacOS (Darwin) system, with SHELL set to "zsh" and EDITOR set to "vi", but the v command works fine for me. Do you have the "VISUAL" environment variable set? Which version of less is failing? Does it work on earlier versions?

**Comment by polluks** [comment]
Well, I tried a clean system and Apple's 581.2 worked. So my daily system is somehow broken.

**Comment by gwsw** [comment]
Hm, that may suggest a problem with your lesskey file. Since sudo changes your HOME variable, you'd probably be using a different lesskey file when you use sudo.

**Comment by polluks** [comment]
My LESSEDIT was "%e %g" and lowercase e is undefined.
