### ISSUE TITLE
less -R displays ^O when a color escape sequence contains Ctrl-O as defined by sgr0 for some terminfos 

### ISSUE THREAD

**Issue by ericvw** [gwsw/less#357]
I created https://github.com/tmux/tmux/issues/3511, which provides full details and context of the behavior I observed when using `less -R` with `TERM=tmux-256color` that defines `sgr0` as `\E[m\017`.

In short, when a program emits `\E[m\017` to reset attributes, `less -R` will render output with `^0` (from `\017`).

Is it possible to enhance `-R` to strip ^O from its output?

**Comment by gwsw** [comment]
The -R option is intended to handle standard SGR sequences, which often appear as formatting in text files. It is not intended to handle terminal-specific escape sequences, which normally wouldn't be found in text files, but would only be used by a program sending output directly to a terminal. I read the tmux issue, but I don't really understand why fish_delta is sending terminal-specific sequences through less. It could control the terminal itself, or it could send text output through less, but it doesn't make sense to me for a program to be doing both.

**Comment by ericvw** [comment]
Thank you for the response! I'll close this out since the intent is to handle standard SGR sequences that appear in text files, not terminal-specific escape sequences.
