### ISSUE TITLE
Output garbled when using less -r and horizontally splitting

### ISSUE THREAD

**Issue by sumodm** [gwsw/less#359]
When doing less -r using the following [file](https://pastebin.com/raw/06U5JEeD), it works alright when terminal is in full screen mode.

Correct
![Screenshot from 2023-04-12 12-28-17](https://user-images.githubusercontent.com/1060369/231379484-4d0c2d16-105d-41a5-a67d-531053f30902.png)

But when I open it in vertical mode by splitting tmux window or resizing the terminal, it garbles the output

Garbled 1: Tmux Window split
![Screenshot from 2023-04-12 12-28-06](https://user-images.githubusercontent.com/1060369/231379265-0dff6321-2469-4a3d-ae53-41a6b16573ac.png)

Wrong2: Terminal resized
![Screenshot from 2023-04-12 12-29-51](https://user-images.githubusercontent.com/1060369/231379514-b0e2b1ce-2e61-40fc-8b2b-91db8f19a89a.png)

Unable to narrow down the sample file to the simplest example, as the error disappears (this is output from OpenAI's [sample code](https://github.com/openai/openai-cookbook/blob/12e5e3ec69fc762f3e3e611948aa0f8bf6867893/examples/Unit_test_writing_using_a_multi-step_prompt.ipynb))

**Comment by gwsw** [comment]
Yes, this is not unexpected. As the man page says about the ```-r``` option:

> Warning: when the -r option is used, less cannot keep track of the  actual appearance of the screen (since this depends on how  the  screen  responds  to  each type of control character).  Thus, various display problems may result, such as long lines being split in the wrong place.
>              USE OF THE -r OPTION IS NOT RECOMMENDED.
