### ISSUE TITLE
less uses pre-C89 function definitions

### ISSUE THREAD

**Issue by bsdjhb** [gwsw/less#361]
LLVM 15 complains if about pre-C89 (K&R) function definitions that will be invalid in a future version of C.  It probably makes sense to move to C89 function definitions if possible.  Downstream in FreeBSD we are just going to neuter the warning for now.

**Comment by gwsw** [comment]
Less was changed to use C89 definitions in less-618. Are you seeing this problem with a release later than that?

**Comment by bsdjhb** [comment]
My apologies, I should have checked more thoroughly.  FreeBSD currently has less-608, so yes it's an older release.
