### ISSUE TITLE
The  prompt  expansion  features for shell-command

### ISSUE THREAD

**Issue by telychko** [gwsw/less#362]
Hi everyone.

Less has a nice feature that expands prompt for LESSEDIT environment variable.

LESSEDIT has the following default value `%E ?lm+%lm. %g`. It expands to editor, line number and file name.

Is it possible to make such expansion for shell commands?

For example, you can execute following in your less prompt, and it will print a line number.

`!echo %lm`

**Comment by gwsw** [comment]
In the current beta release (less-632), the # command does this. (Requested in #330.)

**Comment by telychko** [comment]
Thank you. That's what I am asked about. You are doing cool things!
