### ISSUE TITLE
Allow Unicode Private Use Area code points for prompt

### ISSUE THREAD

**Issue by mutax** [gwsw/less#363]
I am using unicode code points from the range U+E000..U+F8FF in my prompt to make use of characters in the powerline fonts.
Unfortunately they are considered unassigned and thus escaped instead of sent to the terminal.

When removing the range in ubin.uni I can use these characters in my prompt -- and they are also shown when paging through a file.

It would be great if these code points could be allowed at least for the prompt.

**Comment by gwsw** [comment]
What version of less are you using? In the current beta release (less-632) you can use the LESSUTFCHARDEF environment variable to treat Private Use characters as printable.
