### ISSUE TITLE
less -r or less -R doesn't seem work any more

### ISSUE THREAD

**Issue by aki-k** [gwsw/less#364]
When I read a text file with some special characters with "less -r magnitude.nfo", the characters are shown on the screen like this:
```
<B2><DC>   <DF><DB>ܰ<B0>    <B0><B0><B2><FE><FE><FE><FE><B2><B0>     <B0><B2> <B0><B1><B0>  <B1><B0>
<B2><B1><DC><DF>  <B1>     <B1>   <B0><B0><B1>   ߱<B0>        <B0> <B0><B0><B1><B2><B2>
<DF>ܲ<DC>   ߲<B2><DC><DC><FE>  <B0>            <DF>߲<B1><B0>  <B0><B2><B0> <B2><B2><DD>   <B0>     <DC>
<B0><B0><B2><DD>     <B0><B0><B0> <B0>    <B0><B0><B1><B1><B2><B2><DB>
  <DF>ܲ<DC>  ܲ<DF>   ܱ<B2><B2><B2><B2><DF><DF><DF> <FE><FE> <DC> <B1><B1><B0> <DF>߲<B2><B1> <B2><B2><DD>       ܲ
<B0><B1><B2><DB>      <B1><B0><B0><B0><B0><B0><B0><B0><B1><B1><B1><B1><B1><B2><DD>
<B2><DC>  <DF><DB>۲߱<B0><DC>۲<B0><B2><DB>۲        ܱ<B2><B1><DC><DC>   ܲ <B2><DB><DD>ܱ<B1><B2><DC> <DE>
<DB><DD>    <B0><B1><B2><DB><DC><DC>    ߲<B1><B1><B1><B2><B2><B2><B2><B2><B2><B2><DF>
޲<B2><DC>  <DF>  <B0><B2>۲<DD> <DE><DB><DB>۲<B2><DC><DC>  ܲ<B2><B2>߰ <DE><DB><DB><DC> <DF> <B2><DB>
<DB>߲<B2><B2><DF> <B2><DB><DD>     <B0><B0><B1><B2><DF>߲<B2><DC><DC>  <DF><DF><DF><DF><DF><DF><DF>
޲<DB><DB><DB><DC>  <B0><B2><DB><DB><DB>  <DB><DB>۲<DE><DB>۲߲<B2><DB><DF> <B0><B1><B0> <B2><B2><DB>
<DB><DC> <DB><DB>۲<DC><DC><DB><DB><DB><DB><DB><DB>۲<B2><DF>  <B0><B0><B1><B0>   <DF><DB><DB><DB><DC> ޲
<B2><DB>۲<B1><B0><B0>
<DE><DB>۲߲<B2><DC><DB>۲<DB><DB> <DE><DB>۲<B0><DE><DB><DB><DD><DE><DB><DB><DD>  <B2><B2><B1> <B2>۲ ߲
<DB><DB>۱<DB><DB>ܰ<B2><DB>۲<DC><DB><DD>  <DC>ܰ<B1><B2><B1>   ޲<DB><DB><DD> ߲<DB><DD>
<DE><DB>۲  ߲<DF> <B2><B2><DB> <DB>۲<B1> <DE><DB>۲<B2>۲   ۲<B2> <DB>۲<DD> <DE><DB><DB>۰<DB>۲ <B1><DB>
<DB><DB>۲   <DE><DB>۰<B2><B2><DD>  <B0><DB><DB>۲<DC><DC><DC><DB><DB><DC>
<DE><DB>۲      <B2><B2><B2><B1><B2><B2><B2><DF>߲<B2>۲<B2>۲   <DB>۲ <DB>۲<DD>  <DB><DB><DB> <DB>۲ <B0>
<DB><DB><DB>۲    <B2><DB><DD>޲<B2>  <DE><DB><DB><DB><DD><DB><DB><DB><DF>   <B0>
<DE><DB>۲     ޲<B1><B2><B2><B2>߱ ܲ<DB>۲<DE>۲<DD>  <DB>۲ <DB>۲<DD>  <B2><DB><DB><DD><DB>۲ <B0><DB><DB>޲
<B2><DD>  ޲<B2><DB><DB><DB><DD> <B0><B2><DB><DB><DB><DB><DB><DB><DB>    <B0><B0>
<DE><DB>۲    ܲ<B1><B1><B2><B1><DF> <B0>   ߲<B2><DC><DF><DB><DB><DC><DC><DB>۲<DC>۲<B2><DF>  <B1><B2>
<DB>۲<B2><B1> <B1>۲ ߲<B2><DC>ܲ<B2><B2><B2>۲ ܲ<DB><DB><DB>߲<DB><DB><DB><DD>   <B0><B1>
<DE><DB>۲<B0>  <DF><DF>߰<B1><B1>         <DF><DF><DF>  <DF>߲<B2><DB><DD><DF>߱   <B0><B2><B2><B2><B1>
<B2><B0> <B2><B2><DF> <B0>  <DF><DF><DF>߰<B1><B2>ܲ<B2><DF><DF>  <DF>߲<B2><DB><DB>  <B0><B0><B2>
<DE>۲<B2><B1><B0> <B0><B0>  <B0>   <DC><DC><DC><DB><DB><DB><DB><DB><DC><DC><DC><DC>  ߲<DB><DD>  <B0> 
<B0><B1><B0> <B1><B0><DC><DF>  ܲ<DC>    ܲ<B2><DF><DF>         ߲<B2><B1><B0><B0><B1><B2>
޲<B2><B1><B1><B1><B0>      ܲ<DB>۲<B2><B2><DF><DF><DF><DF><DF><DF><DF>߲<DB><DC><DB><DB>        <B0><B0>
<B1><B1><B0>     <DF>   <DC>߱<B0>      <B0>       <B1><B1><B0><B1><B1><B2>
޲<B1><B1><B1><B0>  <B0> <B0><B0><B1><B2><B2><DB><DF>              <DF>߲<DC>     <B0><B1><B1><B2><B2>
<B1><B0><B0> <B0>   <B0><B2><DD> <B0>       <B1>        <B0><B0><B1><B2><B2>
ޱ<B1><B0>         <B2><B2>  ++S! ++b5! ++Ix  <DC><DF><FE>ܰ<B1><B1><B2><B2><B2><DB><DF>      <B0><B1>
<B2>  <B0>  <B0><B0><B1><B0><B1><B2><B1><B0><B1><B0><B0><B0>  <B0><B1><B1><B2><DB>
ޱ<B0>     <B0><B0>    <DF><DC>                  <DE><DD>   <DF><DF><DF>߱        <B0><B1><B1>         
<B1>       <B0><B1><B2><B2><DB><DD>
<B1><B0>    <B0><B1><B0>       <DF>  <DC>             <DC><DF>        <B0>         <B0><B0>  <B0>   
<B0>      ܱ<B2><DB><DB><DF>
<B0>    <B0><B1><B2><B1><B0> <B0>           <DF>  <FE><FE>  <DF>                        <B0>        
```
Instead, the text file should (at least) resemble this picture of the same text file as shown with the msdos characters:

[magnitude.nfo](https://i.imgur.com/n2tJN7J.png)

I'm not sure what has changed but some years ago I was able to use less -r or less -R to view that kind of text file
without showing those hex codes.

I uploaded the magnitude.nfo text file to [https://0x0.st/HKff.txt](https://0x0.st/HKff.txt)

**Comment by polluks** [comment]
Pay attention
`LESSCHARSET=utf-8 less HKff.txt` fails
`LESSCHARSET=latin1 less HKff.txt` works

**Comment by aki-k** [comment]
Thanks that works. When did that change in less? Never seen that variable.

**Comment by polluks** [comment]
The manual says
> If neither LESSCHARSET nor LESSCHARDEF is set, but any of the strings "UTF-8", "UTF8", "utf-8" or "utf8" is found in the LC_ALL, LC_CTYPE or LANG environment variables, then the default character set is utf-8.

**Comment by aki-k** [comment]
Actually now I found out that if I open the file in vim, it displays the characters as I remembered from years back.

**Comment by gwsw** [comment]
I don't think anything in this area has changed in many years, but it's possible something has changed in your environment variables. As @polluks noted, if certain variables contain "utf8" or similar strings, the character set is utf-8. Otherwise the charset is ASCII. The only way to get a latin1 charset is to explicitly set LESSCHARSET to "latin1". Perhaps that was previously set in your environment without your knowledge.

Another issue is I question the details of the original report. If the -R flag is used, hex codes may (depending on the charset) be displayed for non-ASCII chars as noted in the OP. But if -r is used, hex codes are never displayed, and I'm pretty sure this has always been the case. So I think there may be some confusion between -r and -R in the original report.

**Comment by aki-k** [comment]
@gwsw Do you know how vim is able to open the file in a yet different mode?

**Comment by gwsw** [comment]
Sorry, I don't know much about how vim handles non-UTF-8 character sets. Based on your last screenshot, it appears to me that vim is displaying latin1 characters correctly; for example 0xB0 should be a degree sign, and 0xB2 should be a superscript 2, and that is what your screenshot shows. What I don't understand is why your original screenshot showed colored boxes for these characters. Perhaps that was using some MS-DOS-specific character set rather than latin1.

**Comment by aki-k** [comment]
https://github.com/gwsw/less/issues/364#issuecomment-1525977046 is not a screenshot but text if that's what you meant with "last screenshot". It'd be really nice if less could output those characters just as vim does.

**Comment by aki-k** [comment]
2005 called and showed how the original form of that nfo file can be shown in vim:

:e ++enc=cp437

https://vim.fandom.com/wiki/View_NFO-files_correctly

**Comment by gwsw** [comment]
Less should output the latin1 characters if you set LESSCHARSET=latin1. You may also need to ensure that your terminal emulator is set to use latin1 characters. This produces output that on my terminal looks exactly like your vim output:
```
LESSCHARSET=latin1 less HKff.txt
```

**Comment by aki-k** [comment]
This actually fixed my problem completely:
```
cat magnitude.nfo | iconv -f 437 -t utf-8 | less -r
```

**Comment by aki-k** [comment]
Thanks I'll close this issue now
