### ISSUE TITLE
-Wimplicit-function-declaration problems with less-362 and gcc-13.1

### ISSUE THREAD

**Issue by moodangsellaplow** [gwsw/less#365]
With gcc-13.1 and less-362 (building from tarball) I get this:

...
gcc -I. -c -DBINDIR=\"/usr/bin\" -DSYSDIR=\"/etc\"  -O2 -m64 -march=x86-64 -mtune=generic -pipe -std=gnu17 screen.c
screen.c: In function 'ltgetflag':
screen.c:746:17: warning: implicit declaration of function 'tgetflag'; did you mean 'ltgetflag'? [-Wimplicit-function-declaration]
  746 |         return (tgetflag(capname));
      |                 ^~~~~~~~
      |                 ltgetflag
screen.c: In function 'ltgetnum':
screen.c:757:17: warning: implicit declaration of function 'tgetnum'; did you mean 'ltgetnum'? [-Wimplicit-function-declaration]
  757 |         return (tgetnum(capname));
      |                 ^~~~~~~
      |                 ltgetnum
screen.c: In function 'ltgetstr':
screen.c:768:17: warning: implicit declaration of function 'tgetstr'; did you mean 'ltgetstr'? [-Wimplicit-function-declaration]
  768 |         return (tgetstr(capname, pp));
      |                 ^~~~~~~
      |                 ltgetstr
screen.c:768:17: warning: returning 'int' from a function with return type 'char *' makes pointer from integer without a cast [-Wint-conversion]
  768 |         return (tgetstr(capname, pp));
      |                ~^~~~~~~~~~~~~~~~~~~~~
screen.c: In function 'get_term':
screen.c:1241:13: warning: implicit declaration of function 'tgetent'; did you mean 'lgetenv'? [-Wimplicit-function-declaration]
 1241 |         if (tgetent(termbuf, term) != TGETENT_OK)
      |             ^~~~~~~
      |             lgetenv
screen.c:1382:28: warning: implicit declaration of function 'tgoto' [-Wimplicit-function-declaration]
 1382 |                 strcpy(sp, tgoto(sc_move, 0, 0));
      |                            ^~~~~
screen.c:1382:28: warning: passing argument 2 of 'strcpy' makes pointer from integer without a cast [-Wint-conversion]
 1382 |                 strcpy(sp, tgoto(sc_move, 0, 0));
      |                            ^~~~~~~~~~~~~~~~~~~~
      |                            |
      |                            int
In file included from less.h:80,
                 from screen.c:16:
/usr/include/string.h:141:70: note: expected 'const char * restrict' but argument is of type 'int'
  141 | extern char *strcpy (char *__restrict __dest, const char *__restrict __src)
      |                                               ~~~~~~~~~~~~~~~~~~~~~~~^~~~~
screen.c:1399:28: warning: passing argument 2 of 'strcpy' makes pointer from integer without a cast [-Wint-conversion]
 1399 |                 strcpy(sp, tgoto(sc_move, 0, sc_height-1));
      |                            ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
      |                            |
      |                            int
/usr/include/string.h:141:70: note: expected 'const char * restrict' but argument is of type 'int'
  141 | extern char *strcpy (char *__restrict __dest, const char *__restrict __src)
      |                                               ~~~~~~~~~~~~~~~~~~~~~~~^~~~~
screen.c: In function 'cost':
screen.c:1462:9: warning: implicit declaration of function 'tputs'; did you mean 'puts'? [-Wimplicit-function-declaration]
 1462 |         tputs(t, sc_height, inc_costcount);
      |         ^~~~~
      |         puts
screen.c: In function 'goto_line':
screen.c:2156:16: warning: passing argument 1 of 'ltputs' makes pointer from integer without a cast [-Wint-conversion]
 2156 |         ltputs(tgoto(sc_move, 0, sindex), 1, putchr);
      |                ^~~~~~~~~~~~~~~~~~~~~~~~~
      |                |
      |                int
screen.c:1656:26: note: expected 'char *' but argument is of type 'int'
 1656 | static void ltputs(char *str, int affcnt, int (*f_putc)(int))
      |                    ~~~~~~^~~
...

Do I need to add some -D or -U option to my CFLAGS to fix this?

**Comment by gwsw** [comment]
Ok, perhaps this is related to 3f58d4d9fe15fe2c2b322bb3685aad28cb1a9280 by @thermitegod, which removed the local declaration of tgetstr() and related functions, expecting them to be defined in termcap.h. But based on your build log, it appears your system does not have termcap.h. Is that correct? Which include file declares tgetstr() on your system?

**Comment by satmandu** [comment]
termcap.h does exist on our system:
```
crew whatprovides termcap.h
ncurses: /usr/local/include/ncurses/termcap.h
ncurses: /usr/local/include/ncursesw/termcap.h
```

maybe we need to add a `CFLAGS+=' -I/usr/local/include/ncurses` to our configure command line? I don't think less has a configure option to specify where curses resides...

**Comment by satmandu** [comment]
```
chronos@cheekon-x86_64 /usr/local/lib/crew/packages $ grep tgetstr /usr/local/include/ncurses/termcap.h 
extern NCURSES_EXPORT(char *) tgetstr (const char *, char **);
chronos@cheekon-x86_64 /usr/local/lib/crew/packages $ grep tgetstr /usr/local/include/ncursesw/termcap.h 
extern NCURSES_EXPORT(char *) tgetstr (const char *, char **);
chronos@cheekon-x86_64 /usr/local/lib/crew/packages $
```
I'm trying building with the added CFLAGS...

**Comment by satmandu** [comment]
That fixes our build...

**Comment by gwsw** [comment]
Can you try top of tree (35aac3f11104ed597886d05fa9d3264387c3f6e6) and confirm that this fixes your build? You will need to start with running configure.

**Comment by satmandu** [comment]
> Can you try top of tree ([35aac3f](https://github.com/gwsw/less/commit/35aac3f11104ed597886d05fa9d3264387c3f6e6)) and confirm that this fixes your build? You will need to start with running configure.

That fixed it for us. Thanks!

**Comment by gwsw** [comment]
I have released less-633 which includes this fix.
