### ISSUE TITLE
lesspipe.sh: in POSIX sh, ';;&' is not defined

### ISSUE THREAD

**Issue by wileyhy** [gwsw/less#369]
In order to use ';;&', the shell can be `bash` or `mksh`, or the syntax can be changed to conform with POSIX.  On Fedora 38, `dash`, `oksh` and `zsh` return errors. 

As a poor worrkaround theissue can be resolved, I believe, from the `case` statement spanning lines 53-128, with breaking the `case` up into three separate statements, essentially replacing each... 
`;;&`
...with... 
`;;`
`esac`
`case "$1" in`
`` 
...(note newlines).

Thanks for letting people contribute.
cheers
(credit: shellcheck) 

https://pubs.opengroup.org/onlinepubs/9699919799/utilities/V3_chap02.html#tag_18_09_04

[liveuser@localhost-live less]$ zsh
[liveuser@localhost-live]~/OTHERSPROJECTS/less% x=1; case $x in 0) echo foo ;;& 1) echo bar ;; *) echo quux ;; esac
zsh: parse error near `&'

[liveuser@localhost-live less]$ ksh
$ x=1; case $x in 0) echo foo ;;& 1) echo bar ;; *) echo quux ;; esac                                               
ksh: syntax error: `&' unexpected

[liveuser@localhost-live less]$ mksh
$ x=1; case $x in 0) echo foo ;;& 1) echo bar ;; *) echo quux ;; esac
bar

[liveuser@localhost-live less]$ oksh
localhost-live$ x=1; case $x in 0) echo foo ;;& 1) echo bar ;; *) echo quux ;; esac
oksh: syntax error: `&' unexpected

[liveuser@localhost-live less]$ dash
$ x=1; case $x in 0) echo foo ;;& 1) echo bar ;; *) echo quux ;; esac
dash: 1: Syntax error: word unexpected (expecting ")")
$ dash: 1: Syntax error: ")" unexpected

**Comment by polluks** [comment]
Maybe you should open this issue in https://github.com/wofr06/lesspipe/issues

**Comment by wileyhy** [comment]
https://github.com/wofr06/lesspipe/issues/129

**Comment by wileyhy** [comment]
Reported this bug on Red Hat bugzilla.
https://bugzilla.redhat.com/show_bug.cgi?id=2210583
