### ISSUE TITLE
Less on Windows hangs when exiting after the terminal was resized

### ISSUE THREAD

**Issue by dblueman** [gwsw/less#371]
Less 621 (as distributed when installing Git) on Windows 11 hangs when quitting after resizing the terminal. As a result, the user must run 'taskkill /f /im less.exe'.

Steps to reproduce:
1. open file in less eg via 'less.exe test.txt'
2. resize terminal
3. type 'q' to quit
4. observe less hangs

**Comment by gwsw** [comment]
@adoxa Hi Jason, do you have any thoughts about this? I'm not sure how the git version of less is compiled. The cygwin build does not seem to have this problem.

**Comment by adoxa** [comment]
I couldn't replicate it on 10 (21H2 19044.1526), using Git for Windows 2.41.0 (less 633), in either ConHost, Windows Terminal or MinTTY.

**Comment by dblueman** [comment]
Reinstalling the current git 2.41.0, which ships less version 633, I now can't reproduce the problem.

Case closed! Many thanks for trying to reproduce guys.
