### ISSUE TITLE
With stdin redirected to /dev/null and output to a file less started to return exit code 1

### ISSUE THREAD

**Issue by ppisar** [gwsw/less#373]
There is a change in an exit code if a standard input is /dev/null and standard output is not a terminal:

With 608 version of less:

$ unset LESSOPEN; /usr/bin/less /etc/passwd </dev/null >/dev/null; echo $?
0

After upgrading to 633:

$ unset LESSOPEN; /usr/bin/less /etc/passwd </dev/null >/dev/null; echo $?
1

I understand it's a corner case nobody wants to use, but still it exists in the wild (pmtools test suite).

**Comment by gwsw** [comment]
This is fixed in 39c96a472a53e35726cea72e9bd1fc9779133acf (less-634).

**Comment by ppisar** [comment]
Great. Please, don't forget to release it on your home page <http://www.greenwoodsoftware.com/less/>.

**Comment by gwsw** [comment]
Released in less-635.
