### ISSUE TITLE
unable to enter input (hanging/missed keypress) and getting "Waiting for data..." on screen

### ISSUE THREAD

**Issue by shishz** [gwsw/less#375]
I'm using less-633-1 on fedora 38.

I used to be able run:
$ gpg -d encrypted.asc | less

and input the password and have the file displayed in less.  Now less scribbles on the screen "Waiting for data..." and now trying to enter the password, characters will be either dropped? or not received by gpg.

The "Waiting for data..." is not useful and spams the terminal right over the password prompt too.

**Comment by gwsw** [comment]
This is the same as #368 and is fixed in less-634.

**Comment by shishz** [comment]
Thanks.  I just tried v634 and it worked.
