### ISSUE TITLE
Search result is hidden when using `--header`

### ISSUE THREAD

**Issue by apcamargo** [gwsw/less#376]
If you search for a pattern when using `--header`, the result is hidden by the header line.

Example:

```bash
less -S --header 1 genomad_marker_metadata.tsv
```
![image](https://github.com/gwsw/less/assets/22940964/d382afae-bd34-49a0-905a-7660176c2898)
Search for "GENOMAD.000100.CC" (`/GENOMAD.000100.CC`):
![image](https://github.com/gwsw/less/assets/22940964/01b90211-30c4-4038-b237-703f156b7edf)
The result is hidden behind the header and can only be seen by pressing `↑`:
![image](https://github.com/gwsw/less/assets/22940964/82efc426-f7ed-4462-ac41-fade6640fad4)
A simple solution would be to show the result in the `n + 1` line that is being displayed, where `n` is the number of lines in the header.

**Comment by gwsw** [comment]
The description of --header in the man page does say:
```
              (Note that it
              may  be  necessary to change the setting of the -j option to en‐
              sure that  the  target  line  is  not  obscured  by  the  header
              line(s).)
```
I don't like automatically changing the setting of an option that the user has control over, but I will think about this.

**Comment by apcamargo** [comment]
I completely missed this. I think you're right that it is not a good idea to change the setting automatically when it is exposed to the user.
