### ISSUE TITLE
ENV_VAR += incorrectly appends options without spaces

### ISSUE THREAD

**Issue by PatrickF1** [gwsw/less#380]
This is a snippet of my lesskey file
```
#env
LESS =  --ignore-case
LESS += --LONG-PROMPT
LESS += --RAW-CONTROL-CHARS
LESS += --tabs=4
LESS += --window=-4
LESS += --quit-on-intr
```
When I run less, I get
```
There is no ignore-case--LONG-PROMPT--RAW-CONTROL-CHARS--tabs=4--window=-4--quit-on-intr option ("less --help" for help)
```
I've tried appending $ to each line, adding a single space, and quoting all the options with a space in the front to prevent it from being trimmed (e.g. " --LONG-PROMPT"). Alas, nothing works. What am I doing wrong? Or could this be a bug?

Thanks!

**Comment by gwsw** [comment]
As noted in the man page, whitespace before and after the equals sign is ignored. However spaces at the end of a line are not. So you should be able to just append a space to the end of each line.

**Comment by PatrickF1** [comment]
Thank you Mark, that worked. The first time I tried by adding spaces at the end of each line must have failed because my editor over-helpfully trimmed the lines. That was tough to debug though and I suspect most users expect += to automatically separate their values with spaces. Just my two cents! Thanks for continuing to maintain less for for responding so quickyl!
