### ISSUE TITLE
lesskey: using "-#" option with `LESS` environment variable does not work

### ISSUE THREAD

**Issue by jf** [gwsw/less#382]
let's say that you have the following in your `lesskey` file:
```
#env

LESS = -N -#4
```

only `-N` will take effect, but *not* `-#4`

I'm not sure that this is worth fixing (do not use `-#`, use `--shift` instead)... but in any case this should be at least documented so that nobody stumbles over it.

The key is the logic in `parse_line`, which calls `clean_line`, which will trim an input line at the first `#` regardless of what that *may* or may not represent (in this case, not a comment, but a valid `#` char that you want to keep!), **before** any attempt to interpret what the line may be (is it a `LESS` env var?).

To truly fix this, we would have to **avoid** doing `clean_line` first, and push all the `#` handling into BOTH `parse_varline`, and `parse_cmdline`, and I'm guessing that's not ideal. We *could* have a simpler solution and only complicate `parse_varline`... but I'm not sure that's ideal either:

```
	...

	if (p == NULL)
		return;

	if (tables->currtable->is_var)
		parse_varline(p, tables);
	else {
		p = clean_line(p);
		if (*p == '\0')
			return;
		parse_cmdline(p, tables);
	}
}
```

Perhaps the best thing to do would be to add a `KNOWN BUGS` section to `lesskey`'s man page?

**Comment by gwsw** [comment]
You can escape the hash with a backslash to avoid it being treated as a comment character:
```
LESS = -N -\#4
```
I will change the lesskey man page to note that # is one of the characters that needs to be escaped.

**Comment by jf** [comment]
oh doh! what an easy fix 😮‍💨 Thank you for the tip (and the work to be done on the man page)!

**Comment by jf** [comment]
(sorry, just realized maybe I should leave the issue open and leave it to you to close this when the man page is updated.)

**Comment by gwsw** [comment]
Documented in ac874f70fdabcc83df6b43f0ef3882dbc27ff789.
