### ISSUE TITLE
macOS: dist

### ISSUE THREAD

**Issue by polluks** [gwsw/less#387]
For your information:
Apple does not include nroff anymore because of GPLv3.
This is the work around
`make -f Makefile.aut NROFF="mandoc -man" dist`

**Comment by gwsw** [comment]
Thanks for the information. I always make releases on a Windows machine so this doesn't affect my work flow, but I will keep it in mind. Perhaps Makefile.aut could set NROFF conditionally but it doesn't seem worth it right now.
