### ISSUE TITLE
mouse-click mark behaves as if the first line was marked

### ISSUE THREAD

**Issue by avih** [gwsw/less#389]
The docs for `--mouse` state:
> ... clicking the mouse sets the  "#"  mark  to  the line  where the mouse is clicked ...

While using `-J` to display the status column does indeed show that the clicked line gets marked with `#`, jumping to this mark with `'#` behaves as if the mouse marked the first visible line - and not the clicked line.

Expected behavior:
`'#` jumps so that the marked line becomes the top line.

Alternatively, that clicking the mouse anywhere marks the top line with `#`, rather than the clicked line.

I don't know if it's intended to behave like that - personally I think it's fine if the mouse marked the first visible line, like `m#` would, but it looks weird that jumping to the mark with `'#` can end up with the visibly marked line not as the top line.

**Comment by avih** [comment]
OK, I _think_ I got it through experimentation. Please let me know if that's correct:

Marking a line actually remembers two things:
- The marked line (where the letter or `#` appears at the status column).
- The "current view" or the top line or $whatever else which represents the position of the current view at the file.

So when jumping to a mark, it restores this "current view".

But (if `-J` is used) it will also show the marked line which is not necessarily the "current view" line,

`m` marks the top line of the current view.
'M' marks the bottom line of the current view.
Mouse-click marks any line of the current view.

But all of those, when jumping to the mark, will return to the current view, where the mark itself is not necessarily the top of this view.

Yes?

**Comment by gwsw** [comment]
Yes, that is exactly correct. The idea is that jumping to a mark will make the screen look exactly like it did when the mark was set.

**Comment by avih** [comment]
> The idea is that jumping to a mark will make the screen look exactly like it did when the mark was set.

Right, that's what I imagined a mark would do - and it does, but the line marker threw me off.

Maybe it would be useful to mention at the docs that "current view" (which is the mark jump target) and the "marked lines" are not synonymous?

**Comment by avih** [comment]
I'm closing because it behaves as designed.

I'll leave the decision of whether to modify the docs to someone else.

Thanks for the explanation.
