### ISSUE TITLE
Unclear compilation documentation in README

### ISSUE THREAD

**Issue by neunenak** [gwsw/less#39]
The README says that to compile `less` it is necessary to first run a shell script called `configure`; however, there is no file called `configure` in the repository.

**Comment by timotheuslin** [comment]
[Igor Liferenko's answer works for me](https://unix.stackexchange.com/questions/468215/how-to-compile-less-pager/469506#469506)
...
autoheader
autoconf
./configure
make -f Makefile.aut funcs.h
make
...

**Comment by gwsw** [comment]
The instructions in the README are written for someone compiling a release, as packaged in a zip or tgz file which has been created by "make -f Makefile.aut release". There aren't instructions yet on how to build from the git repository, although there should be.
