### ISSUE TITLE
less +F --header produces infinite skipping... on Ctrl-X

### ISSUE THREAD

**Issue by joknarf** [gwsw/less#400]
seems a little bug.

if the text is shorter than terminal rows, pressing Ctrl-X produces infiinite loop `skipping...` message
![WindowsTerminal_y5kzSZdmcZ](https://github.com/gwsw/less/assets/10117818/56f2624e-fb93-434c-82f1-c46da6d19d89)

if text is longer than terminal rows, seems ok:
![WindowsTerminal_HWn2zPkxSV](https://github.com/gwsw/less/assets/10117818/73840d56-e244-421e-8412-dca2fad2c578)

same on v632 and v639

**Comment by gwsw** [comment]
Thanks, fixed in b49f194a77fb752b9dd172e347cfc5380a7e49e3.

**Comment by joknarf** [comment]
Thank you, I confirm this is fixing the issue.
