### ISSUE TITLE
Segmentation fault (core dumped) when trying to search for `!=`

### ISSUE THREAD

**Issue by fstab** [gwsw/less#402]
Hi, I just wanted to search for `!=` in a text, so I typed

```
/!=
```

I know this is wrong, because `/!` switches to `Non-match /`.

However, if I type the full sequence `/!=` followed by `<enter>` less crashes with:

```
Segmentation fault (core dumped)
```

Less version is `less 633 (PCRE2 regular expressions)` (current version on Arch Linux).

**Comment by gwsw** [comment]
This is bug #374, which was fixed in 8320d1a920a90599892b9aca2306822709dab8f7 (released in less-635).
