### ISSUE TITLE
Horrid color specs

### ISSUE THREAD

**Issue by gvanem** [gwsw/less#407]
I've been using most as the `PAGER` for man/groff until now. It looks awesome.
E.g. from the `man tgoto`, it shows this nice output:
![tgoto-most](https://github.com/gwsw/less/assets/945271/7fe03648-df8b-4bcd-9db6-b68ff59f81ac)

But trying to view the already generated `f:\MinGW32\share\man\cat3\tgoto.3x` [file]() using less with
no `%LESS`, it looks like shit:
![tgoto-less](https://github.com/gwsw/less/assets/945271/03f7b330-3c91-41bd-9fbc-cb91c30c3a00)

Trying a `set LESS= --dumb -R --use-color -D d14.1 -D u+9.1 -D s+5.1`, it looks a bit less ugly:
![tgoto-less-2](https://github.com/gwsw/less/assets/945271/b8239ba1-9e5c-47a4-a8f0-181fdc3469e3)

I'd ass-u-me since I have a default blue background in my Windows console, that less would never dare to set a 
dark blue on black background. Yikes. 

With most, it's pretty easy to set the colors in `most.rc`. But here, I have to decode a bunch of gibberish `--color=xyz stuff`
to get this correct. What do others with a blue console set `$LESS` to? 

*BTW*. I'm on Win-10 with the *Legacy Console* tuned **on** if that matters.

**Comment by gwsw** [comment]
The default colors for Windows were chosen many years ago and the reasons are unfortunately lost in the mists of time. I agree they're not ideal. If you have a nonstandard background color, you may want to select only foreground colors and leave the background as default (by specifying a single number to the -D option). For example, something like
```-Dd15 -Du14``` or the equivalent ```-DdW -DuY```
to set bold to bright white and underline to bright yellow, with the default background for both. This should look similar to the most output. These settings can of course be set in your LESS environment variable or lesskey file, so you don't have to type them every time.

**Comment by gvanem** [comment]
Thanks for a fast response. I tried with `set LESS=--dumb -R --use-color -Dd15 -Du14 -Ds12` on a man-file with 
some SGR sequences:
```
 ←[1m[-T ←[4m←[22mtagsfile←[24m←[1m]
```

this still shows as black and ugly background; almost impossible to see:

![less-tags](https://github.com/gwsw/less/assets/945271/804d21bc-e6de-41e7-b173-02a45845bd59)

It's cyan on red in a Cygwin `cat + grep`.

**Comment by gwsw** [comment]
If you set the -D options in the LESS environment variable (rather than on the command line), you must terminate each one with a dollar sign, like this:
```
set LESS=-R -Dd15$ -Dd14$ -Ds12$
```
You shouldn't use the --dumb option, although it has no effect on Windows.

**Comment by gvanem** [comment]
Finally some progress; this works almost as nice as in most: `set LESS= -R --use-color -D d15$ -D u11$`.
But I think I stick to most with it's support for mouse-wheel scroll etc (I hacked that up). 

I'd say you should really consider supporting color-settings in a `less.cfg` file. This here is ludicrous IMHO.

**Comment by gwsw** [comment]
Less does support mouse wheel scrolling (see the --mouse option).
Color settings can be set in the lesskey configuration file.

**Comment by gvanem** [comment]
> (see the --mouse option).

It does nothing.

**Comment by gwsw** [comment]
Mouse scrolling was broken on Windows builds between less-605 and less-635 (see #379). If you are using one of those versions you could update to less-636 or later.

**Comment by gvanem** [comment]
> If you are using one of those versions you could update to less-636 or later.

Done that (built less myself). And it works fine now. Hence closing this issue.
