### ISSUE TITLE
Not buffering the first screen of data

### ISSUE THREAD

**Issue by book** [gwsw/less#408]
When piping commands that produce a lot of output slowly (say, a line every few seconds) through `less`, it will only start showing something when a screenfull of output has been produced. Which means waiting a long time before seeing anything.

It would be nice to have an option that makes less output lines as they arrive, until the screen is full. I have been looking in the manual, and couldn't find such an option.

**Comment by gwsw** [comment]
Could you describe a way to reproduce this, including the type of operating system you're running on? On both Linux and MacOS, this command produces output that appears in less one line at a time, before the first screen is filled:
```
i=1; while :; do echo $i; sleep 1; let i=$i+1; done | less
```

**Comment by rpigott** [comment]
I'd hazard a guess that you're probably observing the application buffering its own output when stdout is not a tty. Nothing to do with less.

**Comment by book** [comment]
My use case is typically a `git log` command, where the first few commits take a lot of time to show up. I'd expect the first commit (less than a screenful of text) to show up, followed by the next one, whenever it is found, and so on.

Indeed, `less` already does what I expected it to do. That can easily be confirmed using GNU `grep` with and without its `--line-buffered` option, and watching the differences.

Sorry for not investigating further and wasting your time needlessly. And thank you for building a great tool so many years ago, and maintaining it to this day.
