### ISSUE TITLE
less becomes unresponsive after resizing on Windows

### ISSUE THREAD

**Issue by zadjii-msft** [gwsw/less#411]
(I'm porting this over here from https://github.com/microsoft/terminal/issues/15386, since we're at a loss)

> ### Windows Terminal version
> 
> 1.16.10262.0
> 
> ### Windows build number
> 
> 10.0.22621.1702
> 
> ### Other Software
> 
> git version 2.39.2.windows.1
> 
> ### Steps to reproduce
> 
> - start a terminal
> - run a command which uses a pager e.g. git log
> - Maximize the terminal pane
> - Page down (space) a few pages
> - Terminal goes unresponsive (i.e. the 'less' prompt does not reappear)
> 
> 
> 
> ### Expected Behavior
> 
> Scrolling down keeps working normally
> Pressing 'q' quits the pager
> 
> ### Actual Behavior
> 
> One must interrupt to get the prompt back.
> For some reason terminal within vscode cannot be interrupted with keyboard & one must kill the task.
> See https://github.com/microsoft/vscode/issues/180406

Additional notes: this seems to repro the same in both Windows Terminal and conhost

> If you try to open a `conhost.exe` window, then set the "screeen buffer size" to be equal to the "window size", does the same thing repro in conhost?
> ![image](https://github.com/microsoft/terminal/assets/18356694/6272c335-5955-49f2-904a-f9e8a03a8d0b) ![image](https://github.com/microsoft/terminal/assets/18356694/556eeedb-c74f-4772-b87b-86c64b177a00)

> Yes, same behavior with conhost and sizes equal

/cc @stephenatwork, who originally filed this on the Terminal repo

**Comment by gwsw** [comment]
I'm trying to reproduce this using less built with Visual C. First I open Command Prompt (is that what you mean by "start a terminal"?). Then I run "less FILE". At this point I cannot resize the window. Dragging the corners does not enlarge it, and although I can shrink it, scroll bars appear and the underlying terminal seems to remain unchanged. If I click the Maximize button the window moves to the upper left corner of the screen but the size remains unchanged. 

All this acts the same if I run in Developer PowerShell for VS rather than cmd.

Any hints on how to reproduce? Also, which version of less are you running?

**Comment by zadjii-msft** [comment]
> is that what you mean by "start a terminal"?

I believe OP repro'd this with both a Windows Terminal window and a conhost / vintage console window. With conhost, they needed to set the "Screen Buffer Size" to be equal to the "Window Size", and enable "Wrap text output on resize". I _think_ if you disable that checkbox in the properties, you'll get the behavior you're describing.

My suspicion was that there was some bug in specifically that case - where the "viewport" was as big as the entire text buffer, that caused this. 

I alas think we'll need @stephenatwork to answer which `less` version they were using.

**Comment by gwsw** [comment]
Thanks, after enabling "Wrap text output on resize" I am able to resize the cmd window. However I cannot reproduce the reported issue. I maximize the terminal window, press SPACE a few times, and everything is fine. I don't see less become unresponsive. I'm using less-643.

**Comment by stephenatwork** [comment]
Thanks for following up guys. I just tried to repro the original steps & what was a 100% repro didn't reproduce a t all.

cmd window 10.0.22621.1635
less 629 (included with git)

**Comment by zadjii-msft** [comment]
Well, that's just fantastic to hear. Thanks for following up! I guess we don't need this after all ☺️
