### ISSUE TITLE
RFE: please start making github releases

### ISSUE THREAD

**Issue by kloczek** [gwsw/less#418]
Is it possible next time on release new version make the github release to have entry on https://github.com/gwsw/less/releases? 🤔

I'm asking because only on make gh release is spread notification about new release to those who have set watch->releases.

More about gh releases is possible to find on
https://docs.github.com/en/repositories/releasing-projects-on-github/managing-releases-in-a-repository
https://github.com/marketplace/actions/github-release

**Comment by gwsw** [comment]
I don't want to give people the idea that they can download official releases from github. Releases that would be produced by github would contain all the checked-in files, and would therefore not be the same as actual releases on greenwoodsoftware.com. Release announcements can be monitored by subscribing to the less-announce mailing list.

**Comment by kloczek** [comment]
Again .. tis RFE is >>>>only about spread notification about new release<<<<<.

**Comment by gwsw** [comment]
I would be ok with just using it to announce a new release, but as I understand it, creating a release will produce a tar file named less-XXX.tar that will be publicly available. The name would look identical to the releases on greenwoodsoftware.com but would have different contents, which I think could be confusing. Perhaps I could create a release on github and then immediately delete it? I don't know if that would do what you want.

**Comment by kloczek** [comment]
> I would be ok with just using it to announce a new release, but as I understand it, creating a release will produce a tar file named less-XXX.tar that will be publicly available.

gh release does not create any tsr balls. It produces ONLY email notifications.

**Comment by gwsw** [comment]
That doesn't seem to be true. I just tried creating a github release for less-643, and the release contains two "assets": v643.zip and v643.tar.gz. I didn't see any way to remove the assets from the release, so I deleted the release.

**Comment by kloczek** [comment]
Exactly the same assets are listed in every tag.
Nothing else is created/provided.
Again: gh release is only about spreading over email notifications about new release.
Only this and nothing more.

**Comment by gwsw** [comment]
I'm afraid that sending a notification from github will lead people to believe that they should retrieve the release from github. This is already a problem and I don't want to make it worse. I also don't see the value in having two notification systems, one on greenwoodsoftware.com and one on github, where the github notification just tells you to go to greenwoodsoftware. Why do you want to use the github notification system rather than the existing one on greenwoodsoftware? I also see that a number of high-profile repositories, like [linux ](https://github.com/torvalds/linux) and [git ](https://github.com/git/git) itself, don't use github releases.

**Comment by kloczek** [comment]
None of the gh notifications changes someone believes 😋 

Value is very simple: **inform** those who applied to be informed about new release.
I did not seen anything about greenwoodsoftware in you first gh release and my automation was able to process that notification to download new version of the source tar ball to try upgrade less.spec and send request to build infra to preliminary test is that upgraded package will be building or not (and everything was OK).

**Comment by gwsw** [comment]
Sorry, but I just don't see the value in having two notification systems. I also believe that if someone receives a release notification from github, they are likely to think that they should download the release from github. No one should be downloading releases from github unless they are doing development on less. End users should download releases from greenwoodsoftware.com or gnu.org.

**Comment by kloczek** [comment]
Value is in informing people that new release has been created.
If you don't care about that that is perfectly fine ..

**Comment by gwsw** [comment]
If someone wants to be informed of new releases, they can subscribe to the mailing list (http://greenwoodsoftware.com/less/less-announce.html). As I said, I don't see the value in having two notification systems.
