### ISSUE TITLE
Colors break in Windows Terminal

### ISSUE THREAD

**Issue by adam-c-anderson** [gwsw/less#42]
OS: Win10 Pro 10.0.18363.0
Windows Terminal 0.7.3451.0

Steps to reproduce:
1. Open a new PS terminal session. I am able to reproduce this issue with an empty profile.
2. View some output from less. `less -?` is quick and easy but anything will do. Less outputs help with expected normal/foreground color (gray or white)
3. Do something that causes output. I used `ls` but `type` also works. The output appears as normal.
4. Now view some output from less again. 

Expected: normal output should use the same color as before
Actual: normal output appears black

This only occurs in Windows Terminal. The normal console host does not reproduce this problem. I'm not sure if it's a Windows Terminal bug or less. I've reported it in the Windows Terminal repo as well.

**Comment by adam-c-anderson** [comment]
Possibly addressed by https://github.com/gwsw/less/pull/29

**Comment by lzybkr** [comment]
This issue is more likely fixed in https://github.com/gwsw/less/pull/26

**Comment by tats-u** [comment]
@lzybkr
I have a similar issue in the version 551, which is available in [scoop](https://scoop.sh/).
OS: Windows 10 Pro 18363.592
Terminal: [Hyper](https://hyper.is/) 3.0.2 + Dark theme plugins (`hyper-material` / `hyper-solarized-dark` / `verminal`)

Has it already been fixed after the version 551?  If so, do you know when the next release will be published?  Releases has been stopped at it as much as about half a year ago.

**Comment by rivy** [comment]
I believe this is already fixed in my "fork" (https://github.com/rivy/less).
It's usable until a/the fix is released here...

**Comment by gwsw** [comment]
Should be fixed in #26.

**Comment by tats-u** [comment]
Oh, version 553 & 554, which seem to have fixed this bug, are available in GitHub Releases.  I'm sorry for overlooking them.  However, they have not been mentioned in [the official homepage](http://greenwoodsoftware.com/less/)...  Are they tolerable against general use like version 551?  If so, I'd like to encourage Chocolatey and Scoop, package managers of Windows softwares, to update the packages of `less`.

**Comment by gwsw** [comment]
Versions 553 & 554 have not yet gone through beta testing, so I'd prefer they not get general use yet. I plan to release a version for beta testing soon.

**Comment by tats-u** [comment]
@gwsw Thank you for the information.  I'll wait for one.
