### ISSUE TITLE
Define the scroll area to preserve horizontal and vertical header.

### ISSUE THREAD

**Issue by gschadow** [gwsw/less#43]
We use less with psql (and mysql and whatever other database tools), for an example see [A better psql with less.](http://merlinmoncure.blogspot.com/2007/10/better-psql-with-less.html). Now wouldn't it be nice if we could fix the header line so as to scroll only in the region below line 2? But then comes horizontal scrolling, where you would want to scroll the horizontal header along with the body. And once you have that, you'd want a vertical header also, where horizontal scrolling would begin at, for example, column 10, while vertical scrolling would scroll that vertical header just like horizontal scrolling would scroll that horizontal header.

Think of Excel Window -> Freeze Pane setting.

So this could be using the option --freeze-pane 10,2, for example, where 10,2 means 10 columns from the left of vertical header and 2 lines from the top of horizontal header, so that the scroll area is starting from 11,3.

Here are relevant questions about this subject on stackexchange:
- [pager program like less, able to repeat top N lines](https://unix.stackexchange.com/questions/27812/pager-program-like-less-able-to-repeat-top-n-lines)
- [How to scroll large datafile while keeping header](https://unix.stackexchange.com/questions/60507/how-to-scroll-large-datafile-while-keeping-header)

UPDATE: adding some example:
```
 foo | bar | baz | zebra | zoo
-----+-----+-----+-------+-----
   1 |   2 |   3 |     3 |   4
   4 |   5 |   6 |     9 |  10
   7 |   8 |   9 |    15 |  16
  10 |  11 |  12 |    21 |  22
  13 |  14 |  15 |    27 |  28
  16 |  17 |  18 |    33 |  34
  19 |  20 |  21 |    39 |  40
  22 |  23 |  24 |    45 |  46
  25 |  26 |  27 |    51 |  52
```
now let's say our terminal is only 20 columns by 9 lines, so it would show:
```
 foo | bar | baz | z
-----+-----+-----+--
   1 |   2 |   3 |
   4 |   5 |   6 |
   7 |   8 |   9 |
  10 |  11 |  12 |
  13 |  14 |  15 |
  16 |  17 |  18 |
lines 1-8
```
now if I scroll right and down I see this
```
   6 |     9 |  10
   9 |    15 |  16
  12 |    21 |  22
  15 |    27 |  28
  18 |    33 |  34
  21 |    39 |  40
  24 |    45 |  46
  27 |    51 |  52
lines 4-11/13 97%
```
but if I has been able to set the `--freeze-pane 0,2` then the window would look like this:
```
 baz | zebra | zoo
-----+-------+-----
  12 |    21 |  22
  15 |    27 |  28
  18 |    33 |  34
  21 |    39 |  40
  24 |    45 |  46
  27 |    51 |  52
lines 4-11/13 97%
```
and if I has been able to set the `--freeze-pane 6,2` then the window would look like this:
```
 foo | zebra | zoo
-----+-------+-----
   1 |    21 |  22
   4 |    27 |  28
   7 |    33 |  34
  10 |    39 |  40
  13 |    45 |  46
  16 |    51 |  52
lines 4-11/13 97%
```

**Comment by gwsw** [comment]
Addressed by the --header option in less-593.
