### ISSUE TITLE
[request] Windows: default LESSCHARSET to utf-8

### ISSUE THREAD

**Issue by avih** [gwsw/less#431]
On Windows, UTF-8 documents display incorrectly unless `LESSCHARSET` is set to `utf-8`, or the console codepage is set to UTF-8 (`chcp 65001`).

I _think_ the default input encoding which `less` assumes on windows is cp 1251 - at least the manpage mentions it, and if that's the case then there are two issues with that:
- According to wikipedia, [cp 1251 is for Cyrillic scripts](https://en.wikipedia.org/wiki/Windows-1251), which is not the default on many Windows systems. E.g. the default in many English and latin installs is 1252.
- These days, the vast majority of text files are encoded as UTF-8, while the default console codepage is not UTF-8 (most users don't touch it, and it's probably unwise for `less` to change it).

I'm not familiar enough with how `less` assumes the input encoding on non-windows systems (maybe it uses the LOCALE values?), but on Windows I think LESSCHARSET should default to `utf-8` even when the console codepage is not UTF-8.

I believe that would improve the out-of-the-box experience, while LESSCHARSET can still set a custom encoding if desired.

EDIT:
I see it actually defaults to ["dos"](https://github.com/gwsw/less/blob/master/charset.c#L482) encoding, which I'm pretty sure is a bad default in almost all cases, and UTF-8 is highly likely a better default, at least on Windows (can't speak for actual DOS, I don't think it's actually used much?).

**Comment by gwsw** [comment]
That's actually a mistake in the man page; the "windows" charset is 1252. I've fixed the man page.

I mostly agree that UTF-8 should be the default, at least ideally. The only issue is backwards compatibility: if someone is currently using less for documents that work with the current default, a less upgrade could make their documents unreadable until they figure out how to reconfigure it. I would guess that a very small number of users would be using such documents today, but I don't know what that percentage would be.

**Comment by avih** [comment]
I understand the concern.

But as far as I can tell the default encoding is actually "dos" and not "windows" or "1252". I seriously doubt that there are more users who rely on "dos" default than users who will benefit from "utf-8" default...

And, this could always be added to some changes doc or the actual manpage ("On Windows the defaulr is "utf-8". v644 and earlier defaulted to "dos").

**Comment by avih** [comment]
And, I now also realized that if the console CP is UTF8, then the user can't override the input encoding.

So a better fix is probably the diff I posted earlier, and also remove the `WIN32C` code which tests the console CP at the top of that function.

**Comment by avih** [comment]
For reference, that's my suggested patch:
<details>

```patch
From 7a6ef312895a3afd58f2592d1264bad964a28ef8 Mon Sep 17 00:00:00 2001
From: "Avi Halachmi (:avih)" <avihpit@yahoo.com>
Date: Tue, 19 Sep 2023 22:25:42 +0300
Subject: [PATCH] windows: assume UTF-8 input files by default

Previously, if the console codepage was UTF-8 (chcp 65001) then 'less'
assumed input files are UTF8, else if LESSCHARSET was set then that
was used for input files, else "dos" encoding was assumed.

This had few issues:
- The encoding couldn't be overridden if the console cp was utf8.
- The console is not utf8 by default, so the 'less' default was "dos".

Now, regardless of the console codepage:
- Input files are assumed UTF-8 by default, and display correctly.
- LESSCHARSET, LC_ALL, etc can always override the input encoding.
---
 charset.c    | 16 +++++++---------
 less.nro.VER |  1 +
 2 files changed, 8 insertions(+), 9 deletions(-)

diff --git a/charset.c b/charset.c
index 3a5e2b2..fbc651e 100644
--- a/charset.c
+++ b/charset.c
@@ -414,15 +414,6 @@ static void set_charset(void)
 {
 	char *s;
 
-#if MSDOS_COMPILER==WIN32C
-	/*
-	 * If the Windows console is using UTF-8, we'll use it too.
-	 */
-	if (GetConsoleOutputCP() == CP_UTF8)
-		if (icharset("utf-8", 1))
-			return;
-#endif
-
 	ichardef_utf(lgetenv("LESSUTFCHARDEF"));
 
 	/*
@@ -476,10 +467,17 @@ static void set_charset(void)
 	ilocale();
 #else
 #if MSDOS_COMPILER
+  #if MSDOS_COMPILER==WIN32C
+	/*
+	 * Default to "utf-8" on Windows.
+	 */
+	(void) icharset("utf-8", 1);
+  #else
 	/*
 	 * Default to "dos".
 	 */
 	(void) icharset("dos", 1);
+  #endif
 #else
 	/*
 	 * Default to "latin1".
diff --git a/less.nro.VER b/less.nro.VER
index 17e0fb0..349587b 100644
--- a/less.nro.VER
+++ b/less.nro.VER
@@ -1810,6 +1810,7 @@ variables.
 Finally, if the
 .I setlocale
 interface is also not available, the default character set is latin1.
+On Windows the default is utf-8.
 .PP
 Control and binary characters are displayed in standout (reverse video).
 Each such character is displayed in caret notation if possible
-- 
2.41.0.windows.2

```
</details>

**Comment by avih** [comment]
And, this seems like an unrelated issue, but I don't think `windows-1252` works as expected.

E.g. in these three cases:
```sh
# 0xCA (202)
printf "\312" | LESSCHARSET=dos less
printf "\312" | LESSCHARSET=windows-1252 less
printf "\312" | LESSCHARSET=windows-1251 less
```
LESSCHARSET does not seem to make any difference between "dos", "windows-1252", and "windows-1251".

If the console codepage is 437 then all three display `╩` (which is correct for 437).

If the console codepage is 1252 then all three display `Ê` (which is correct for 1252).

If the console codepage is 1251 then all three display `К` (which is apparently correct for 1251).

So it seems like the encoding is ignored, and instead it just prints the bytes and lets the console interpret it according to its current codepage?

In contrast, `LESSCHARSET=utf-8` makes it interpret the input as UTF-8 and display it correctly regardless of the console codepage, which is the expected correct behavior, e.g.:
```sh
# 0xe2 0x95 0xa9  U+2569  ╩
printf "\342\225\251" | LESSCHARSET=utf-8 less
```
Prints `╩` correctly regardless of the console codepage.

**Comment by avih** [comment]
> LESSCHARSET does not seem to make any difference between "dos", "windows-1252", and "windows-1251".

OK, I now actually read the docs, and the only thing LESSCHARSET does is specify which values are control/binary/printable, and at least at the example above, apparently 0xCA is printable in dos/1251/1252.

And indeed I presume that, except with UTF-8, the input is not converted, and the terminal displays the bytes according to its current codepage settings.

I guess that's not a terrible default logically, but you should know that the terminal codepage defaults to "OEM codepage", which is a legacy thing to emulate (real) DOS codepage, like 437 in the US or 850 in some European countries, so that dos programs (or some such) could run at the windows console and print non-garbage.

In these same counties, the actual 8-bit codepage which windows uses for its (ANSI) API, like `CreateFileA` is different, and typically in the 12XX group

So the default console codepage, i.e. OEM codepage, is rarely useful for anything on Windows, and not a good default practically. If anything, the ANSI codepage is somewhat useful if one limits oneself to 8-bit codepages, which is typically the 12XX ones (1252, etc).

But making the assumption that the input files are the system ANSI codepage (`GetACP()`) still needs another step to also display them correctly - either change the console codepage to the ANSI codepage, or convert from ANSI to W and use something like `WriteConsoleW` - which simply ignores the console codepage.

But even the 12XX encodings should be rare these days in text files (I don't have statistics, but I don't have any file which is encoded as 12XX that I know of).

So really, the only sensible default should be UTF-8, which basically bypasses all the hurdles: it's global, it's the most common encoding by far, it displays correctly regardless of the terminal codepage, and would typically "just work" (TM) out of the box.

And LESSCHAR* could still be used to override it.

I.e., I still think the 2nd patch I posted is the best approach.

**Comment by gwsw** [comment]
Done in 5dcf7b5f572dc75c31098d0cdf766eb682ec834c.

**Comment by avih** [comment]
Confirmed fixed. Thanks.
