### ISSUE TITLE
Distinguish release and beta git tags

### ISSUE THREAD

**Issue by cheese** [gwsw/less#441]
It is a common practice to implement https://github.com/gwsw/less/issues/245#issuecomment-1083614051, or the one suggested in https://github.com/gwsw/less/issues/245#issuecomment-1083726104. And I hope a `v643-release` tag can be created.

Some projects like Freedesktop SDK are not able to track new releases from arbitrary HTML pages but can track them from git tags.

**Comment by gwsw** [comment]
An additional ```v6xx-rel``` tag is now created for each release version (tags ```v661``` and ```v661-rel ```are the same).

**Comment by avih** [comment]
> An additional `v6xx-rel` tag is now created for each release version

I see you also tagged retroactively. Nice, but there are still untagged releases before v458. Maybe you can tag those too at some stage.
