### ISSUE TITLE
Highlighting changes word order in RTL text

### ISSUE THREAD

**Issue by backtabber** [gwsw/less#448]
Highlighting, such as used to indicate search matches, changes word order in RTL text.
I'm assuming that this has something to do with the ANSI escape sequences used for highlighting, which contain the letter "m". Is there any fix or workaround for this?

**Comment by gwsw** [comment]
Can you provide a sample file that demonstrates this issue?

**Comment by backtabber** [comment]
Open with less and search for ضرورت
[sample.txt](https://github.com/gwsw/less/files/13191824/sample.txt)

**Comment by gwsw** [comment]
I'm not seeing the problem, using the Terminator terminal emulator.

This is the file viewed in less:

![sample1](https://github.com/gwsw/less/assets/30166465/23fd9544-f1ff-4baa-8bbb-b2990bac1407)

And this is after searching for ضرورت:

![sample2](https://github.com/gwsw/less/assets/30166465/5ce80d8c-1c5f-49a2-a7df-f19d82706fef)

I don't read Arabic but as far as I can see, the word order has not changed. I wonder if the problem might be in your terminal emulator? What do you see if you just do ```cat sample3.txt``` using this file?

[sample3.txt](https://github.com/gwsw/less/files/13198787/sample3.txt)

This is what I see in Terminator:

![sample4](https://github.com/gwsw/less/assets/30166465/ab656db0-4203-406a-88fa-bc552422ef0f)

**Comment by backtabber** [comment]
Yes, the terminal emulator was the culprit.  Thanks for you help.

**Comment by backtabber** [comment]
If one happens to be stuck with such an uncooperative terminal emulator, is there any workaround for indicating the location of the search matches.  Would it be feasible to perhaps have an option to surround the matched string with asterisks rather than using ANSI escape sequences?

**Comment by gwsw** [comment]
Using asterisks would disrupt the screen layout, since an asterisk takes space on the screen. You could try the -JG option which would mark the matching line although it wouldn't indicate the exact substring within the line.

**Comment by backtabber** [comment]
That works.  Thanks again.
