### ISSUE TITLE
Say what program does in man page NAME section

### ISSUE THREAD

**Issue by jidanni** [gwsw/less#457]
Here we are looking around for terminal-related programs.
```
$ apropos -s 1 terminal
clear (1)            - clear the terminal screen
grotty (1)           - groff output driver for typewriter-like (terminal)...
luit (1)             - Locale and ISO 2022 support for Unicode terminals
more (1)             - display the contents of a file in a terminal
namei (1)            - follow a pathname until a terminal point is found
neqn (1)             - format equations for character-cell terminal output
nroff (1)            - format documents with groff for TTY (terminal) dev...
reset (1)            - initialize or reset terminal state
script (1)           - make typescript of terminal session
sensible-terminal (1) - sensible terminal emulator
...
```
We miss out on `less`. Why? because

> less - opposite of more

even on the Posix man page.

Sounded clever back then, but what if every man page did that? apropos(1) would
then be filled with "A is the opposite of B" and "C is an improved
version of D"... But one day when users are not familiar anymore with B
and D, it doesn't make sense.

So please fix the NAME field, so at least in apropos(1) it also just says
> less (1) - display the contents of a file in a terminal

**Comment by polluks** [comment]
Well, less is a true veteran, not any wannabe tool.
