### ISSUE TITLE
Feature Request: Save filtered results

### ISSUE THREAD

**Issue by asdf23** [gwsw/less#46]
In less I can filter the results with the & key, I can also save the results. However I believe there is no way to save only the filtered results. I'd like to be able to hit & add a filter then press s to specify a log file. The results of the log file should reflect the filter.

**Comment by gwsw** [comment]
I've spent some time investigating this, but the code isn't structured in a way that makes it easy to do this. I think it would be more disruptive to implement this than it merits, since there are (admittedly less convenient) workarounds like piping into a grep command.
