### ISSUE TITLE
Changing wrap option does not take effect immediately

### ISSUE THREAD

**Issue by gwsw** [gwsw/less#460]
Steps to reproduce:

1. Run ```seq 120 | less```
2. Type ```/13``` and press Enter. "13" in line 13 is highlighted.
3. Press ```n```. "13" in line 113 is highlighted.
4. Press ```n```. The message "Pattern not found" is displayed.
5. Enter ```--search-options=w``` and press Enter.
6. Press ```n```.

Expected: Search should wrap and show line 13.
Actual: The message "Pattern not found" is displayed.

**Comment by gwsw** [comment]
On reconsideration, I think the current behavior is fine. Changing --search-options should affect only future searches with ```/``` and ```?```, not a continued search with ```n```.

**Comment by bac0n** [comment]
... if `W` is in effect I think `n` should honor `W` for the lifetime of that "search" even if less is restarted.
