### ISSUE TITLE
"invalid search option ' '" when $LESS contains --search-options=W and it is not the last argument

### ISSUE THREAD

**Issue by yump** [gwsw/less#461]
Seems like the parser for the search options string doesn't recognize the following space as terminating the options.

Steps to reproduce:

1. Build less at the current master, 16a526030ee47d364948ac16d67b872840c32abb.
2. Run 
```
env LESS="--ignore-case --RAW-CONTROL-CHARS --LONG-PROMPT --quit-if-one-screen --use-color --incsearch --file-size --search-options=W --modelines=2" ./less /proc/cpuinfo
```
3. See error message `invalid search option ' '`

**Comment by gwsw** [comment]
I accept that this is not exactly expected behavior, but it is behaving as documented.

>Some  options like -k or -D require a string to follow the option letter.  The string for that option is considered to end when a dollar sign ($) is found.

**Comment by yump** [comment]
I believe this is also fixed by https://github.com/gwsw/less/commit/3440a1d490308042fb65c7646573694efd4ab444, same as  #495. 

Thanks for making this follow the principle of least surprise.
