### ISSUE TITLE
Enhancement: option for inhibit "done  (press RETURN)"

### ISSUE THREAD

**Issue by telychko** [gwsw/less#462]
$ less -V
less 643 (PCRE2 regular expressions)
Copyright (C) 1984-2023  Mark Nudelman

* Manual was read
* Taken a look into code

Would be great if less could have an option [here](https://github.com/gwsw/less/blob/master/lsystem.c#L189C1-L189C10) to inhibit `done...` messages.

Use case: key binding for shell routines.

**Comment by telychko** [comment]
Thank you, I'm appreciated for your great work

**Comment by elig0n** [comment]
@gwsw I already have Ctrl-P bound to 'up' under `#line-edit` in my lesskey file, is there an alternative approach besides for me to disable it ?

**Comment by gwsw** [comment]
I don't think there's a way to both have ^P be a user-defined command and also use it as the message suppression character. You will probably need to remove the ^P command from your lesskey file if you want to use ^P to suppress the done message.
