### ISSUE TITLE
Cannot search symbols @ and ! in ^R search mode (--use-backslash not affects)

### ISSUE THREAD

**Issue by telychko** [gwsw/less#463]
$ less --version
less 643 (PCRE2 regular expressions)

Cannot search @ and ! symbols in non-regexp mode:

less '+/^R@' file
It's ok as @ is the one of the search mode, but would be good that special symbols could be available via --use-backslash option.

Suggested solution:
less --use-backslash '+/^R\@' file

^R there is the one raw symbol.

**Comment by gwsw** [comment]
In 16a526030ee47d364948ac16d67b872840c32abb and later you can use the new ctrl-L search modifier to search for a search modifier character:
```
less '+/^R^L@' file
```

**Comment by telychko** [comment]
Thank you for your great work!
