### ISSUE TITLE
less (v643) is not able to operate on files residing on Linux pseudo-filesystems

### ISSUE THREAD

**Issue by ricardobranco777** [gwsw/less#465]
Using version from FreeBSD 14-STABLE: less 643 (POSIX regular expressions)

To reproduce:
`less /compat/linux/proc/cpuinfo`

**Comment by ricardobranco777** [comment]
Fix for FreeBSD: https://github.com/freebsd/freebsd-src/pull/1004

**Comment by polluks** [comment]
See also #466.

**Comment by gwsw** [comment]
Fixed in 1fafd968b48e5cea6c85f126d77071a8de707a55.
