### ISSUE TITLE
--mouse breaks click+drag selection

### ISSUE THREAD

**Issue by ivanbrennan** [gwsw/less#47]
Using the `--mouse` option, I can scroll with the mouse-wheel/trackpad (thanks for that!), but now I cannot select text.

For example, running
```sh
MANPAGER='less' man bash
```
I can click + drag with the mouse to select a region of text.

But if I add the `--mouse` option
```sh
MANPAGER='less --mouse' man bash
```
clicking + dragging with the mouse has no effect.

**Comment by ivanbrennan** [comment]
With the `--mouse` option in effect, I can click + drag the mouse to select text if I also hold down Shift. So perhaps this is the expected behavior?

**Comment by noscript** [comment]
I'm having the same issue, `--mouse` should not break the text selection.

Shift+drag is the standard behavior of most terminals to override the so called _mouse protocol_ https://invisible-island.net/xterm/manpage/xterm.html#h3-Mouse-Protocol

**Comment by gwsw** [comment]
Shift-drag will select text if the terminal supports it.
On any terminal, you can type "--mouse" to disable mouse mode and enable text selection. Another simpler way is to simply type a colon, since mouse reporting is disabled while entering text at the bottom of the screen.

**Comment by noscript** [comment]
What is mouse drag used for in less?

Would it be possible to propagate the action to terminal, if there is no other functionality assigned?

**Comment by gwsw** [comment]
Less does not use mouse drag, but it gets disabled when mouse reporting is enabled.  I do not know of a way to tell the terminal to select text.

**Comment by Ottaviocr** [comment]
I can replicate this bug/feature on FreeBSD:
<pre>
% uname -a
FreeBSD FreeBSD 12.1-RELEASE-p8 FreeBSD 12.1-RELEASE-p8 GENERIC  amd64

% /usr/local/bin/less --version
less 551 (PCRE regular expressions)

% /usr/local/bin/less --mouse /var/log/messages
</pre>

- select a block of text by left-down-clicking: doesn't work.
-  select a block of text by [SHIFT] + left-down-clicking: works

I, too, would like to know if this is a bug or intended behaviour.

**Comment by gwsw** [comment]
This behavior is determined by the terminal that you are using. It seems that most terminals don't allow selecting text while mouse reporting is enabled, but rather simply report the mouse clicks and drags to the application. Perhaps your terminal has a setting to change that behavior, but I don't believe there's any easy or portable way for less to change it.
