### ISSUE TITLE
lines get omitted randomly in --raw-control-chars mode with colored text

### ISSUE THREAD

**Issue by xuancong84** [gwsw/less#470]
When a text file contains long lines with colored text (using console escape characters), and you run `less` with `--raw-control-chars`, if you scroll down line-by-line, the display will be correct. However, if you page up/down or scroll up line-by-line, some of the lines will get omitted randomly. This occurs both with and without wrapping. For example, the following two screenshots both show running `less --raw-control-chars` on the same file.

Scrolling down line-by-line, `less` displays:
![image](https://github.com/gwsw/less/assets/10172392/2903fa90-8a3d-455d-82a9-1b1214f65c19)

Scrolling down by PageUp/PageDown or scrolling up line-by-line, `less` displays:
![image](https://github.com/gwsw/less/assets/10172392/05424891-09af-4d04-aafa-aabe409461ab)

The inconsistency might result from the heuristic estimation calculation of starting point of new data, which does not take into account of the space change when `--raw-control-chars` is enabled.

**Comment by gwsw** [comment]
Yes, this is expected and is not really fixable. When -r is in effect, less cannot keep track of the state of the screen since raw escape sequences may do unpredictable things to the terminal. The man page says:

>Warning: when the -r option is used, less cannot keep track of the actual appearance of the screen (since  this  depends  on how  the  screen responds to each type of control character). Thus, various display problems may result, such as long lines being split in the wrong place.

> USE OF THE -r OPTION IS NOT RECOMMENDED.

**Comment by xuancong84** [comment]
> Yes, this is expected and is not really fixable. When -r is in effect, less cannot keep track of the state of the screen since raw escape sequences may do unpredictable things to the terminal. The man page says:
> 
> > Warning: when the -r option is used, less cannot keep track of the actual appearance of the screen (since  this  depends  on how  the  screen responds to each type of control character). Thus, various display problems may result, such as long lines being split in the wrong place.
> 
> > USE OF THE -r OPTION IS NOT RECOMMENDED.

Nope, that kind of explanation is for lazy/lousy developers. Although it is true that you cannot track arbitrary cursor position due to the full set of control characters (which can go to beginning/end of a line, clearing of screen, page break, etc), you CAN precisely track the cursor if the text contains no special control characters other than font/color selection. And all you need to do is to set the character spacing to zero for all escape sequences controlling color and font style. In particular, **discarding all characters between `\033` and `m`** (when computing space) will do the job.

You can find more details on the escape sequence at [Wifipedia](https://en.wikipedia.org/wiki/ANSI_escape_code#Fs_Escape_sequences)

**Comment by gwsw** [comment]
If I'm understanding you correctly, you're describing the -R option. Is there something you need that -R doesn't do?

**Comment by xuancong84** [comment]
Yup, `-R` does the job, but `\r` gets displayed, so progress bars pop out messy. But it is the best we can do. Thanks!
