### ISSUE TITLE
False positive binary

### ISSUE THREAD

**Issue by polluks** [gwsw/less#475]
file seems to be smarter
```
$ file nerdfetch 
nerdfetch: POSIX shell script text executable, Unicode text, UTF-8 text, with escape sequences
$ less nerdfetch 
"nerdfetch" may be a binary file.  See it anyway? 
```
By the way you may update the year
https://github.com/polluks/less/blob/0fce351c3d49475510cc197bcaa71c77b6293b38/optfunc.c#L527

**Comment by gwsw** [comment]
nerdfetch contains some Private Use Unicode characters like U+F17C and U+E23A. I guess it depends on a custom font that includes these characters. But by default less considers all Private Use characters to be binary. You can use LESSUTFCHARDEF to override this default when you view files containing such characters.

Thanks for the reminder about the copyright date. I will update it before the next tagged release.
