### ISSUE TITLE
Hard to read blue color on black background and gnome-terminal

### ISSUE THREAD

**Issue by pacho2** [gwsw/less#479]
Hello,

I find really hard to read some files due to less using a dark blue color for variables. I can reproduce it when gnome-terminal (3.50.1) is configured with a black background. I have tried to change the color palette, but it doesn't seem to affect less colors at all. I attach a screenshot showing the issue:
![image](https://github.com/gwsw/less/assets/923400/24c6b0ab-3c96-413a-ab38-98c7e2126fb3)

On the other hand, colors used in text console are much more readable, but I don't know how to get them used when using gnome-terminal

Thanks a lot for your help

**Comment by gwsw** [comment]
Less itself does not do any syntax coloring. It seems that you are using a third-party LESSOPEN script that is adding syntax coloring. You will have to look at that script to see how to change the colors.

**Comment by pacho2** [comment]
Ah, you are right... it seems the "lesspipe" command is provided downstream at Gentoo 

I will look at it

Thanks a lot for the hint!
