### ISSUE TITLE
Feature request: Ability to set default value for the number of lines to scroll

### ISSUE THREAD

**Issue by stnrepin** [gwsw/less#48]
Hello,

Vim has the option `scroll` which sets the number of lines to scroll with `Ctrl-U` and `Ctrl-D` commands (they're identical to less's `u` and `d` commands). So, I'd like to have a similar feature in less: declare how many lines should be scrolled by `u` and `d` (by default: half a screen).

Technically, I think, we should just add a command line parameter and set `wscroll` by its value (if presented).

If this feature looks good to you I can try implementing it.

**Comment by gwsw** [comment]
The -z option sets the number of lines scrolled by the f and b commands. Is that sufficient?

**Comment by stnrepin** [comment]
Hm, I didn't somehow notice this option. Of course, `f` and `b` commands are useful with default behavior, but I think your suggestion is sufficient. Thanks :)

So, I can close the issue?

**Comment by gwsw** [comment]
Yes, please do.
