### ISSUE TITLE
# doesn't handle spaces in filenames

### ISSUE THREAD

**Issue by gregrwm** [gwsw/less#480]
less opens and displays files with one or more spaces in the filename, but # doesn't handle such filenames properly.

Try this:
echo  hi there|less
s/tmp/hi\ there
:e/tmp/hi\ there
:e-
:e#
/tmp/hi: No such file or directory  (press RETURN)

**Comment by gwsw** [comment]
Fixed in 1626d061a6af7186e861720c659ea55963c82d95.
