### ISSUE TITLE
Respect Multibyte Characters in `--rscroll` Option

### ISSUE THREAD

**Issue by 0xTadash1** [gwsw/less#483]
Currently, when multibyte characters are passed to the `--rscroll` option, the program displays `>`. 

It would be greatly appreciated if characters commonly seen on web pages, such as the ellipsis `…` (U+2026), could also be specified. :smiley:

**Comment by gwsw** [comment]
Fixed in d4b3821af218d2b8bd4353969df6fd15e5318e39.

**Comment by 0xTadash1** [comment]
Thank you!
