### ISSUE TITLE
ignore case in search for Cyrillic text

### ISSUE THREAD

**Issue by krem** [gwsw/less#485]
-i an -I options/commands have no effect for Cyrillic text (and I suppose for other non Latin too?) UTF-8 encoded.

**Comment by gwsw** [comment]
What system are you running on? These options should work for Cyrillic text if your system supports the wctype.h functions (iswupper, iswlower, towupper and towlower). You can confirm whether less can find these functions by checking the value of HAVE_WCTYPE in your defines.h.

**Comment by krem** [comment]
It's on regular PC Arch Linux. Where I should find defines.h? I'm not compiling anything - just using less from standard repo. I've tested other pagers - they do search ok.

**Comment by gwsw** [comment]
>Where I should find defines.h? I'm not compiling anything

Ah, well the defines.h question would be a question for whoever compiled the binary you are using. You might forward the question to the Arch Linux distributor, or you could download the source and try building it yourself. I have tested Cyrillic text on a Fedora distribution and the -I/-i options seem to work fine.
