### ISSUE TITLE
wait time calculation error with usleep() causes significant CPU load

### ISSUE THREAD

**Issue by lne3** [gwsw/less#489]
Hello, at https://github.com/gwsw/less/blob/812d8a5747e1504f2ce8f81640a5112f43c3a1bc/os.c#L502 the time in parameter `int ms` is in milliseconds but usleep() expects microseconds. This causes significant CPU consumption with "scroll forward" (F key) when using that code path.

**Comment by gwsw** [comment]
Thanks, fixed in a16053ea213b0f5de4efd7859c2eb593bc0ed090.
