### ISSUE TITLE
header hides search result on long lines

### ISSUE THREAD

**Issue by polluks** [gwsw/less#491]
I'm using `MANPAGER="less --header=1" man port`
<kbd>/echo</kbd>
<kbd>n</kbd><kbd>n</kbd>
```
PORT(1)                         MacPorts Manual                        PORT(1)
not commons* \)

           Note

           Special shell characters like *, \( or \) need to be escaped in
           order to be passed correctly to port.
...
```
no echo?
<kbd>k</kbd>
```
PORT(1)                         MacPorts Manual                        PORT(1)
           port echo maintainer:jberry and uninstalled and \( category:java and not commons* \)

           Note

           Special shell characters like *, \( or \) need to be escaped in
           order to be passed correctly to port.
...
```
aha!

**Comment by gwsw** [comment]
What version of less are you using? I think this is fixed in bcd42b14 (v645).

**Comment by polluks** [comment]
It's 653x.

**Comment by gwsw** [comment]
My system does not have the port command, and my man command does not accept a --header option, so I can't reproduce this exactly how you have reported it. I have attempted similar actions but still cannot reproduce. For example ```less --header=1 -x24 main.c``` and then search for "copy" works correctly. Can you provide a sample file that shows the problem?

**Comment by polluks** [comment]
Oops, of course I was using `MANPAGER="less --header=1" man port`
See https://raw.githubusercontent.com/macports/macports-base/master/doc/port.1

**Comment by gwsw** [comment]
Sorry, I'm still not able to reproduce. I downloaded the port.1 file, ran 
```nroff -man port.1 > port.man``` and then did 
```less --header=1 port.man```
If I search with ```/echo``` I see
```
PORT(1)                         MacPorts Manual                        PORT(1)
           port echo depof:mysql5
           port echo 'apache*'

       Logical operators "and", "or", "not", "!", "(" and ")" may be used to
       combine individual portnames, port glob patterns and/or
       pseudo-portnames to construct complex port-expressions that expand to
       the set of matching ports.

       For example:

           port upgrade outdated and 'py27-*'
           port echo maintainer:jberry and uninstalled and \( category:java and >

           Note
```

I'm puzzled by two things in your first screenshot: first your search seems to have found the instance of "echo" on line 135 but skipped the ones on lines 124 and 125. Second, the second line in your output (immediately after the header) is
```
not commons* \)
```
which looks the last part of line 135 after wrapping, but wrapping should always be disabled when --header is active so I don't see how you could be seeing a wrapped line.

Do you have a .lesskey file? I'm wondering if some options are set which is causing this behavior.

**Comment by polluks** [comment]
I also have an `-r`, does this change wrapping?

**Comment by gwsw** [comment]
Oh yes, if you are using -r, that's definitely going to cause problems. The man page says

> Warning: when the
              -r option is used, less cannot keep track of the actual  appear-
              ance  of  the  screen  (since this depends on how the screen re-
              sponds to each type of control character).  Thus,  various  dis-
              play  problems may result, such as long lines being split in the
              wrong place.
>
>              USE OF THE -r OPTION IS NOT RECOMMENDED.

Using -r is almost never the right thing to do. If you're using it to cause SGR sequences to be interpreted, you should use -R instead.

**Comment by polluks** [comment]
indeed
