### ISSUE TITLE
Missing help.c generation on windows

### ISSUE THREAD

**Issue by gpcancia** [gwsw/less#493]
Compiling on windows platform (Makefile.wng) the help.c is not generated (the final link fails due to "helpdata" unresolved).
Executing manually:
perl mkhelp.pl < less.hlp > help.c
the link works and less.exe is generated.

**Comment by gpcancia** [comment]
Please cancel this issue (related only to less 653), it was due to an incorrect building environment. The Makefile.wng is correct.

**Comment by avih** [comment]
For reference, the mingw `Makefile.wng` supports 3 methods of generating `help.c`: using perl (if the cmmand succeeds), else using `sh` (shell) and few posix utils like `od` and `awk`.

And finally, if that doesn't work, then one has to add manually to the makefile invocation `WINGEN=1` - which compiles a small C program which is then used instead perl or the shell utils.

(and `mkhelp.py` also exists, if one wants to generate it manually using python, though it's not attempted by the mingw makefile).
