### ISSUE TITLE
CAPS-LOCK key is added to search strings (Windows version)

### ISSUE THREAD

**Issue by msoyka-of-wharton** [gwsw/less#5]
If you're viewing a file and press slash or question mark to initiate a search and then press the CAPS-LOCK key while entering the search string, two characters are displayed and become part of the search string.  Those two characters are displayed as "alpha" (code \340) and "colon" (code \072).  The two characters must be backspaced-over to erase them otherwise the search will fail.  

On a PC, the CAPS-LOCK key generates a two-character scancode: \000 followed by \072.  This sequence is defined in the file pckeys.h but is never referenced.  The leading zero is replaced by \340 in function "getchr".  

I've observed this behavior in Windows XP 32-bit and Windows 10 64-bit apps built using MingW.  I suspect this is a problem for all Windows-based compilers for which MSDOS_COMPILER==WIN32C.

**Comment by gwsw** [comment]
Fixed in v539.
