### ISSUE TITLE
s command asks for filename even when it knows it will reject it

### ISSUE THREAD

**Issue by subrook** [gwsw/less#50]
As documented in `less 551`, the `s` command "only works if the input is a pipe, not an ordinary file."  However, when viewing an ordinary file, typing `s` gives the prompt `log file:` and accepts a filename.  Only after the filename is entered does it say `Input is not a pipe`.  There is no need to prompt for and allow the user to enter a filename that will only be rejected; whether input is a pipe is known the moment the user presses `s`.

**Comment by gwsw** [comment]
Good point. This is fixed in c25faac53b05b921e42788d1f0cbc4f932e2cb1d.
