### ISSUE TITLE
Wrong warning when running on Lear Siegler ADM-5 terminal

### ISSUE THREAD

**Issue by fstark** [gwsw/less#505]
(Issue reproduced on Linux)

How to reproduce:
Enter ``TERM=adm5 less``

Expected Result:
```
Missing filename ("less --help" for help)
```

Result:
```
WARNING: terminal is not fully functional
Missing filename ("less --help" for help)
```

There is a spurious warning that the terminal is not fully functional.

**Comment by gwsw** [comment]
Fixed in deb498116bd318fc40cee18479413f39e12a6d28.
