### ISSUE TITLE
less-654 does not display ISO-8859-1 characters C0...FF

### ISSUE THREAD

**Issue by PetriKaukasoina** [gwsw/less#510]
Using a locale with ISO-8859-1 character map (fi_FI). Characters between C0...FF don't display. For example the last characters of the Finnish alphabet: XYZÅÄÖ

```
echo XYZÅÄÖ|less
less-654 displays: XYZ<C5><C4><D6>         (the hex codes in reverse colors)
less-653 displays: XYZÅÄÖ

```
LESSCHARSET is not set, but setting LESSCHARSET=iso8859 does not change anything.

**Comment by gwsw** [comment]
This sounds like the same as #508. Can you confirm whether d5bf86410248fe0eac1733df3ce52f1fddafc710 fixes this problem?

**Comment by PetriKaukasoina** [comment]
Yes, thanks. It fixes the problem.
