### ISSUE TITLE
weird --header behavior

### ISSUE THREAD

**Issue by elig0n** [gwsw/less#528]
in 1649cc3:

using the command `--header` when scrolling past the first page of an open file, the line argument i.e. 2 will use the first 2 lines of the current page and not from the start of the file like it is in previous releases. Also, scrolling back before those lines becomes impossible.

**Comment by gwsw** [comment]
This is a deliberate change, so that a line or lines other than the beginning of the file can be used as header lines (see #436). If you want the first line in the file to be the header you can just press ```g``` before entering the ```--header``` command. See the man page, which says

>The  first header line is set to line number N in the
              file.  If N is empty or missing, it is taken to be the number  of  the  line  **currently
              displayed in the first line of the screen** (if the --header command has been issued from
              within less), or 1 (if the --header option has been given on the  command  line).
