### ISSUE TITLE
Searching fails after leaving follow mode with CTRL-C.

### ISSUE THREAD

**Issue by GWHAYWOOD** [gwsw/less#53]
My use case is mail server logs, which here tend to be very long.  Typically I'll run less on the logfile, using 'f' to tail the log.  If I stop tailing the log by pressing CTRL-C and immediately search backwards for something (using the '?' key) then

(1) less claims that the string was not found, even though it is there, and
(2) less replaces the first character on every line of the display with a tilde character.

If I then repeat these operations (tail the file, CTRL-C, search backwards for the same string) the string is then found and the erroneous tilde characters are corrected.

This issue is still present in the current beta release.
Please see my mail to you of 19th December 2017, Subject "Bug 292."

[less_bug_report.txt](https://github.com/gwsw/less/files/4403449/less_bug_report.txt)

**Comment by gwsw** [comment]
Can you give a step-by-step procedure to reproduce this? I have not been able to reproduce it. I tried doing "less main.c", then "G" to go to the end of the file, then "?quit" to search backwards, and it works fine. I also tried "F" (which I think you meant in your second sentence rather than "f") and ctrl-C and then the search, but I still do not see the effect that you describe.

**Comment by GWHAYWOOD** [comment]
I've experimented a little and I think you need (1) to view a file that's large enough for less to say that it's "calculating line numbers" and (2) to hit CTRL-C before it finishes doing that, so that it says "line numbers turned off".  To save typing I normally alias 'li' to 'less -S' and I wondered if it needed the '-S' to be on the command line but I tried it with just 'less filename' and the same thing happens.

Yes you're right, I meant 'F' not 'f' - my fingers just type it without my knowing what I've typed...

Thanks for looking at this!

**Comment by gwsw** [comment]
I believe this is now fixed in 87599e930a055d5ee92630da8380ade18ebfa24c.
Could you try the top of tree in github and confirm whether it fixes your issues?

**Comment by GWHAYWOOD** [comment]
I grabbed the Zip file and built from it what claims to be version 561x.

The issue seems to be resolved, thenk you very much!
