### ISSUE TITLE
Use TAB in -- command to complete partial option name

### ISSUE THREAD

**Issue by gwsw** [gwsw/less#531]
When setting options with long names, it would be nice to not have to type the whole name. TAB could cycle through option names in the ```--``` command, similar to the way it works on filenames in the ```:e``` command.

**Comment by polluks** [comment]
Warp has already partial supported completion for less
https://docs.warp.dev/features/command-completions/completions#supported-completion-specs

**Comment by gwsw** [comment]
Thanks. To be clear, this issue is about adding TAB completion to the ```--``` command inside less, not to the shell, since less cannot affect how the user's shell behaves.

**Comment by polluks** [comment]
Warp is not another shell, but a "modern, Rust-based terminal with AI built. Completions will suggest commands, **option names**, and path parameters".
2024: I don't know how this works, it's AI.

**Comment by gwsw** [comment]
Implemented in f800e8c36ea2efec420988eeb9aed447b18387b1 in the post659 branch.
