### ISSUE TITLE
less -i with \S in the pattern becomes case sensitive

### ISSUE THREAD

**Issue by gbwey9** [gwsw/less#534]
**Reproduction steps:**

1. less --version should be less 643 (PCRE2 regular expressions)
2. less -ip "\Soving" --help

**Expected result:** 

should match "MOVING" in the less help screen

**Additional information:**

these two searches find the match
less -ip "[^\s]oving" --help
less -Ip "\Soving" --help

**Comment by gbwey9** [comment]
**Additional Note:**
The following don't find a match but should:

- less -ip "\Soving" --help
- less -ip "\Doving" --help
- less -ip "\Wmoving" --help

The following do match as expected:

- less -ip "[^\s]oving" --help
- less -ip "[^\d]oving" --help
- less -ip "[^\w]moving" --help

**Comment by gwsw** [comment]
Technically this is in conformance with what the man page says about -i, although I agree that it is not expected nor desirable behavior.

>This option is ignored if any uppercase letters appear  in  the  search  pattern;  in  other
words, if a pattern contains uppercase letters, then that search does not ignore case.

You can work around the issue by using -I rather than -i.

**Comment by avih** [comment]
> This option is ignored if any uppercase letters appear in the search pattern; in other
> words, if a pattern contains uppercase letters, then that search does not ignore case

So a preferred behavior would be that the 2nd part says something like this?

"if a pattern contains uppercase letters which are matched literally, then that search does not ignore case"

Though I'm guessing the RE API doesn't have something to test that, right? and manually parsing the RE to detect it is not easy (except simple cases) and not worth it?

Maybe there's room to support case-[in]sensitivity modifier to search, similar to how ^R after `/` disabled RE search?

**Comment by gwsw** [comment]
Less supports 8 different regex libraries. As far as I know, none of them support finding "literal" uppercase chars as opposed to uppercase metachars in the pattern. I don't think it would be easy for less to do this itself, especially in a way that works for all 8 libraries.

There is (sort of) already a modifier to make a search case-insensitive: type ```-!I``` before the search. It does affect all subsequent searches though, not just the current one.

**Comment by gbwey9** [comment]
Thanks for the explaining the issue.
