### ISSUE TITLE
less output containing "^G" after clickable texts (ArchLinux-Alacritty)

### ISSUE THREAD

**Issue by DanielKaleby** [gwsw/less#535]
When I try to use less to display a file that contains clickable text (using the ANSI code \x1B]8), the characters "^G" are always displayed at the end of these texts (the same happens in bat, which from what I I understand you use less as a pager), this only happens with the "links", the bold and italic texts are displayed correctly, I managed to solve this using the `--raw-control-chars` flag but this brought another problem , in which some lines of the displayed file simply disappear, and when I scroll down and then up, these lines start to appear, but in place of others (it's difficult to explain, but it's like that)
For the other ansi formatting to work I needed to export `export LESSUTFCHARDEF=E000-F8FF:p,F0000-FFFFD:p,100000-10FFFD:p` so I imagine the problem is that something else is missing within this variable, but what exactly?
`more` can display everything correctly but I really like how `less` does things and I wanted to be able to work around this problem and use it.

**Comment by avih** [comment]
Which version of less you're using?

Can you provide a sample text file with such links (it's called OSC 8) where it doesn't work correctly?

Can you please also provide a screenshot of it displaying incorrectly?

**Comment by DanielKaleby** [comment]
![20240629_131325](https://github.com/gwsw/less/assets/74084485/bba4792a-0722-4300-9664-5a24255834ca)

```
[~]$ less --version
less 643 (PCRE2 regular expressions)
Copyright (C) 1984-2023  Mark Nudelman
```

I use arch, and I tried doing this in alacritty and kitty.

It does not directly show a file as I summarized in the first text, but rather the content of a "formatted" file (.md), so that hyperlinks `[title](url)` are treated by this regex: `s/\[(.+?)\]\((.+?)\)/\x1B]8;;$2\a\e[4m$1\e[24m\a\x1B]8;;\a/g;` that is, it is text that must appear in bold and clickable.
I think it would be a lot to send here to have the full context (or not?).

**Comment by avih** [comment]
You can zip the file and attach the zip.

**Comment by gwsw** [comment]
less-643 does not support OSC 8 sequences. You should try the current beta less-658.

**Comment by DanielKaleby** [comment]
> less-643 does not support OSC 8 sequences. You should try the current beta less-658. Also note that incorrect display with -r is expected and documented. Using -r is not recommended except in very limited situations.

Thank you, (I was separating the content of the document covered and the excerpt of the script that I made to send to the other friend who asked) I will try with this version that you mentioned.
I'll let you know here when I get it
This thing about terminal formatting and escape sequences is very confusing (at least for someone with my IQ), lol

**Comment by avih** [comment]
> less-643 does not support OSC 8 sequences

Well, for me OSC 8 does work for me in less 643. It does include commit c6a3a48 before v623.

And with `less -R` (not -r) in v643 it does work correctlly for me in both alacritty and kitty. I.e. the links are highlighted correctly, I don't get a final ^G like OP has.

Also, I tested with OSC 8 termination of both ESC \ and ^G. Here's my test file:
[osc8.zip](https://github.com/user-attachments/files/16041655/osc8.zip)

And here's how it looks in alacritty 0.13.2 (in Alpine linux 3.20.1):
![less-643-alacrotty-osc8](https://github.com/gwsw/less/assets/2164962/cf8d35f8-87a2-486d-9f09-1c5e00071b25)

So again, can you please provide a sample file where this issue happens?

**Comment by gwsw** [comment]
Oh, that's right, I misspoke. less-658 added the ^O commands to navigate and open OSC8 sequences, but less-643 did have support for just passing through the sequences to the terminal when -R was in effect.  I agree, a sample file would be useful to see.

**Comment by avih** [comment]
> hyperlinks `[title](url)` are treated by this regex: `s/\[(.+?)\]\((.+?)\)/\x1B]8;;$2\a\e[4m$1\e[24m\a\x1B]8;;\a/g;`

This regex is broken. It has an extra `\a` (which is BEL, which is ^G), just after `\e[24m`:
original:
```
s/\[(.+?)\]\((.+?)\)/\x1B]8;;$2\a\e[4m$1\e[24m\a\x1B]8;;\a/g;
```
fixed:
```
s/\[(.+?)\]\((.+?)\)/\x1B]8;;$2\a\e[4m$1\e[24m\x1B]8;;\a/g;
```

**Comment by DanielKaleby** [comment]
> > hyperlinks `[title](url)` are treated by this regex: `s/\[(.+?)\]\((.+?)\)/\x1B]8;;$2\a\e[4m$1\e[24m\a\x1B]8;;\a/g;`  that is, it is text that must appear in bold and clickable.
> 
> It's not bold, it's underline (SGR 4 to start, SGR 24 to end).
> 
> But the issue is that this regex is broken. It adds an extra `\a` (which is BEL, which is ^G), just after `\e[24m`, and which "less" displays correctly as ^G.
> 
> original:
> 
> ```
> s/\[(.+?)\]\((.+?)\)/\x1B]8;;$2\a\e[4m$1\e[24m\a\x1B]8;;\a/g;
> ```
> 
> fixed:
> 
> ```
> s/\[(.+?)\]\((.+?)\)/\x1B]8;;$2\a\e[4m$1\e[24m\x1B]8;;\a/g;
> ```

Yes, it is underlined, I confused it in the other comment because the md images appear as bold and underlined, while the hyperlinks are underlined.
This corrected regex doesn't seem to make a difference.
The problem with `-r` occurs with some files and not others, so the problem is probably in the rest of my script and outside the scope of less, but here is a zip of my project (just an update really and show you through Curious, I don't expect anyone to solve it besides me. I tried to isolate just the code that mattered but I wasn't able to reproduce the problem correctly, so I zipped everything together, the changes related to less are in the 'printfile' function).
[issue.zip](https://github.com/user-attachments/files/16042015/issue.zip)

For the pager to be active you have to pass the flag ´-p´

[in this example folder the file "README.md" is the only one where the problem occurs]

And I'm running the script like this: `sh script.sh -p README* sampleREADME*`

I've been trying to get this to work for days, and I don't think I'll get anywhere so I'm going to leave this aside and add other easier functions to my script..

(If you want to know more about this script, there are some details [here](redd.it/1dhgupj).)

**Comment by avih** [comment]
> This corrected regex doesn't seem to make a difference.

It definitely does make a difference, you just need to test it with a minimal test case, like this:
![less-fixed](https://github.com/gwsw/less/assets/2164962/2bf82014-fc7f-4226-92dd-8f048d096fa9)

But you're correct that this is not an issue of "less", and you should continue debugging it on your own.

**Comment by gwsw** [comment]
>The problem with -r occurs with some files and not others

Before any further debugging, you should stop using -r and replace it with -R. As the man page notes, using -r can produce erroneous output. Trying to debug your own display problems when using -r which can introduce its own display problems is going to be very difficult and confusing.

**Comment by DanielKaleby** [comment]
> But you're correct that this is not an issue of "less", and you should continue debugging it on your own.

Thanks for your attention, I corrected the regex that the script uses and I'm going to use `more` for now as it didn't present any problems, after finishing the other planned features I'll try working with less/bat again.

**Comment by DanielKaleby** [comment]
> Before any further debugging, you should stop using -r and replace it with -R. As the man page notes, using -r can produce erroneous output. Trying to debug your own display problems when using -r which can introduce its own display problems is going to be very difficult and confusing.

Thank you very much! In fact, declaring that variable to make all unicode characters displayed and using `-R` in place of `-r` everything seems to work as it should.
