### ISSUE TITLE
gpg: BAD signature.

### ISSUE THREAD

**Issue by Achaean** [gwsw/less#537]
I downloaded both files with Firefox.
```
>ls
total 560K
4.0K less-661.sig  556K less-661.tar.gz
>
```
and the archive seems to be OK.
```
>file less-661.tar.gz
less-661.tar.gz: gzip compressed data, from Unix, original size 648198
>
```
However:
```
>gpg --verify less-661.sig less-661.tar.gz
gpg: Signature made Sat Jun 29 20:16:20 2024 EEST
gpg:                using DSA key F153A7C833235259
gpg: BAD signature from "Mark Nudelman <markn@greenwoodsoftware.com>" [unknown]
>
```

**Comment by gwsw** [comment]
This is most likely a Firefox bug. See #518. You can confirm by uncompressing the file; you will probably find that the result is still compressed, and that it will then pass the signature check.

**Comment by Achaean** [comment]
Indeed, it seems to be a Firefox problem.
It is not unzipped, but somehow it downloaded corrupted.

I redownloaded it (with Chromium this time), and the problem got away.
**THANKS!!!**  :-)
