### ISSUE TITLE
lesstest behavior with /dev/pts/* 

### ISSUE THREAD

**Issue by sumitradawn** [gwsw/less#548]
Hello community members, 

I am trying to port less-661 in AIX OS and observed that lesstest application is getting hanged. 
For debugging, I have added some print statement and  below behaviour is observed.
In method open_tty() .
1. code is trying to open /dev/stdin which is getting failed because in AIX , this device file is not present.
2.   As a fall back , code is trying to open the device (/dev/pts/X) which is returned from ttyname() and this is getting passed.

But further down the line, read on the above file handle is getting hanged .

So I was thinking to understand the behaviour of this under Linux, so I made the changes captured in attached patch file.  Using this change, I observed the same behaviour compared to AIX and lesstest is getting hanged.

Below log is captured in file /tmp/less.log after applying the attached patch.
```
main argc:4
argv[0]:/home/buildusr/sumitra/Less/less/less
argv[1]:--tty
argv[2]:/dev/dummy
argv[3]:chinese1
Post fd assignment in open_tty:is_lesstest is true: ttyin_name:/dev/dummy , -1
dev:/dev/pts/1
fd:7
```

I wanted to hear form community developers about this behavior.  
Let me know you input/suggestion. 
[less_diff.patch](https://github.com/user-attachments/files/16378533/less_diff.patch)

**Comment by gwsw** [comment]
As explained in lesstest/README, lesstest creates a test environment in which an instance of less runs, with its normal tty input replaced by a pipe with its write end opened by the lesstest program. In less, the read end of the pipe is stdin, so the normal fallbacks in open_tty that try real tty devices won't work when less is run within the lesstest environment. Does AIX have any named device that refers to stdin? If not, perhaps you could replace the ```open_tty_device``` in ttyin.c line 72 with just ```fd = 0;```. I'm not positive that this will work; it's just the first idea that occurs to me.

**Comment by sumitradawn** [comment]
The tests are now passing after I changed the open_tty_device in ttyin.c to fd = 0, which I have patched and attached below. If I should raise a PR for the same, please let me know.
[lesstest_diff.patch](https://github.com/user-attachments/files/16390451/lesstest_diff.patch)

**Comment by gwsw** [comment]
I've implemented this slightly differently in 2453357fb9170c5efad17420b2c6681929a6d32d. This will work for any system that does not support /dev/stdin, not only AIX.

**Comment by avih** [comment]
Is the test supposed to run on windows too? Clearly the windows makefiles dont't have it, but if there was a `open_tty_device` which returns false (I _think_ it doesn't exist currently for windows), then should it work theoretically, if someone adapted the makefile?

**Comment by gwsw** [comment]
I'm not sure. I designed the whole thing for Linux. It uses several Linux features that I'm not sure would work on Windows, like fork, execve, pipes, signals, sigaction, etc. If it worked on Windows it would be a pleasant surprise but it is not intentional.

**Comment by avih** [comment]
> It uses several Linux features that I'm not sure would work on Windows, like fork, execve, pipes, signals, sigaction, etc.

Yeah, by this desciption I doubt it would work without significant effort...

**Comment by avih** [comment]
> Thank you for the update. May I know when this change will be part of master?

After the bugfix release for v661, which should hopefully happen in the next few weeks or less.

**Comment by sumitradawn** [comment]
> > Thank you for the update. May I know when this change will be part of master?
> 
> After the bugfix release for v661, which should hopefully happen in the next few weeks or less.

Okay, Thank you for the information.

**Comment by sumitradawn** [comment]
Fix is identified and will be part of next release , so closing this issue
