### ISSUE TITLE
Adding `#stop` prevents custom keybindings from working

### ISSUE THREAD

**Issue by joelim-work** [gwsw/less#551]
With the following `lesskey` file, custom keybindings work as expected:

```
#command
x quit
```

But after adding `#stop` to disable the _default keybindings_, the custom keybindings don't work instead:

```
#command
x quit
#stop
```

Doing a bisect indicates that the issue starts from 09377f7.

**Comment by gwsw** [comment]
Fixed in 2526c72b1212b2a1f34bdda88a93b0c7f7b4a16a.

**Comment by joelim-work** [comment]
Tested with your changes and `#stop` works for me now. Thanks!
