### ISSUE TITLE
Less will not read any more of the input after interrupting the F command.

### ISSUE THREAD

**Issue by chrispurnell** [gwsw/less#553]
Interrupting the F command with Control-X causes less to stop reading the input.
Using the F command again works but trying to scroll down will not get anything new.

**Comment by gwsw** [comment]
Fixed in 99d2557a9ab078191e0b05e7ac4199aa3b068e70. This restores behavior that was present in less-643; that is, the new content is viewable after entering the ```R``` command, and only if the file is not a pipe.

**Comment by piotr-dobrogost** [comment]
Why is the `R` command in this case necessary?
Shouldn't an attempt to scroll past the end of a file automatically refresh the file size in case it has changed in the meantime?

**Comment by gwsw** [comment]
Good question. I started to explain why it doesn't do that, but my explanation wasn't convincing even to me. I've made a change in 9933cf193898275b3a6209029d99e1ef5482fa6c in the post659 branch that should make the R command unnecessary. It changes a low-level part of the code, so it's possible it introduces some regression but so far my testing has not revealed any problems.

**Comment by piotr-dobrogost** [comment]
> I've made a change in [9933cf1](https://github.com/gwsw/less/commit/9933cf193898275b3a6209029d99e1ef5482fa6c) in the post659 branch that should make the R command unnecessary.

Thank you!
