### ISSUE TITLE
Make --quit-if-one-screen believe the screen is smaller with multi-line prompts

### ISSUE THREAD

**Issue by vincentbernat** [gwsw/less#559]
Hey!

When using `less -FX` and the file is a bit less than one screen long, the first line disappear due to the prompt pushing it up when we have a multi-line prompt, so we have to scroll back a bit to see it. For example, I have a 3-line prompt and doing that push the first line away from the screen:

```
less -f -FX <(for i in $(seq 1 $((LINES-2))); do echo $i; done)
```

I can workaround the issue with `LESS_LINES`, but I would like to keep everything else unchanged. Ideally, there should be a way to teach less that for `--quit-if-on-screen`, it should assume the screen is smaller than it is when testing the exit condition, but for everything else, nothing should change.

**Comment by gwsw** [comment]
I think this is the same issue as #514.

**Comment by vincentbernat** [comment]
That's right. I didn't find this PR as I only looked at the issues! :-/
