### ISSUE TITLE
Less don't respond to interrupt

### ISSUE THREAD

**Issue by Gurran** [gwsw/less#56]
If I launch less with
`less +F {somefile}`

Less jumps to the bottom of the file and waits for interrupt.
When i press `Ctrl+c` nothing happends. `Ctrl+d` does nothing, neighter does `q`:

Key kombinations I've tried:
`Ctrl+c`
`Ctrl+Shift+c`
`Ctrl+d`
`Ctrl+Shift+d`
`q`
`Q`
`f`
`Shift+F`

Less version 551

**Comment by gwsw** [comment]
I cannot reproduce this on Linux, Windows/cygwin or MacOS. What type of operating system are you running on? If you run "stty -a", does it show that your intr character is ^C?

**Comment by Gurran** [comment]
I just figured it out after pulling my hair out for two days. 

My terminal swallowed the input. And I didn't realize this because I tried a different computer (a mac) and got the same behavior.

I now realize that Macs use Command + C. And that my terminal (Alacritty) swallowed the input.

Sorry for bothering you.
