### ISSUE TITLE
Issue in less man pages

### ISSUE THREAD

**Issue by hmartink** [gwsw/less#564]
'''Dear less maintainer,
the manpage-l10n project maintains a large number of translations of
man pages both from a large variety of sources (including less) as
well for a large variety of target languages.

During their work translators notice different possible issues in the
original (english) man pages. Sometimes this is a straightforward
typo, sometimes a hard to read sentence, sometimes this is a
convention not held up and sometimes we simply do not understand the
original.

We use several distributions as sources and update regularly (at
least every 2 month). This means we are fairly recent (some
distributions like archlinux also update frequently) but might miss
the latest upstream version once in a while, so the error might be
already fixed. We apologize and ask you to close the issue immediately
if this should be the case, but given the huge volume of projects and
the very limited number of volunteers we are not able to double check
each and every issue.

Secondly we translators see the manpages in the neutral po format,
i.e. converted and harmonized, but not the original source (be it man,
groff, xml or other). So we cannot provide a true patch (where
possible), but only an approximation which you need to convert into
your source format.

Finally the issues I'm reporting have accumulated over time and are
not always discovered by me, so sometimes my description of the
problem my be a bit limited - do not hesitate to ask so we can clarify
them.

I'm now reporting the errors for your project. If future reports
should use another channel, please let me know.

Man page: less.1
Issue:    B<[-b >I<space>B<] → B<[-b >I<buffer>B<]

"B<[-b >I<space\\/>B<] [-h >I<lines\\/>B<] [-j >I<line\\/>B<] [-k "
">I<keyfile\\/>B<]>"
--
Man page: less.1
Issue:    --intr → B<--intr>

"When the \"Waiting for data\" message is displayed, such as while in the F "
"command, pressing \\(haX will stop B<less> from waiting and return to a "
"prompt.  This may cause B<less> to think that the file ends at the current "
"position, so it may be necessary to use the R or F command to see more "
"data.  The --intr option can be used to specify a different character to use "
"instead of \\(haX.  This command works only on systems that support the "
"B<poll>(2)  function.  On systems without B<poll>(2), the interrupt "
"character (usually \\(haC) can be used instead."
--
Man page: less.1
Issue:    Remove closing bracket and full stop

"https://en.wikipedia.org/wiki/ANSI_escape_code#SGR)."
--
Man page: less.1
Issue:    less → B<less>

"Causes less to interpret the specified text as the contents of a "
"B<lesskey>(1)  source file.  In the text, B<lesskey> lines may be separated "
"by either newlines as usual, or by semicolons.  A literal semicolon may be "
"represented by a backslash followed by a semicolon."
--
Man page: less.1
Issue 1:  -U option → B<-U> option
Issue 2:  -r option → B<-r> option

"Causes \"raw\" control characters to be displayed.  The default is to "
"display control characters using the caret notation; for example, a control-"
"A (octal 001) is displayed as \"\\(haA\" (with some exceptions as described "
"under the -U option).  Warning: when the -r option is used, B<less> cannot "
"keep track of the actual appearance of the screen (since this depends on how "
"the screen responds to each type of control character).  Thus, various "
"display problems may result, such as long lines being split in the wrong "
"place."
--
Man page: less.1
Issue:    B<nroff> → B<nroff>(1)

"Causes consecutive blank lines to be squeezed into a single blank line.  "
"This is useful when viewing B<nroff> output."
--
Man page: less.1
Issue:    --wordwrap → B<--wordwrap>

"Causes lines longer than the screen width to be chopped (truncated) rather "
"than wrapped.  That is, the portion of a long line that does not fit in the "
"screen width is not displayed until you press RIGHT-ARROW.  The default is "
"to wrap long lines; that is, display the remainder on the next line.  See "
"also the --wordwrap option."
--
Man page: less.1
Issue:    specifying -t → specifying B<-t>

"The -t option may also be specified from within B<less> (using the - "
"command) as a way of examining a new file.  The command \":t\" is equivalent "
"to specifying -t from within B<less>."
--
Man page: less.1
Issue:    --file-size → B<--file-size>

"If --file-size is specified, B<less> will determine the size of the file "
"immediately after opening the file.  Then the \"=\" command will display the "
"number of lines in the file.  Normally this is not done, because it can be "
"slow if the input file is non-seekable (such as a pipe) and is large."
--
Man page: less.1
Issue:    ASCII → B<ASCII>(7)

"Use the character I<c> instead of \\(haX to interrupt a read when the "
"\"Waiting for data\" message is displayed.  I<c> must be an ASCII character; "
"that is, one with a value between 1 and 127 inclusive.  A caret followed by "
"a single character can be used to specify a control character."
--
Man page: less.1
Issue:    the -N option → the option B<-N>

"Sets the minimum width of the line number field when the -N option is in "
"effect to I<n> characters.  The default is 7."
--
Man page: less.1
Issue:    --tabs → B<--tabs>

"A modeline contains, anywhere in the line, a program name (\"vi\", \"vim\", "
"\"ex\", or \"less\"), followed by a colon, possibly followed by the word "
"\"set\", and finally followed by zero or more option settings.  If the word "
"\"set\" is used, option settings are separated by spaces, and end at the "
"first colon.  If the word \"set\" is not used, option settings may be "
"separated by either spaces or colons.  The word \"set\" is required if the "
"program name is \"less\" but optional if any of the other three names are "
"used.  If any option setting is of the form \"tabstop=I<n>\" or \"ts=I<n>\", "
"then tab stops are automatically set as if --tabs=I<n> had been given.  See "
"the --tabs description for acceptable values of I<n>."
--
Man page: less.1
Issue 1:  markup of --wheel-lines
Issue 2:  as if by the \\(haO\\(haN command → as if the \\(haO\\(haN command had been issued
Issue 3:  as if by the \\(haO\\(haO command. → as if the \\(haO\\(haO command had been issued.

"Enables mouse input: scrolling the mouse wheel down moves forward in the "
"file, scrolling the mouse wheel up moves backwards in the file, left-click "
"sets the \"#\" mark to the line where the mouse is clicked, and right-click "
"(or any other) returns to the \"#\" mark position.  If a left-click is "
"performed with the mouse cursor on an OSC 8 hyperlink, the hyperlink is "
"selected as if by the \\(haO\\(haN command.  If a left-click is performed "
"with the mouse cursor on an OSC 8 hyperlink which is already selected, the "
"hyperlink is opened as if by the \\(haO\\(haO command.  The number of lines "
"to scroll when the wheel is moved can be set by the --wheel-lines option.  "
"Mouse input works only on terminals which support X11 mouse reporting, and "
"on the Windows version of B<less>."
--
Man page: less.1
Issue 1:  -u → B<-u>
Issue 2:  -U → B<-U>

"If set, backspaces are handled as if neither the -u option nor the -U option "
"were set.  That is, a backspace adjacent to an underscore causes text to be "
"displayed in underline mode, and a backspace between identical characters "
"cause text to be displayed in boldface mode.  This option overrides the -u "
"and -U options, so that display of backspaces can be controlled separate "
"from tabs and carriage returns.  If not set, backspace display is controlled "
"by the -u and -U options."

"If set, carriage returns are handled as if neither the -u option nor the -U "
"option were set.  That is, a carriage return immediately before a newline is "
"deleted.  This option overrides the -u and -U options, so that display of "
"carriage returns can be controlled separate from that of backspaces and "
"tabs.  If not set, carriage return display is controlled by the -u and -U "
"options."
--
Man page: less.1
Issue:    -U → B<-U>

"If set, backspaces are handled as if the -U option were set; that is "
"backspaces are treated as control characters."

"If set, carriage returns are handled as if the -U option were set; that is "
"carriage returns are treated as control characters."

"If set, tabs are handled as if the -U option were set; that is tabs are "
"treated as control characters."
--
Man page: less.1
Issue 1:  -U → B<-U>
Issue 2: options. → option.

"If set, tabs are handled as if the -U option were not set.  That is, tabs "
"are expanded to spaces.  This option overrides the -U option, so that "
"display of tabs can be controlled separate from that of backspaces and "
"carriage returns.  If not set, tab display is controlled by the -U options."
--
Man page: less.1
Issue:    --search-options=W → B<--search-options>=I<W>

"Sets default search modifiers.  The value is a string of one or more of the "
"characters E, F, K, N, R or W.  Setting any of these has the same effect as "
"typing that control character at the beginning of every search pattern.  For "
"example, setting --search-options=W is the same as typing \\(haW at the "
"beginning of every pattern.  The value may also contain a digit between 1 "
"and 5, which has the same effect as typing \\(haS followed by that digit at "
"the beginning of every search pattern.  The value \"-\" disables all default "
"search modifiers."
--
Man page: less.1
Issue:    B<setlocale> → B<setlocale>(3)

"If that string is not found, but your system supports the B<setlocale> "
"interface, B<less> will use setlocale to determine the character set.  "
"setlocale is controlled by setting the LANG or LC_CTYPE environment "
"variables."
--
Man page: less.1
Issue 1:  -e → B<-e>
Issue 2:  -E → B<-E>

"The -e option works differently.  If the -e option is not set, B<less> "
"behaves as if the -e option were set.  If the -e option is set, B<less> "
"behaves as if the -E option were set."
--
Man page: less.1
Issue:    -p → B<-p>

"The parameter to the -p option is taken to be a B<less> command rather than "
"a search pattern."
--
Man page: less.1
Issue:    -t → B<-t>

"Name of the command used by the -t option to find global tags.  Normally "
"should be set to \"global\" if your system has the B<global>(1)  command.  "
"If not set, global tags are not used."
--
--
Man page: less.1
Issue:    sets → which sets

"Where \"xxx\" is a URI scheme such as \"http\" or \"file\", sets an OSC 8 "
"handler for opening OSC 8 links containing a URI with that scheme."
--
Man page: less.1
Issue:    B<more> → B<more>(1)

"Options which are passed to B<less> automatically when running in B<more>-"
"compatible mode."
--
Man page: less.1
Issue:    B<lesskey> → I<lesskey>

msgid "Possible location of the B<lesskey> file; see the KEY BINDINGS section."
--
Man page: lessecho.1
Issue:    B<less> → B<less>(1)

"B<lessecho> is a program that simply echos its arguments on standard "
"output.  But any metacharacter in the output is preceded by an \"escape\" "
"character, which by default is a backslash.  B<lessecho> is invoked "
"internally by B<less>, and is not intended to be used directly by humans."
--
Man page: lessecho.1
Issue:    -e- → B<-e->

"Specifies \"I<x>\", rather than double-quote, to be the open quote "
"character, which is used if the -e- option is specified."
--
Man page: lesskey.1
Issue:    There's no such list

"Whitespace is any sequence of one or more spaces and/or tabs.  The I<string> "
"is the command key(s) which invoke the action.  The I<string> may be a "
"single command key, or a sequence of up to 15 keys.  The I<action> is the "
"name of the less action, from the list below.  The characters in the "
"I<string> may appear literally, or be prefixed by a caret to indicate a "
"control key.  A backslash followed by one to three octal digits may be used "
"to specify a character by its octal value.  A backslash followed by certain "
"characters specifies input characters as follows:"
--
Man page: lesskey.1
Issue:    B<less> → B<less>(1)

"The following input file describes the set of default command keys used by "
"B<less>.  Documentation on each command can be found in the B<less> man "
"page, under the key sequence which invokes the command."
--
Man page: lesskey.1
Issue 1:  -i → B<-i>
Issue 2:  -S → B<-S>
Issue 3:  B<less> → B<less>(1)
Issue 4: --color → B<--color>

"The following input file sets the -i and -S options when B<less> is run and, "
"on version 595 and higher, adds a --color option."
--
Man page: lesspipe.1
Issue 1:  file → B<file>(1)
Issue 2:  I<file> → B<file>(1)
Issue 3:  I<iconv> → B<iconv>(1)

"If the file utility reports text with an encoding different from the one "
"used in the terminal then the text will be transformed using I<iconv> into "
"the default encoding. This does assume the I<file> command gets the file "
"encoding right, which can be wrong in some situations. An appended colon to "
"the file name does suppress the conversion."
--
Man page: lesspipe.1
Issue:    less → B<less>(1)

"The filter is normally not called if input is piped to less as in"
--
Man page: lesspipe.1
Issue 1:  less → B<less>(1)
Issue 2:  B<LESSOPEN> is a variable, how to start it…? Should be »by prepending I<|-> to the B<LESSPOPEN> environment variable«

"As described in the man page of less, the filtering in a pipe can however be "
"forced by starting B<LESSOPEN> with the characters I<|->."
msgstr ""
"Wie in der Handbuchseite zu B<less> beschrieben, können Sie die Filterung in "
"einer Pipe dennoch aktivieren, wenn Sie der Variable B<LESSOPEN> die Zeichen "
"I<|-> voranstellen."
--
Man page: lesspipe.1
Issue:    lesspipe.sh → B<lesspipe.sh>

"B<LESSOPEN> starting with the two characters I<||> to handle empty files and "
"command errors is implemented only partly, usually on failures of commands "
"within B<lesspipe.sh> the error messages get displayed."
--
Man page: lesspipe.1
Issue:    pygmentize → B<pygmentize>(1)

"Among the colorizers a preferred one can be forced for coloring by setting "
"the ENV variable B<LESSCOLORIZER> to the name of the colorizer. For "
"I<pygmentize> and I<bat>/I<batcat> restricted option settings are allowed as "
"follows:"
--
Man page: lesspipe.1
Issue 1:  less → B<less>(1)
Issue 2:  syslog → I</var/log/syslog> (to match the file name in the example)

"As soon as B<lesspipe.sh> calls a program to convert the input the ability "
"to watch growing files (using the F command within less) is lost. This is "
"usually wanted for log files like syslog. To temporarily disengage "
"B<lesspipe.sh> a colon as the last argument for B<less> needs to be added as "
"e.g in"
--
Man page: lesspipe.1
Issue:    +F → B<+F>

"or B<less> can be called with the +F argument, which is equivalent to F "
"within the pager:"
--
Man page: lesspipe.1
Issue 1:  cat → B<cat>(1)
Issue 2:  B<ccze> → B<ccze>(1)

"Appending a colon to the file name does not work, as then the filter has to "
"be engaged to at least remove that colon and use cat for the original file.  "
"On the other hand non growing log files can be colorized using B<ccze>.  Its "
"recognition as a log file is difficult if not ending in I<.log> but can be "
"forced appending B<:.log> to the file name as e.g in"
--
Man page: lesspipe.1
Issue:    in the chain raw format → in the chain in a raw format

"To display the last file in the chain raw format, a colon (I<:>) has to be "
"appended to the file name. If it does contain a colon, then the alternate "
"separator character equal sign (I<=>) has to be used."
--
Man page: lesspipe.1
Issue 1:  B<zsh> and B<bash> → B<zsh>(1) and B<bash>(1)
Issue 2: less_completion → I<less_completion>

"With the provided I<lesscomplete> (for B<zsh> and B<bash>), I<_less> (for "
"B<zsh>) and I<less_completion> (for B<bash>) files a tab completion for "
"files in archives can be accomplished.  Entering a colon (:) or an equal "
"sign (=) after an archive file name and then pressing the tab key triggers "
"the completion mechanism.  This also works in chained archives. The files "
"I<lesscomplete> and I<less_completion> have to be in one of the directories "
"listed in B<$PATH> and the function I<_less> for B<zsh> in a directory "
"listed by I<$fpath>. The less_completion script has to be sourced within a "
"bash initialization script, e.g. in I<~/.bashrc>. New directories such as "
"I<~/scripts> and I<~/.fpath> can be added using the commands"
'''

**Comment by g-branden-robinson** [comment]
> Most of the other[ issue]s are requests to format command line options in bold. This is a common convention but is not universal.

I maintain _groff_ and I think I can throw some light here.

I too have seen mixed usage, even in historical man pages.  I seem to remember frequently seeing italic markup on command-line options in man pages originating in BSD, but don't recollect whether that was on systems that predated the Great Rewriting in _mdoc_ circa 1990 (4.3BSD/Net-2, I think?).

However, the choice of boldface for option literals (_cf._ arguments _to_ options) does have, in my view, solid and consistent precedent in the first _man_(7) pages that ever existed, in Seventh Edition Unix.  (Man pages existed before that, but the macros used to format them are extinct--they were not _man_(7) documents.)

https://minnie.tuhs.org/cgi-bin/utree.pl?file=V7/usr/man/man1/cat.1
https://minnie.tuhs.org/cgi-bin/utree.pl?file=V7/usr/man/man1/ls.1
https://minnie.tuhs.org/cgi-bin/utree.pl?file=V7/usr/man/man1/du.1
https://minnie.tuhs.org/cgi-bin/utree.pl?file=V7/usr/man/man1/grep.1
https://minnie.tuhs.org/cgi-bin/utree.pl?file=V7/usr/man/man1/od.1
https://minnie.tuhs.org/cgi-bin/utree.pl?file=V7/usr/man/man1/ps.1

(I tried to pick man pages that people would be very likely to have seen owing to them documenting commands that one can scarcely get through a shell session without; it was kind of fun rediscovering which commands in those days _didn't accept **any** options_.  One Bell Labs CSRC luminary--I think it was Rob Pike--is on record many times lamenting the presence of `-u` in V7 _cat_.) 

> For example, the man pages for the widely used programs git, find, vim, curl and magick don't format options as bold.

I would rule out _git_ as an example because it doesn't make this decision for itself, instead delegating it to _docbook-to-man_(1), which is downright _reviled_ by maintainers of _man_(7) formatters.

Regarding _find_, the man page from the version I have:

```
$ find --version | head -n 1
find (GNU findutils) 4.8.0
```

...indeed leaves off the boldface in its "Synopsis" section--in fact, after the command name it omits font style changes altogether--but seems _mostly_ consistent about using bold for options per se everywhere else in the page.  For example, the "Options" section starts like this.

```
.SH OPTIONS
The
.BR \-H ,
.B \-L
and
.B \-P
```

Checking macro usage, we see only one italic font style macro used to mark up anything:

```
 $ zgrep -E '^\.(IR*|RI) .*\\-' $(man -w find)
.I bug\-findutils
```
...which isn't a command-line option, versus many occurrences of such with bold.

```
$ zgrep -Ec '^\.(BR*|RB) .*\\-' $(man -w find)
359
```

The document does fail to set options in bold when using them as paragraph tags sometimes.

```
$ zgrep -E '^\.IP .*\\-' $(man -w find) | head
.IP \-P
.IP \-L
.IP \-H
.IP "\-D debugopts"
.IP \-Olevel
.IP \-daystart
.IP \-follow
.IP "\-regextype \fItype\fR"
.IP "\-warn, \-nowarn"
.IP \-d
```

This looks to me like inexpert use of _man_(7).  They should be using the `TP` macro so that they can put the tag on the next input line and call a macro like `B` or `BI` to set the parameters.

I fully agree with you that _vim_(1)'s practice is to not set options in anything but roman.

_curl_(1)'s man page is also produced by a generator.  Its source says:

```
.\" DO NOT EDIT. Generated by the curl project gen.pl man page generator.
```

I see multiple style problems, like setting the whole synopsis in bold and failing to escape hyphens used as dashes.  These could be problems with the `gen.pl` script.  I would not regard this document as testamentary of conscious man page style choices.

The ImageMagick (GraphicsMagick?) man pages seem also to be programmatically generated--but with no disclosure of the generator's identity, a poor practice if true--and more crudely than any of the foregoing examples.  Looking at the source of _display_(1) on my system, I see what appears to have once been a plain text document; large chunks of the document exhibit no *roff syntax at all.  `TP` is applied uselessly to a single-line synopsis, and paragraphing macros are otherwise _never_ used.  So this project, too, I would not give any weight as an example of good _man_(7) authorship.

> I will consider changing less to format options as bold but currently I don't consider it to be an error.

I agree; it's not an error per se but a question of consistent style, which applies in multiple respects: (1) is a given man page document internally consistent?; (2) is it consistent with other man pages from the same project?; (3) is it consistent with common practice?

In my view there has been too little written about point (3), so I decided to create the [_groff_man_style_(7)](https://man7.org/linux/man-pages/man7/groff_man_style.7.html) man page in _groff_ 1.23.0 to document my findings and make recommendations.
