### ISSUE TITLE
Unable to scroll with mouse with #stop

### ISSUE THREAD

**Issue by xudongzheng** [gwsw/less#569]
If `LESSKEYIN` file has `#stop`, then there is currently no way to scroll with the mouse. To reproduce:

```
seq 100 > example
echo "#stop" > lesskeyin
LESSKEYIN=lesskeyin less --mouse example
```

Additionally, it doesn't seem like the mouse escape keys from
<https://github.com/gwsw/less/blob/03f9f1a63ccf6ee32cee40640eb23d53ef88b850/decode.c#L75-L76>

are defined in

<https://github.com/gwsw/less/blob/03f9f1a63ccf6ee32cee40640eb23d53ef88b850/lesskey_parse.c#L32>

**Comment by gwsw** [comment]
Fixed in 0df5d8b3d608f4876fd23c76c10d66c5452d8ecf in the post659 branch.
