### ISSUE TITLE
Uninitialized value used in ch_init

### ISSUE THREAD

**Issue by correctmost** [gwsw/less#573]
### Description
I noticed this issue while testing xfce4-terminal.  It doesn't seem to affect functionality, but I thought I'd report it anyhow.

### Steps to reproduce
1. `cat | valgrind --track-origins=yes ./less`
1. Press Ctrl + c
2. Press q

### Valgrind trace
```
Conditional jump or move depends on uninitialised value(s)
   at 0x112A98: ch_init (ch.c:858)
   by 0x11C0BB: edit_ifile (edit.c:611)
   by 0x11BA9A: edit (edit.c:399)
   by 0x11C705: edit_stdin (edit.c:903)
   by 0x11C413: edit_first (edit.c:740)
   by 0x10EC21: main (main.c:441)
 Uninitialised value was created by a stack allocation
   at 0x11BB15: edit_ifile (edit.c:433)
```
### Version info
- Tested with ec23abda5705b8c0e428576f64adcaf509f0dda8 on Arch Linux

**Comment by gwsw** [comment]
Fixed in 715297eb517494753135a53322770311ccf03a9e.
