### ISSUE TITLE
less some_file.bin does not show contents, but "No isoinfo available Install mkisofs to view ISO images"

### ISSUE THREAD

**Issue by gsalzer** [gwsw/less#578]
When using `less` to view a text file with the extension `.bin`, it doesn't show the file contents but the message
```console
No isoinfo available
Install mkisofs to view ISO images
```
How can I tell `less` to handle the file as a text file?

How to reproduce
--

```console
$ echo 'Some contents.' > file.bin
$ cat file.bin
Some contents.
$ more file.bin 
Some contents.
$ less file.bin
No isoinfo available
Install mkisofs to view ISO images
file.bin (END)
$ less --version
less 590 (GNU regular expressions)
$ lsb_release --all
Description:	Ubuntu 24.04.1 LTS
```

**Comment by avih** [comment]
Can't reproduce with less v590 on Ubuntu 22.04 LTS.

Are you maybe using lesspipe? (which is not part of this repo)

Can you try this?
```sh
LESS= less -L file.bin
```

If this works, then the error message is probably from lesspipe, and you should report it to them.

**Comment by avih** [comment]
> Are you maybe using lesspipe? (which is not part of this repo)

Well, for what it's worth, in Ubuntu lesspipe is part of the less package. See here at the "Downloadable files" section - https://launchpad.net/ubuntu/noble/amd64/less/590-2

However, it's an independent package, and not developed or maintained by the "less" developers, but in Ubuntu they just decided to bundle them together.

**Comment by gsalzer** [comment]
Thanks for researching and clarifying the issue. It is indeed the `LESSOPEN` variable being set to `lesspipe`. According to the man page of `lesspipe` (and according to your code snippet), files are identified by extension, not by contents, so the extension `bin` makes `lesspipe` believe that it is a special file.

```console
$ echo $LESSOPEN
| /usr/bin/lesspipe %s
$ LESSOPEN=
$ echo $LESSOPEN

$ less file.bin
Some contents.
file.bin (END)
```
