### ISSUE TITLE
less sometimes runs commands only after pressing Enter

### ISSUE THREAD

**Issue by injust** [gwsw/less#579]
I came across a really strange bug today. I reproduced it in a new Git repo with a minimal config, but it still seems very specific to my environment.

I am running `git diff` on a Bun lockfile, with git's pager set to [delta](https://github.com/dandavison/delta). delta pipes its output to less. I followed the instructions at https://bun.sh/guides/install/git-diff-bun-lockfile to configure Git to work with Bun lockfiles.

This asciinema recording can best explain what is happening: https://asciinema.org/a/Iy7ds9zCaqPTn5YAAabYe3F4b or [asciicast.txt](https://github.com/user-attachments/files/17406069/asciicast.txt)

Usually I press <kbd>f</kbd> and <kbd>b</kbd> to navigate, and <kbd>q</kbd> to quit. However, ~1/3 of the time, less doesn't seem to do anything until <kbd>Enter</kbd> is pressed. When this issue occurs, it persists until less exits.

The issue seems to stop if I do any of the following:

- Unset `core.fsmonitor`
- Remove `LESS=` from `core.pager`
- Run `bun ./bun.lockb` to convert both versions of the lockfile to text before diffing it

---

Git: 2.47.0
delta: 0.18.2
less: 661
macOS: Sequoia 15.1
Terminals: Ghostty and Terminal.app

---

.gitattributes:
```
*.lockb binary diff=lockb
```

.gitconfig:
```gitconfig
[core]
	fsmonitor = true
	pager = LESS= delta

[diff "lockb"]
	binary = true
	textconv = bun
```

bun.lockb files: [old.bun.lockb.zip](https://github.com/user-attachments/files/17406109/old.bun.lockb.zip) and [new.bun.lockb.zip](https://github.com/user-attachments/files/17406106/new.bun.lockb.zip)

Minimal repo that reproduces for me: [repo.zip](https://github.com/user-attachments/files/17413375/repo.zip) (test with `git diff HEAD^`)

**Comment by injust** [comment]
While the issue was happening (pressing `f` et al didn't execute immediately), I ran `printenv LESS` and pressed Enter when it was done. After that, less started running commands like `f` instantly.

This convinces me that this is a bug in less.

**Comment by gwsw** [comment]
I have not investigated this yet, but the symptom suggests that the terminal is not in raw mode. The fact that it happens inconsistently suggests that there is some kind of race when less starts up and sets the terminal mode, where another program, perhaps bun or delta, is also trying to set the terminal mode. If less sets the mode first and then the other program overwrites it, you will see this symptom. If the other program sets the mode first, then less will overwrite it and behave normally. If you run the ```!``` command (or use ctrl-Z) to run printenv, less will set the terminal mode again after the command completes, which explains why that seems to fix the problem.

**Comment by injust** [comment]
I immediately thought of delta's dark/light detection (grep for `--detect-dark-light` in https://dandavison.github.io/delta/full---help-output.html), but the documentation suggests the race condition doesn't come from there.

I tested by adding `--detect-dark-light=never` or `--dark` to delta in `core.pager`, but the issue still happens.

It would really surprise me if bun is setting the terminal mode.

**Comment by avih** [comment]
> It would really surprise me if bun is setting the terminal mode

I would bet on delta.

On windows, it also sets the console output CP to UTF8 even when stdout is not a tty, which also causses an issue with "less" - because when "less" starts the terminal codepage is UTF-8 (because delta modified it), but after delta exits it restores it to whatever was there initially, but "less" doesn't know that, so UTF-8 output gets broken.

I.e. IMO delta's terminal handling is problematic also on windows, so I would bet that it also changes the terminal mode uncoditionally in this issue - also when its stdout is not a tty.

**Comment by gwsw** [comment]
I installed delta and ran it under strace, and it appears that delta does indeed change the terminal modes. Note the call to TCSETSW:

```
...
fcntl(2, F_GETFL)                       = 0x2 (flags O_RDWR)
fstat(2, {st_mode=S_IFCHR|0620, st_rdev=makedev(0x88, 0x3), ...}) = 0
fstat(0, {st_mode=S_IFCHR|0620, st_rdev=makedev(0x88, 0x3), ...}) = 0
fstat(2, {st_mode=S_IFCHR|0620, st_rdev=makedev(0x88, 0x3), ...}) = 0
fstat(1, {st_mode=S_IFCHR|0620, st_rdev=makedev(0x88, 0x3), ...}) = 0
ioctl(2, TCGETS, {c_iflag=ICRNL|IXON|IXANY|IMAXBEL|IUTF8, c_oflag=NL0|CR0|TAB0|BS0|VT0|FF0|OPOST|ONLCR, c_cflag=B9600|CS8|CREAD, c_lflag=ISIG|ICANON|ECHO|ECHOE|IEXTEN|ECHOCTL|ECHOKE|PENDIN, ...}) = 0
ioctl(2, TCSETSW, {c_iflag=ICRNL|IXON|IXANY|IMAXBEL|IUTF8, c_oflag=NL0|CR0|TAB0|BS0|VT0|FF0|OPOST|ONLCR, c_cflag=B9600|CS8|CREAD, c_lflag=ISIG|ECHOE|IEXTEN|ECHOCTL|ECHOKE|PENDIN, ...}) = 0
write(2, "\33]10;?", 6)                 = 6
...
```

**Comment by gwsw** [comment]
It would be an interesting experiment to set your pager to a wrapper script that did something like
```
sleep 2
less $*
```
If that fixed the problem it would be evidence for the theory that less is racing with delta.

**Comment by avih** [comment]
> If that fixed the problem it would be evidence for the theory that less is racing with delta.

Yes, but it's not guaranteed to work even if delta is the cause, because it can block on stdout untill something (less) reads, and only exit after it completed its output. I.e. when "less" starts "delta" may still wait for something to dequeue its output.

**Comment by gwsw** [comment]
Evidence suggests that delta is changing the terminal modes in a race with less also changing the terminal modes. Please reopen if any other evidence appears that contradicts this theory.
