### ISSUE TITLE
Feature Request: Make search move to the correct position on long lines, instead of just focusing the correct line

### ISSUE THREAD

**Issue by sosmo** [gwsw/less#58]
Currently search (/, ?, n and N) only moves to the line of the next match, but if a line is long and doesn't fit the terminal window, less won't scroll to show the position of the match. The Busybox version of less, however, does bring the match into the view even if it's at the end of a very long line.

Here's an example creating a long line of A's that fills the terminal window, then trying to find the B at the end:

    (printf 'A%.0s' {1..10000} ; echo B) | less

Searching for "B" (`/b`) doesn't scroll the line and thus you won't see the matched "B". Pressing `G` moves to the end and you see it highlighted, but finding the "B" otherwise is very difficult.

This feature would make less work similarly to Busybox's version and would make less more useful for dealing with large data files.

**Comment by gwsw** [comment]
Fixed in 4a356316bbf103d21dbd4adc0ea19b7904881b04.
