### ISSUE TITLE
latest stable release 668  named "beta" and missing from gnu server

### ISSUE THREAD

**Issue by xosevp** [gwsw/less#580]
~gzip-tar and zip RECOMMENDED versions files at http://www.greenwoodsoftware.com/less/download.html are named "beta"~ (fixed).
Also it is  missing in the  gnu server ( https://ftp.gnu.org/gnu/less/ ).

Thank you.

**Comment by avih** [comment]
Additionally, this repo is also missing the tag `v668-rel`.

**Comment by gwsw** [comment]
All fixed.

**Comment by xosevp** [comment]
Thank you, now business as usual:
https://release-monitoring.org/project/1550/
https://repology.org/project/less
