### ISSUE TITLE
feature request: Signal handler to reload file

### ISSUE THREAD

**Issue by fragglet** [gwsw/less#582]
If you type an `R` in `less`, it reloads the current file, which is useful if the contents of the file are changing. It would be nice if this could be triggered externally by sending a signal.

A crude example of what you might do with this:
```
less processes.txt

.....

while true; do
  ps auwx > processes.txt
  kill -USR1 $LESSPID
  sleep 5
done
```

**Comment by gwsw** [comment]
Implemented in 132e657208bceb724fc6312e299cf6731950a6a0.

The LESS_SIGUSR1 and LESS_SIGUSR2 environment variables can be used to define the desired action when a USR1 or USR2 signal is received.

**Comment by fragglet** [comment]
Thank you!

**Comment by fragglet** [comment]
qq: Is there a reason that you added this for both USR1 and USR2? It occurs me that it potentially ties your hands if you find yourself wanting to catch another signal in the future since most systems only support the two user signals

**Comment by gwsw** [comment]
Ok, after consideration I have removed LESS_SIGUSR2 in 15a1ab992b17c09bc20f9bdc636dcf4a31b7259f. Only SIGUSR1 is currently supported.
