### ISSUE TITLE
Behavior of command "p" has changed (Go to a position N percent ...)

### ISSUE THREAD

**Issue by parke** [gwsw/less#59]
Ubuntu 19.10 provides less-487.
Ubuntu 20.04 provides less-551.

On Ubuntu 19.10 (with less-487), pressing "p" would move to the top of the file (i.e. to the 0% position), and would **redraw** the top of the file **at the top of the terminal**.  This would happen even if the file were short enough that the entire file could be displayed on the terminal all at once.

On Ubuntu 20.04 (with less-551), the behavior of "p" has changed.  If the file is short enough that the entire file can be displayed on the terminal, then pressing "p" will do nothing.  In other words, the file will not be redrawn at the top of the terminal.

Is this change intentional?

Is there any easy way to restore the old behavior of "p"?  (I prefer the old behavior.)

**Comment by gwsw** [comment]
I cannot reproduce this behavior in less-551. Pressing p redraws the screen from the top, even if the file fits on one screen. I wonder if the Ubuntu release has changed something. Can you try downloading less-551 from http://greenwoodsoftware.com/less/less-551.tar.gz and confirm whether you still see this issue?

**Comment by parke** [comment]
I will download and build 551 when I get a chance.  It may be several days.  What OS/distro are you using where you cannot reproduce it?  Fyi, I was able to reproduce with 551 on Void Linux.

**Comment by gwsw** [comment]
I've tried on Fedora, MacOS, and Cygwin. Perhaps there's some difference in your environment? Do you have any flags set in your LESS environment variable and/or lesskey file?

**Comment by parke** [comment]
I do have LESS set, but I can unset LESS and still reproduce.  Afaik, I do not use lesskey.  I will post an update once I have time to compile from source and do more testing.

**Comment by gwsw** [comment]
Ok, I'm able to reproduce this, so no need to test a self-compiled version. It turns out it was a flag in _my_ lesskey file that was preventing me from seeing it. I will look into this.

**Comment by parke** [comment]
Compiling four versions of less on Ubuntu 20.04 results in the following:
  version  551  buggy
  version  530  buggy
  version  520  buggy
  version  487  no bug

**Comment by parke** [comment]
I can reproduce the bug on Fedora 32, less 551 (as provided by Fedora), running on a Vultr.com VPS.  I am ssh'ing into the VPS from Ubuntu 20.04.  My terminal is xterm.

**Comment by parke** [comment]
I compiled the same four versions of less on the Fedora 32 VPS.  I get exactly the same behavior as on Ubuntu 20.04.  If I type "50p", the file will redraw at the top of the terminal.  However, typing just "p" does nothing (same as on Ubuntu 20.04).

Vultr also allows browser based VNC access to a VPS.  Using VNC, I can do a console login to the VPS and then reproduce exactly the same behavior on the console.

If you want to test on Vultr, you can run a small Vultr VPS for $0.01 per hour.

**Comment by parke** [comment]
Oh, sorry... I overlooked your message saying you were able to reproduce the issue.

**Comment by gwsw** [comment]
This should be fixed in less-560. If you have a chance to test it, let me know if it fixes your issue.

**Comment by parke** [comment]
How do I built it?  There is no ./configure script.  (I have forgotten how to use autotools.)

**Comment by gwsw** [comment]
See the PRE-INSTALLATION section in the README:

> If you are building from a clone of a git repository, type "make -f Makefile.aut".

**Comment by parke** [comment]
Thanks.  I get the following error when I run `make install`.

    make: *** No rule to make target 'less.nro', needed by 'install'.  Stop.

But if I run the un-installed copy of `./less`, the "p" command does now have the desired effect of moving the content to the top of the terminal.  Thanks!

**Comment by temporaryrespite** [comment]
you'll want `make -f Makefile.aut all dist`
then maybe something like:
```bash
sh configure --prefix=/usr --sysconfdir=/etc --with-regex=pcre --with-editor=vim                                                                              
make
```
