### ISSUE TITLE
Non-Latin characters in lesskey file

### ISSUE THREAD

**Issue by van-de-bugger** [gwsw/less#595]
I have the following `lesskey` file in my `.config` directory:

```
#command
й   quit
zz  quit
яя  quit
:й  quit
```

The file is in UTF-8 encoding.

Single character assignment (`й`) works, but two character assignments work only if both characters are Latin (e. g. `zz`), and does not work in case of non-Latin characters (Cyrillic in my case: `яя` or even `:й`): typing `zz` causes less to quit, but typing `яя` or `:й` does not.

For example, if I run `less lesskey` command, less shows the content of the file and message "lesskey (END)" in the bottom line. When I type the first character `я`, less hides the message in the bottom line and shows the character I typed. When I type `я` again, less rings the bell, and shows message "(END)" in the bottom line, but does *not* quit.

OS: Fedora 38.

The issue is reproduced with:

* less 633 (POSIX regular expressions) (installed from the OS repo),
* less 668 (POSIX regular expressions) (built from the sources), 
* less 670 (POSIX regular expressions) (built from the sources).

**Comment by gwsw** [comment]
Fixed in deb9a06e16ae1afac4bda8d9199a32df162b50bd.

**Comment by van-de-bugger** [comment]
> Fixed in deb9a06.

Confirmed.
