### ISSUE TITLE
shift option unrecognized in lesskey-specified $LESS unless long form

### ISSUE THREAD

**Issue by smemsh** [gwsw/less#597]
example .lesskey:
```
#env
LESS = -#3
```
this will not take effect, in latest master (3b8c09d).  options before it are recognized.  also recognized is `--shift=3`.  it is an effective workaround, but maybe `-#3` should work since it does in `$LESS`.

**Comment by gwsw** [comment]
The # sign is a comment marker. You can include it literally by preceding it with a backslash, as the lesskey man page notes:

>A  backslash  followed  by  any  other character indicates that
            character is to be taken literally.  Characters which  must  be
            preceded  by backslash include caret, space, tab, hash mark and
            the backslash itself.

So you would put this in your lesskey file
```
LESS = -\#3
```

**Comment by smemsh** [comment]
Ok, the man page said:

> lines which *start* with a hash mark (#) are ignored

so I didn't think they needed to be escaped in the middle of a line.

**Comment by gwsw** [comment]
Good point. I have updated the man page to be more clear.
