### ISSUE TITLE
less exits when searching while reading from a pipe

### ISSUE THREAD

**Issue by rschupp** [gwsw/less#598]
Try the following
```
cat /etc/passwd | less
```
then search "/" for something: less will immediately exit with $?=1.
I expect it to position to the first match or display "not found".
This worked in v669 and broke in v670, `git bisect` blames ca59eda0baea2409ebef33406269474d61efd93b.

OS etc: Linux 6.12, running Debian sid.

**Comment by gwsw** [comment]
This seems to be the same as #592. It was fixed in 8db7960040647b94812309d4b48ea9614bd04c55.
