### ISSUE TITLE
Please provide a way to disable the --rscroll option.

### ISSUE THREAD

**Issue by GWHAYWOOD** [gwsw/less#60]
The default reverse-video '>' character is extremely distracting but there appears to be no way to revert to the original behaviour of simply truncating lines which are too long to fit on the screen.

Please provide some way (for example --rscroll= with no argument) of reverting to the original behaviour (i.e. no replacement of the rightmost character on the screen).  It should also be possible to set the behaviour in .lessrc or similar of course.

To avoid breaking the Principle Of Least Surprise, in general changes like this should be options which need to be requested e.g. on the command line rather than default behaviour.

**Comment by gwsw** [comment]
You can disable the rscroll char display by setting --rscroll to a dash ("-"). This is mentioned in the man page:

>        --rscroll
              This  option  changes the character used to mark truncated lines.  It may begin
              with a two-character attribute indicator like LESSBINFMT does.  If there is  no
              attribute  indicator, standout is used.  If set to "-", truncated lines are not
              marked.

**Comment by GWHAYWOOD** [comment]
Ah - my mistake.  Looks like there's no man page in the Zip file and when I grepped the source for rscroll I only saw the brief help, which doesn't mention the '-' trick.

Thank you, all I have to do now is modify .bashrc on a couple of hundred machines... :)
