### ISSUE TITLE
Makefile.wnm does not create help.c or funcs.h

### ISSUE THREAD

**Issue by jftuga** [gwsw/less#61]
I am trying to compile `less` with Visual Studio 2019 with `Makefile.wnm`

When I run `nmake /f Makefile.wnm`, I get the following error:

```
Microsoft (R) Program Maintenance Utility Version 14.25.28614.0
Copyright (C) Microsoft Corporation.  All rights reserved.

NMAKE : fatal error U1073: don't know how to make 'funcs.h'
Stop.
```

What needs to happen somewhere in `Makefile.wnm` for it to succeed are these commands:

    perl mkhelp.pl < less.hlp > help.c
    perl mkfuncs.pl * > funcs.h

If I run these first, then `nmake` will succeed.

Please note that `lessecho.exe` is not built with this Makefile.  Could that also be fixed?

**Comment by gwsw** [comment]
Are you building from a released tarball, or from a git clone? If the latter, you need to first run "make -f Makefile.aut", as described in the README.

**Comment by jftuga** [comment]
When I run Visual Studio `nmake /f Makefile.aut`, I get the following error:

    Microsoft (R) Program Maintenance Utility Version 14.25.28614.0

    Makefile.aut(27) : fatal error U1001: syntax error : illegal character '{' in macro
    Stop.

I also tried the `mingw-64` make program, but get this result:

    mingw32-make.exe -f Makefile.aut

    mv -f ./help.c ./help.c.old
    mv: cannot stat './help.c': No such file or directory
    mingw32-make: [Makefile.aut:50: help.c] Error 1 (ignored)
    rm -rf help.c
    ./mkhelp.pl < less.hlp > help.c
    if cmp -s help.c help.c.old; then mv -f help.c.old help.c; fi
    mv -f ./funcs.h ./funcs.h.old
    mv: cannot stat './funcs.h': No such file or directory
    mingw32-make: [Makefile.aut:59: funcs.h] Error 1 (ignored)
    perl ./mkfuncs.pl ./main.c ./screen.c ./brac.c ./ch.c ./charset.c ./cmdbuf.c ./command.c ./cvt.c ./decode.c ./edit.c ./filename.c ./forwback.c ./help.c ./ifile.c ./input.c ./jump.c ./line.c ./linenum.c ./lsystem.c ./mark.c ./optfunc.c ./option.c ./opttbl.c ./os.c ./output.c ./pattern.c ./position.c ./prompt.c ./search.c ./signal.c ./tags.c ./ttyin.c ./version.c >./funcs.h
    if cmp -s funcs.h funcs.h.old; then mv -f funcs.h.old funcs.h; fi
    ./mkutable -f2 Mn Me -- unicode/UnicodeData.txt > compose.uni
    ./mkutable -f2 Cf -- unicode/UnicodeData.txt > fmt.uni
    cd .; autoheader; autoconf
    /usr/bin/sh: autoheader: command not found
    /usr/bin/sh: autoconf: command not found
    mingw32-make: *** [Makefile.aut:56: configure] Error 127

I tried installing `autoconf` but was not able to figure out how to do this under Windows.

___

Next, I downloaded `less-561.zip` from the Releases page.  I tried running bot `nmake /f Makefile.aut` and `nmake /f Makefile.wnm` but both these resulted in the same error.

What is the best way to compile `less` under Windows? I am open to using either `Visual Studio` or `mingw-w64`.  I could either download the .zip from the Release section or run `git clone`. Ideally, the build would run *out of the box* by running `make` without any further modifications.  `Visual  Studio` would be my first choice as I would like to use something like https://circleci.com/ or https://www.appveyor.com/ to automate builds each time you release a new version. As far as I can tell, these build systems support `Visual Studio` but not (at least easily) `mingw-w64`.

**Comment by gwsw** [comment]
Caveat: I have not tried any of this, but I believe that after running the mingw32-make -f Makefile.aut, you can ignore the autoconf failure and just run make -f Makefile.wnm. Autoconf is trying to create the makefile but since the Windows uses a prebuilt makefile (Makefile.wnm) the autoconf step is not needed.

Alternatively, if you build from the tarball rather than a git clone, you don't need to use Makefile.aut (which isn't included in the tarball anyway), and you can just run make /f Makefile.wnm. Since funcs.h is included in the tarball you shouldn't get the original error

**Comment by jftuga** [comment]
These two files from https://github.com/gwsw/less/releases do not contain either `funcs.h` or `help.c`:

* https://github.com/gwsw/less/archive/v561.zip
* https://github.com/gwsw/less/archive/v561.tar.gz

Also, `Makefile.aut` is included in both.

If you could repackage these archives with those 2 files, I think the `make` would then be successful.

**Comment by gwsw** [comment]
Sorry, I was not clear. I'm referring to the release tarballs on the less web site, like
http://greenwoodsoftware.com/less/less-561.tar.gz

**Comment by jftuga** [comment]
I was able to run `nmake  /f Makefile.wnm` on the provided URL tarball and `less.exe` and `lesskey`  built successfully. 

Why are these 2 files included on the website tarball but not with the github release -- just curious? Is it because they should be created the `perl` scripts? If so, it would be nice if `Makefile.wnm` included those as targets such that `Makefile.aut` would not need to be invoked first (just my opinion).

Also, I noticed that `lessecho.exe` is not a `Makefile.wnm` target.

Thanks for all of your prompt replies. I really appreciate your help today.

**Comment by gwsw** [comment]
The expectation is that ordinary users will download official releases from the greenwoodsoftware site. They should not be using intermediate releases from git, which are not fully tested and may be buggy. In most cases a git clone should be used only by a developer working on less itself.

lessecho is not used in a Windows environment, so there's no reason to build it in the Windows makefile.

**Comment by jftuga** [comment]
Thanks for your explanations.  I am closing this issue.

**Comment by jftuga** [comment]
This is now automated here for Windows builds with [AppVeyor](https://www.appveyor.com/),

https://github.com/jftuga/less-Windows

See also:

https://github.com/jftuga/less-Windows/issues/1#issuecomment-628469023

We would like to use my repo as a source for [Chocolatey](https://chocolatey.org/) for a Windows binary version of `less.exe`.
