### ISSUE TITLE
less does not quit by q before it has written a viewport of text.  

### ISSUE THREAD

**Issue by jarnos** [gwsw/less#62]
I do not know, if it is intentional.

Test shell script:
while true; do echo x; sleep 1; done | less

Workaround:
Press Ctrl-C and then q. (For some reason I get exit code 128 then in Bash, 0 in Dash.)
q is not needed, if --quit-on-intr is used, but then the exit code is 2 (so that caller can identify the reason).

Launchpad bug report: https://bugs.launchpad.net/ubuntu/+source/less/+bug/1874971

**Comment by gwsw** [comment]
Less cannot read input from the terminal while it is reading data from the file. This is the same issue as #49, so I am closing this one to keep it in one place.

**Comment by gwsw** [comment]
As of less-617 it is possible to abort the initial screen fill with ctrl-X (on systems that support poll()).
