### ISSUE TITLE
Wrong output with fake .exe file

### ISSUE THREAD

**Issue by fturco** [gwsw/less#65]
I have a Gentoo Linux system with the `sys-apps/less-561` package.
I also have a file called `RARBG_DO_NOT_MIRROR.exe` which is a fake executable:

```
$ file RARBG_DO_NOT_MIRROR.exe 
RARBG_DO_NOT_MIRROR.exe: ASCII text

$ wc RARBG_DO_NOT_MIRROR.exe 
 1 18 99 RARBG_DO_NOT_MIRROR.exe

$ cat RARBG_DO_NOT_MIRROR.exe 
This is not an .exe file. This is just a placeholder to prevent mirroring over other public sites.
```

But if I run try to open it with `less`, I get the following output instead:
```

7-Zip [64] 16.02 : Copyright (c) 1999-2016 Igor Pavlov : 2016-05-21
p7zip Version 16.02 (locale=en_US.UTF-8,Utf16=on,HugeFiles=on,64 bits,1 CPU Intel(R) Core(TM)2 Duo CPU     E8400  @ 3.00GHz (1067A),ASM)

Scanning the drive for archives:
1 file, 99 bytes (1 KiB)

Listing archive: RARBG_DO_NOT_MIRROR.exe


Errors: 1

7-Zip (a) [64] 16.02 : Copyright (c) 1999-2016 Igor Pavlov : 2016-05-21
p7zip Version 16.02 (locale=en_US.UTF-8,Utf16=on,HugeFiles=on,64 bits,1 CPU Intel(R) Core(TM)2 Duo CPU     E8400  @ 3.00GHz (1067A),ASM)

Scanning the drive for archives:
1 file, 99 bytes (1 KiB)

Listing archive: RARBG_DO_NOT_MIRROR.exe


Errors: 1

7-Zip (a) [64] 16.02 : Copyright (c) 1999-2016 Igor Pavlov : 2016-05-21
p7zip Version 16.02 (locale=en_US.UTF-8,Utf16=on,HugeFiles=on,64 bits,1 CPU Intel(R) Core(TM)2 Duo CPU     E8400  @ 3.00GHz (1067A),ASM)

Scanning the drive for archives:
1 file, 99 bytes (1 KiB)

Listing archive: RARBG_DO_NOT_MIRROR.exe


Errors: 1
```

On my system I also have an `app-arch/p7zip-16.02-r6` package which provides a `7z` command.

It seems that `less` calls `7z` instead of directly displaying the contents of `RARBG_DO_NOT_MIRROR.exe`, even if it's not a 7z archive. Why?

**Comment by gwsw** [comment]
I would guess that you are using a LESSOPEN script which calls 7z when the file extension is .exe. I can't be more definitive because there is no LESSOPEN script in the less distribution; it was probably added by Gentoo. Check your environment and/or .lesskey file to see what LESSOPEN is set to.

**Comment by fturco** [comment]
On my Gentoo system, the `LESSOPEN` environment variable is defined in the `/etc/env.d` directory:

```
$ grep -r LESSOPEN /etc/env.d
/etc/env.d/70less:LESSOPEN="|lesspipe %s"

$ echo $LESSOPEN
|lesspipe %s
```

The following command works as expected:

    LESSOPEN="" less RARBG_DO_NOT_MIRROR.exe

Inside `/usr/bin/lesspipe` I found the following line:

```
        *.7z|*.exe)   7z l -- "$1" || 7za l -- "$1" || 7zr l -- "$1" ;;
```

Should I simply unset the `LESSOPEN` variable to fix this problem? Is there something else to do?

**Comment by gwsw** [comment]
Yes, if you don't wish to use your system's lessopen script, you can unset LESSOPEN in your environment, or use the -L flag.

**Comment by fturco** [comment]
I removed both the `LESS` and the `LESSOPEN` environment variables by emptying the `/etc/env.d/70less` configuration file and then running:

    env-update && source /etc/profile

After logging out and then logging in again, the `less RARBG_DO_NOT_MIRROR.exe` command works as expected. Problem solved.

Thank you for the help!
