### ISSUE TITLE
Problem with searching when a line has an escape character in it

### ISSUE THREAD

**Issue by mathleblanc** [gwsw/less#76]
[less-551-bug.txt](https://github.com/gwsw/less/files/5001083/less-551-bug.txt)

**Comment by gwsw** [comment]
Although the man page needs to be made clearer about this, -R should only be used on files which contain no escape sequences other than SGR color sequences.  A non-SGR escape sequence, or a stray escape character, could be interpreted by the terminal as a sequence that affects the output, so less can't safely output such characters to the terminal (except in -r mode, where you are telling less that you are willing to take that risk).  I will edit the man page to make this clearer.
