### ISSUE TITLE
-R doesn't work

### ISSUE THREAD

**Issue by drboone** [gwsw/less#77]
WIth the envariable LESS set to:

`LESS=-e -i -j4 -m -q -R -x4 -P"file %f (%i of %m) line %lb of %L [%pb\%]--"`

and the output shown in [output.txt](https://github.com/gwsw/less/files/5093185/output.txt), `less` shows 
[dashr.txt](https://github.com/gwsw/less/files/5093192/dashr.txt) instead of the expected colorized output.

Replacing -R with -r results in the expected colorization, and the expected long-line induced counting and screen layout issues.

There are no LESSANSI* variables set.

less 551, FreeBSD 12.1.

**Comment by gwsw** [comment]
I cannot reproduce this. Do you by chance have the LESS variable set in your lesskey file? Such a setting will override the environment variable LESS. An interesting test would be to reproduce your problem and then within less type "_r". This will print the setting of the -r/-R flag.

**Comment by drboone** [comment]
I don't have such a setting in my .lesskey, just a few keystroke definitions.  _r produces:

`Display control characters directly, processing ANSI sequences  (press RETURN)`

**Comment by drboone** [comment]
Here's the only code patch applied by FreeBSD.

[charset.c.diff.txt](https://github.com/gwsw/less/files/5093444/charset.c.diff.txt)

**Comment by gwsw** [comment]
You're running that patch? I'm not sure exactly what it's intended to do, but it looks suspicious to me. Can you run an unpatched version from github and see if it acts the same?

**Comment by drboone** [comment]
I _think_ the FreeBSD supplied `less` is built with that patch.  Either removing that patch and rebuilding using the usual ports mechanisms, or using unmolested source from a tarball results in the expected color behavior.  I'll go badger the FreeBSD folks now.  Thanks!
