### ISSUE TITLE
Mention GitHub issue tracker on man page

### ISSUE THREAD

**Issue by jidanni** [gwsw/less#8]
Man page says
```
Send bug reports or comments to <bug-less@gnu.org>
```
but the user cannot even tell if the mail arrived.

In fact if the man page instead said

```
Report bugs at https://github.com/gwsw/less/issues/
```
Then he could rest assured within seconds that his bug reports were
indeed not lost.

**Comment by gwsw** [comment]
Fixed in less-551.
