### ISSUE TITLE
Allow tail mode to work if file recreated

### ISSUE THREAD

**Issue by rdp** [gwsw/less#86]
Hello.  Currently if running less "F" to tail a file.

If a separate process removes the file and starts writing a "new file" there with the same name, less basically freezes tailing the end of the (now removed/renamed) file.

Would be great to have an option equivalent to `tail -F` for less's tail mode.  Cheers!

https://unix.stackexchange.com/questions/4351/is-there-a-way-to-dynamically-refresh-the-less-command

**Comment by gwsw** [comment]
Does the --follow-name option do what you want?

**Comment by rdp** [comment]
This does work, not sure why I missed it except it's way down on the man page.  Might could add the word "tail" there so it's easier for followers.

If you happen to be looking for extra credit, I did see a request out there for a "follow-name" option for non-tail use as well... (Basically "reload whole thing into RAM if file overwritten" I guess?).  https://serverfault.com/questions/445899/less-with-update-file-like-functionality ... :)
