### ISSUE TITLE
Toggle search highlight no longer works

### ISSUE THREAD

**Issue by folkol** [gwsw/less#88]
I use to toggle highlighting of search results back and forth with ESC-u, but since commit 5651293 this no longer works. I would like to understand the rationale behind this change, if this was indeed the intended behaviour. (And if not, consider this a plain old bug report.)

**Comment by gwsw** [comment]
This was a deliberate change, in response to a request for a way to clear the current search pattern. In retrospect, this feature should probably not have been overloaded onto the ESC-u command. I think it would have been better to leave ESC-u as a toggle and add a new command, perhaps ESC-U, to clear the search pattern. Although I'm somewhat loathe to change the functionality yet again, I'm leaning toward changing ESC-u back to the old behavior as you request and adding a new command to clear the search pattern.

**Comment by folkol** [comment]
All right. Thanks for the explanation!

**Comment by gwsw** [comment]
Fixed in 7b1787ed1ad05241cce0eff71918df79573761a4.
