### ISSUE TITLE
Adding the ability to process the vim: command in files to automatically set tabstops

### ISSUE THREAD

**Issue by jefferysmall** [gwsw/less#89]
Great program.  I use two scripts the invoke less with tab stops set to either 4 or 8 and I have a keyboard mapping to quickly toggles between them.  However, I have a lot of different files with both sets of tab stops and I use the vim editor option to automatically set the tab using a **:vim ts=4** or **:vim ts=8** line near the top or bottom of the file -- usually on a comment line.

Is this something **less** could be made to look for and process when the input is a file rather than stdin?

Thanks.

**Comment by gwsw** [comment]
Added --modelines option in db9785f6df628d2dd96595e40f2f002bdaf4e95d. It will work whether the input is a file or a pipe.

**Comment by jefferysmall** [comment]
That's great.  `Just out of curiosity, do the modeline commands need to be at the top of the file or will less find them at the bottom as well?  The reason I ask is because, in the case of a pipe, the end of the file will not necessarily be seen during the display at the start.  I don't see any way around this, but I thought I would ask for clarity.

Thanks for implementing this.  BTW, in what release version will this option appear?

**Comment by gwsw** [comment]
Right, the modelines must be at the beginning of the file, in the first N lines where N is the parameter of the --modelines option. The feature will be in the next release, which will be less-620, although that will probably be a beta release and not a final release.

**Comment by jefferysmall** [comment]
Great.  Thanks again.
