### ISSUE TITLE
option -j<n> yields n-1 spurious lines before the beginning of the file when going to line 1

### ISSUE THREAD

**Issue by vinc17fr** [gwsw/less#93]
When the `-j` option is used with a value larger than 1 (the purpose of this option), n−1 spurious lines appear before the file when going to line 1. For instance, type:

    printf "Line %d\n" `seq 200` | less -Mj3

and in `less`, type `<` to go to the beginning of the file (line 1). One gets:
```
~
~
Line 1
Line 2
Line 3
Line 4
Line 5
Line 6
```

Though the specification of `-j` says that the target (line 1) should appear here at the third line of the terminal, giving empty context lines is useless.

I thought that in `command.c` for `case A_GOLINE:`, changing
```
if (number <= 0)
  number = 1;
```
to
```
if (number < jump_sline)
  number = jump_sline < sc_height ? jump_sline : sc_height;
```
would solve the issue, but this confuses logical lines with physical lines, so that this does not work well when the file starts with long lines.

**Comment by gwsw** [comment]
I agree and have merged your change.
