### ISSUE TITLE
less -R: color codes only apply until end of line

### ISSUE THREAD

**Issue by loewenheim** [gwsw/less#99]
Consider the file `test.txt`:
```
[0m[31mLine 1
[0m[0m[32mLine 2
Line 3
Line 4
Line 5
[0m
```
`less -R test.txt` only shows lines 1 and 2 in color (red and green, respectively) and lines 3–5 uncolored. `cat test.txt` shows lines 2–5 in green, which is what I would expect. I don't know if the behavior of `less -R` is intentional, but I certainly find it surprising.

**Comment by gwsw** [comment]
The problem with letting colors spill across multiple lines is if you jumped to a random place in the file (with the p or G command for example), there would be no way to tell what color the first displayed line should be, without scanning the entire file from the beginning. That would be a heavy price to pay to support a fairly rare situation.

**Comment by loewenheim** [comment]
I see, that certainly makes sense. I think it might be a good idea to mention this in the man page, what do you think?

**Comment by gwsw** [comment]
I agree. I have added a mention to the man page in 1bafa63fbbd12957ba6554f43e7b67b0d4321d1f.

**Comment by loewenheim** [comment]
Great, thank you very much!
